apiVersion: v1
kind: Secret
metadata:
  name: clawdbot
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:nkpED3TXvZpgJkKhMJrJ7LKwoBXVkFK39/0v53upqfAKPookOm3iGQ==,iv:QUHRFxfm2aT7JyPevVRlPqVS4YMfS/jjsWN48N37xaI=,tag:oY4B90GmHVNdNl49zluTvw==,type:str]
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:oMinCWB6JivJu8M4MteIRlzioGY3AvoZIud8cQOKA5v8lV5s1vMJkV+1mpUOyjP1yRTWsbOS9m8fdGVZgbO0aFlxnU5lZoo+wLpUUgobTGom+Wws+HUnkNlKmDXpN1ZS/sthCci43HkYAkHEfl62wFCFC2+UbgA23jeAey5s2kU=,iv:n6BnYztC+G2+cJRO4wiwfPMCCsuye5MIBWf7E/RLBXY=,tag:YyrjCoYaO5QZj54vs9kn/g==,type:str]
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:AoYY4Pu+zZvugf+S77Y45mkhAP6QR3prOm9U3/5jl/8K6uPGms11Al/vVXZu/8GYqzOmGhQ1mFSbKv5GCJlz/UiNo8Y92YFD8nOxmpeVJXbfMQ==,iv:OMKUUvY0O7O/xfhabAQAQexxH0oGFudencP12uqjiPU=,tag:yFow+KknS/4HxU4mvBOAxA==,type:str]
  GH_TOKEN: ENC[AES256_GCM,data:xpevmOvJfdV9C1+8ISASMhMDKzPDBLZfEGxaU8aecJzVdlP3Hy8LIzvSlLi4YkYHew==,iv:8Yd7kTvP8T/KET0JhmYVa7nWYL6hJ7gRaj2CAYAvAHw=,tag:JN3JOfi7OBPnVBePo9Ed5g==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bHhZYzdSdUtaZHcvNGJT
        U2hiQW4rS3pCUWhZTks4bHJVWGs2ZG1GL1NFCkFiK0JUcXJGbUcyendRQ1RvNUd1
        UTREeGRzM0FYeE5UVEo5SnFXVkpNWmcKLS0tIEoxTkxzYjhNV0V6cndyVm05dTV4
        eGxWL3pSaEZtTXRzQlc3aWlFWDhZbTgK8RRCHRHCci7bXUpBc6FsqX2jWGGUs8dY
        eph50A9fY3+7373jZeRWpI/W7xvWbwVqZ1+B/zW8J4LGlg8Xsv3nXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T13:38:06Z"
  mac: ENC[AES256_GCM,data:I+y/Kfbpdg4O0NvVDhMuVYa1CNeWcUtvoF1BZqFm6YmnVRD+SRw3Sh3p0PFgZyYMeGKqSw9NTkrPLhwA1xb/2MQCI0PQPyQLmXZ/xMzsMLbo78J57PyfeVXZX5DAH3frtWp9NwBYhemkgm+rlvZrjPCzogE3FGTGdm8HoudmZ8A=,iv:0MGRrdn7dnC5eHpFPQ9tuKbAWxEsTwslVLgZcZg6CIs=,tag:wABPOYSzI5LMqXovXt0E5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
