apiVersion: v1
kind: Secret
metadata:
  name: clawdbot
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:Js66+7tT2UJ4+UQa0+bpMie83YgOwkXfBFlakPHSqWbLWWtI0w/boQ==,iv:eT1vgszBM1RQcGi/9J1cqB9lNIrRkr/MQmMh/83Udd0=,tag:Bpl+d0nmDLY5cKT+F88kcg==,type:str]
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:m9+UAaLWYvtycapkQRPV8ZPOrqQjS7BLDKmP7ZEWm8zeDqxAUQgDOAq0ToM2eHSwmsguKTaPQGIDpNhoAehIt+p+WO12ePtMZt0pzYexPx7wcYeZ7Q73dpMusK99EQtabN3Cow4VzF0O0mUqJoz9mejnOl3p7nfIPZBoKU474hg=,iv:u8nEaSzOcMDoZBAxiU5R1UMZuE7KwmU2+Q1JG8baDu8=,tag:uwHTijpAjhmm2hJkOODd4w==,type:str]
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:DuDqR/O2R6OUl2KmKJrhzEsCvyNA/DF4c9ibETQUxo2XD/UvckPh+rfyu/3Lhfrxe8DZWUtmLtthXhSZJxquRWbyrafBcnsyF9gqH2YPS54w0A==,iv:ysIqEab03k3P5L8I+qRBUEty/NQ3l4PM6pY1cRbRr/0=,tag:fUXPS6atasi2uDLfJKhXbw==,type:str]
  GH_TOKEN: ENC[AES256_GCM,data:9vauLvFw1ytCFXXmOz1KD8Ortp0f7JPYhsWE+qj8yuPfllJgA83afUk7elHruXue1g==,iv:adw29BDDO1DdW/Isrr6sXDjTM+8CahHm9RFrh1Xcf0k=,tag:TysTf+04XDs25ybxYU0dRg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMExqdVNCK05qVEhUWVJk
        a1BTQ3I5UzVrQW1mVE54b2xZZWxqVTZWL3hFCjRKbnJldFBkQ3MzUVdPbUZrelAv
        ZDd5aXI4RkRYaHVZRkROK2owazl5elkKLS0tIDRWOVd4WE10d1NxVkxtQWxDMVRK
        KzdLbGxydVRBY05xbUFvb1J6aEhtTjgKtc7V50zJnrDZnDEWKzKViEGvHqEosOuX
        HEZwK5ElcSKzCaUR6egtNZNrJXaUSKakN0ZebxrprSCjhBBc8Ve4gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T13:42:45Z"
  mac: ENC[AES256_GCM,data:r0x5DA4AZUuvD/Qi4hh87MAvC+vaNgqnRkzheMLGUVujMFfPRPhWpn5cOD0JJquzReuJ9Hm7MCk6bCRfHQa74s6xp5GXbpK78iQ1WUVdN45jYui6MuqmeM9N07rxJgBnIfsAEnojzICE4EN9Ri75o90O2VaIEiH25EWEHTRqsBQ=,iv:/InXS8MIkhcv0PwY/1YM4YSFzCgzi+Ds//f7995+NX0=,tag:I64mb6E2fWj4BHZ6K/9iLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
