apiVersion: v1
kind: Secret
metadata:
  name: clawdbot
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:giOILg2pHKbXT2yZeNZyvfMYVEbze3a+a20bCJsHWX1alWAGPZ4+fw==,iv:B+NRmaD0zyLqCsFJIR+PgQR1y58IYtIz5sBpqxgVDhw=,tag:yGwHNGIfEw0AJ1TW9nJAOg==,type:str]
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:/qnxFHc2RetvLXNSd9Hq2AURV4rGejOniK12r/xDl4Z8OHPKfE8A37sARATxdwSizPCR71ABbD9AFq7XJfSPgWY7X9az0F3hl3mdlO/xPpkwvRdhY2EJnaOdhvxLsxaGeAt8fpmLk6zU2c0ctkmyusmo9EIwheV89vXMsiARNEk=,iv:+YVXVm1rZ8leJpaYio4RxNtrud12srQsFIONe7k6VNA=,tag:oxnBhDu4mIQ8tXH1wtmg/A==,type:str]
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:AdUFrGUFnZ0BZh4HJBR+gZQdJmtdmb/2iZfh8VqVAAAcG25DAffZHJ5t6Cmdvw+Bsy3Y06BRYCoy2xbNR2px44pb0L9jcF4fBNpVMopj1RJfYg==,iv:ugwVltVZ8zc1fK//Q29kBJH+QT+vbDiWLLlVS1iXJC4=,tag:F7Mdl1+Jm+58LFOzMISVGg==,type:str]
  GH_TOKEN: ENC[AES256_GCM,data:oVQ/JGINGu9PT79/TS2kGEOCGaQ8nT6ONHMxm8FdIcRiG0XdjtZ9g5svUGoYQhy7tg==,iv:rYfHIHvZ2CAJJsh5c9yH2tFczkix4g9BxFrBrIuxo7M=,tag:SaR2ZX3rMPw4yNlAwaW+Aw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudFdCT2Rxc3RVcVZNZ2R4
        ZCtMYm5JczdaNlFJSU93Qm0xSnN4VGtvUVRBCjZFZUJtdk9ZOGhGWm9DY2NibWVY
        eHQ3SWhMdzRhNDZWaFRxQi9VTllNa1UKLS0tIHkvN25mNTYvb2MwazcyQTlWdmVi
        LzhjVll6Z0JxR2RaaGJKZnFDVlNhbk0KqNi5oHfN9sa+CIW8sP6NFi34i/1xXaeC
        kiAXDs9m7OYc7PcvtPyHTm36mqV1k7sU8Ua3Gon/ia3ExyoyCiWspg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T13:35:36Z"
  mac: ENC[AES256_GCM,data:doZLm4P73aOFthuI7UTggjg9SnPy/T+cm0xNzMnggtESeY+KpnrROexHjQEJSI5U35kUYIjiS42XTMJCKMJ2rmeLNEms7FMGFZhJJEMT52i1W8WJPR91cEMJrNj5QZs7zY4S4q27Yj19Bn+myWadvsEEeCHSMW14QkkBXbI+0iY=,iv:eHVSHU6b06cVKahkzaK+WI0ui3VUu8cXLCA6PhNdOwA=,tag:AQTigaV5S7pwqMUdKDjVkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
