apiVersion: v1
kind: Secret
metadata:
  name: steam
type: Opaque
stringData:
  USER_PASSWORD: ENC[AES256_GCM,data:Cxi4iWAT,iv:KSNrxs30yv5RNW7Eu5XcXmMZZo6bQcCtJUulifvU3eA=,tag:kg68Jed1MaKFevWqNNRNqw==,type:str]
  SUNSHINE_USER: ENC[AES256_GCM,data:Rpi6VA==,iv:Ywr/DIOCBERUvKKbTk0GzMxJGmvoulrhYOxnW8niopU=,tag:SmDa6itF82U2KkOUFlSudA==,type:str]
  SUNSHINE_PASS: ENC[AES256_GCM,data:8e2vyQ==,iv:9kyl11jSljKuApQc1r1pBtGrZOArnONjm1RRPv4Z5ZI=,tag:ErMamO4uzIpJNJQYlocycQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVVRFVDdNemJ3cW04bkpN
        Y0NDdVR1K21Kc2t0TTk1ajd2SXRTM3NHTEVzClYwRkZRbG9VRmh2ZDFYc3Z5Mi9J
        aEV3ZGlVdmVLeGxDd0xOdWVxLzd3TUUKLS0tIGNYd3p1bjBENmRMbnFvTlpiTUpu
        MEZHYjl5Tm8yWFlYdjd6QjlabTJrbFkKrTGn4AeiGDppA9eBpImr0pORi2Ao+Fr/
        j8krKnX+R+B2t9C9LzlpAlkj/aCgAvTDrlKi/gaWaxbcacvhVpNOqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T12:46:40Z"
  mac: ENC[AES256_GCM,data:IhYEZRHTQUhoo1o1w3mnUNfCDhds7hvx+Sv3yJ5MJMgkhZ7KfUGfYBas2mHNnsudCuLhXF3vfJ/AaYG94A+kBqsW/ex4FWNvRXJsYkP4yBQa3JPt0cOksSXl2Lkm03fBolwh/bNRjjO/4dIlqAX5IA014KVAtpPExICrSjdscBc=,iv:AvcHDN7EWMqj1ecOhHEZXn0aQaWGgehVgOWFOGeb79A=,tag:+jgGTmYzcZDF4FJCOtY12g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
