apiVersion: v1
kind: Secret
metadata:
  name: steam
type: Opaque
stringData:
  USER_PASSWORD: ENC[AES256_GCM,data:8Necxc0Z,iv:5S9g45DJdDsXvW09g0n0NKSbRYs77PxoUzzBve7nnPI=,tag:8KZB6dzQZh47FpIQ2ktuwQ==,type:str]
  SUNSHINE_USER: ENC[AES256_GCM,data:bPY39Q==,iv:qR7dKBUKIn4j+u3Qfo27/s4FNI4o+c8fKnYQNFmI8kU=,tag:anVWY8n923cJnRBQWbbXQg==,type:str]
  SUNSHINE_PASS: ENC[AES256_GCM,data:zO+bRQ==,iv:LM2XY7ZLlktggApDZOEC5wVScBdQb0L3BF8FQiYE5z8=,tag:EuNK7FSKm8ByP5Kwal2mFw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Mm9WUFlzWklJcmdES0ZN
        emlscWNuWHdSekVNMkNxMU5Cd0VRMlZBZ21NCnhDbG95a0p6cUUyc1NUK1FGN2ty
        UHc0c0hXc3BFWlJyN3dUT0NzSmZ5QzgKLS0tIDBqbE1RWnN0MGJOS3NCRFNqUjRN
        M2N4YXFtdmtRbk9aYk5QY1ltYlY2cGcKVTNgY7ArlpvL9iUIcPr95KjnfCfggO6l
        yRdoZdotRPRVagIy4D84GZzG1bhUih+yRzFi22/Jq17fSSNLeIf6xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T13:42:47Z"
  mac: ENC[AES256_GCM,data:QesCQkYn3MPtzfwHa3DCGi8xqrN1W/fNegxdnau7ge4ZERDWs1yRC6CaaL5ohkd3eapk3/NkUS2ZhfLOpM32/HaiNZoVrG4SgGzC6KY6HqHk/cLKACzH6/Z4eqPPEJDrRuxXw2zGCkLS7uefkC0WxQWT+kMG+lLTF3UyueGVPGI=,iv:cjh/meSxMYHqCVSx+eIh1H4HX8JMoLOKe1yf8XA5Lng=,tag:DaabmEHAFcxxQJV3tWuTaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
