apiVersion: v1
kind: Secret
metadata:
  name: steam
type: Opaque
stringData:
  USER_PASSWORD: ENC[AES256_GCM,data:Fr8j6c0q,iv:O/3aJo1oQ36w/8eCP5zKqPoUnT74RAogqv6szZIzl0M=,tag:I2X9DDKUq9fZpadhd5SCMQ==,type:str]
  SUNSHINE_USER: ENC[AES256_GCM,data:zFcBtw==,iv:baU8P0mnKAII9AN6o3DYuBAFs4HU9Pf8nZFaeLWsTjU=,tag:YmbTvHxejMQ4YMC1mz2YgA==,type:str]
  SUNSHINE_PASS: ENC[AES256_GCM,data:QJFsbQ==,iv:YJhKYSKq8Qbu97PJN1qhhqQhXOZKWlYow45QsE2b3Bc=,tag:ttHMEyvhrzA0NuWjmg0hTQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbVZBTXhuRjJwalVZUUow
        b3JGZzU5Wjc4WHlOQzdYU0FqMTR6Ly9NQlQwCkVuQ2NIVm5MN0NReXYrcnI2T2Mw
        cVFTWVM3bVdPOFRBUUNTZmtJUjROTE0KLS0tIDVqL3Z1NTd4ZlhlY2cvUzA2NDQ4
        OHJDYzRrUE5UelJyV3BoWWI1L3NnNWcKZcLg5dGY+zSsncicLYnEz4C11J54xNoi
        pNe3vmQ2SKXZZoNw+QIalc0xtKcERnFs22JU3DxCfq8vQ2hZjTnC4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T13:45:56Z"
  mac: ENC[AES256_GCM,data:pF4P+Sg3+3vFWiTOSr4Cnwg5tCpDGA8O57vDVNbupzFUzH/c7e3stCNHIOK01tGzYuQYnL834zRzvTK5iBleFIEZUUl6yTrHQqNhPF3o5l+3dViCwoYKdVYKuOP5kWyjIfo1cunKpT5BCCb6mv4fjJg4/gq7AWPN6XLyZ+86r60=,iv:LtEblt5fsX5Asm53qGoJ1JjZ66a7ukWxlXSLM5IOJOc=,tag:9YkYWmISNsKgq7KN3YRQ0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
