apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
stringData:
  GARAGE_RPC_SECRET: ""
  GARAGE_ADMIN_TOKEN: ""
  GARAGE_METRICS_TOKEN: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR1EzcFZpYWtxbmhPd2dX
        Y044ODVkOEVNTE1kd1p3VFl0WW1LTjhLbmxrCnpPaERnVnovREMwSklDNDdSR3Fi
        dnhKdm8vWlhEck8wbEFuK2crNWNHa3cKLS0tIFlLdEtDRWJVQ3E5N1k4Mmxqelc0
        WklqQ3QvWkZJeHZUd21qRXJQZGVXMkEKRSB57soqvPHeWvTh7LMoK7JfB2p67CVj
        v9kk1XHFE+DG5B+QEw+wUsi+9LI/ZgzI1viUwISd8wgbqos1JWJLZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T11:30:49Z"
  mac: ENC[AES256_GCM,data:bu3d8MmzKFxl8mt3pUjit2zFqaV5qdAlR+UBJpmRVGXfOJKN//ebeU6Uz7a63OFOvnht0WVjVEtjOv3RBh1MmGx/7frbbZy5Tjr2BpczcMqcdv1WlVagLg134K9xMCHshxszqkZXt6VCwyEHGeATYwqdGszwwH2NXH7Yu7NXSIs=,iv:zBPqyF4bAJOFHlIXhs1jt+Lmr2jMUN2RbntaeHov1NI=,tag:cib36CCORGDOEmI5cjZuhw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
