apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
stringData:
  GARAGE_RPC_SECRET: ""
  GARAGE_ADMIN_TOKEN: ""
  GARAGE_METRICS_TOKEN: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZjJDdUNQdUtqYW55bFpI
        VVNDREl4KzlXVy9kYkdPelJ4clZrQUM3OFZFCjhHYlpnTFJweU5qZUlGa0g5TmJ6
        UG0xUkNEQ0ZEWUJhYy9PM1A4TDVRUmMKLS0tIFhKZ04yamxhcmNZSm5YWjhacE1u
        MHNsTFozOUw2RkQ5Tks5NnphSGI0OXMKztwYinNYaHmT8cF2EqxjlzCTeWovRTk1
        ZyBlY/T0A6X8Q3KpRB1u8h9qRRQoj0/JtVxpExKAnQeEIBE82jhkQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T11:33:04Z"
  mac: ENC[AES256_GCM,data:QXiBFh9JZqEeQd5r28isV/aEYxrA6zWeO37G+xR1G2EQJMGGzRDPlThB3lrTHmzAnzuV22h/BHY5bcRLoUQwd6YVqe6f9RsDYWWxj9pWKWbFmTmtlGxK/BMVdDpZ9HEG101/RACFKv7khjoTZTPpS+bBUbMniY2oMST9c44h2UM=,iv:IUzz0z75R8nB1EdPt4FKU4pkex2dB7aX9IfELWh9PNM=,tag:2zmJgpDixvkI6BmO+S8VuA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
