apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  GARAGE_RPC_SECRET: ""
  GARAGE_ADMIN_TOKEN: ""
  GARAGE_METRICS_TOKEN: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdGgyZ2NmRkRQQlpuUXln
        QlcwcTYwNVh1anBhRGJacWRPcE9ncndEZjAwCjZMdkc4cHA1VnBxdmc4K1NLaEtw
        RlgwdmRrVjNhTHowdWtFUzlWakFkNmMKLS0tIHREZG1IbG1vb1V4MFM2Q3M2V1JH
        WU5UOTlRQ015Y3oyVEpZeDJBRStsNW8KYZOoCYEkmiaC5yc4aMnPcxwY7h0i9Y5s
        orukPwcxD1W1+nCbtkyeqh6L0SyUDnOdTM60XToNTvD2kav9TsU15A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T19:41:47Z"
  mac: ENC[AES256_GCM,data:ZO7/mLBGUQYZ4H6nv/F9L2xv6gEMyJSfAJEGoD4NSpaobep2aWWHXAD8ve2f5uWZQHdV03eS+rV9BgGj/ri6I9FR6DTQ3KOPj+hqjZI7hfu6PTJO9ePSMHkbxGoz/1dRnzXdr66GlUNfMAbOBsE6gSWHJBjXpfHr/8WvdnnluLc=,iv:sGOSneyFEIsdzh4xzZVxD9U+hbUyKTvaASigq+vXdK4=,tag:oAMXANgReF+wusKOemkSew==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
