apiVersion: v1
kind: Secret
metadata:
  name: shlink-web
stringData:
  SHLINK_SERVER_API_KEY: ENC[AES256_GCM,data:7U3GarOpl4A2eAuwuY73x9QY5kYR7wnAT14HL3DwwcCaSCAm,iv:1f/BwaGNXLfsWWY6ce4B2VedQnEfvpTesjiE4HZUb1o=,tag:uBsWyqI1f4XNkKw65bArPA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa0NQMitaQjcvN0Mvbjl6
        UEZSTUZvQy9YU2RYcnNaQW56SmNOZ05QNERnClJWVWZKR3QxV01MRkppZjVEYTJI
        cnZkdFBxbU1DNFZlZ2RFSlRkYWNDY0kKLS0tIHJJWTFRMTZDVVo3MUpMYWUvY3Rq
        TU5vdlZCRkcyYkNpWHlLMnZEZmlUazgKMJJW8jQghAlalyLg2B5U75hmL+1WzcHm
        z9I9L9Q+ciW8e28z8oG+WexQifxZdIJ2/4LUq98Zg49WHTDPVi6ZiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T11:11:12Z"
  mac: ENC[AES256_GCM,data:Y+lyUGxfMCIV4HPPLqUkeHG0YoHKnJC7P9ZKoknKwetDSoJag6hbsV1HOBarRJ2U9LpCYQ9R4EEhMwmcMRJNFERjZ3i1LR+Tm0I/6M4pkZuCneICPEEhYH3WRb0rq3uvRgLpfPMTv1hD74xRtHFJ9G0hXCJZFfBbpg5MU4SMjZQ=,iv:lmYbPL6c26movCJfdieBNfOCMEvHcJU/jV9OMlnxNl4=,tag:sML5ebnvrpziWjl5Mpxs1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
