apiVersion: v1
kind: Secret
metadata:
  name: shlink-web
stringData:
  SHLINK_SERVER_API_KEY: ""
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWDRlQzlQVGV4Ynlkdysv
        TWNTMDdEQ0JlNkpBUmZ2cFcza1g3c0xoMWhZClovT3NaL2ViUWZsVWZ2dDZTeSsr
        azgvWTlsOVp6U1gwcTZUaFd0SUY2dWMKLS0tIEFZY3MwSHNkWGEzVmVRdzZRR2hF
        OEs2VWs3ZzNhbWh4UlNpa3NybjFrUzQKjHeM7Y189oyLo3JD0N4t2RdsRJNw+z8v
        HsVsxYNdKiaaypagAS3j7OxFGN1xiyU5IlOES7t8XChQmUeDdLvdDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T11:50:38Z"
  mac: ENC[AES256_GCM,data:UQVCBbMpmiBkUPrOcSSkOvuwDB1kghgrMqI7ywMBP/lr+kJDiuXmWz0921qfTEXDGZpMiRqjwaPlnWsoqjuolA1pF2OPP5v7MwCBRh/fNmzSnfs0q/TRjWnn54pijll5pctl9t57HQ4KUDKO3NvlzU1gVPdKQQr2cr+1u4/CJ2o=,iv:dysUEJJEMtS0CjBs5s5i/ZSJvmLMuf6rLA3Um0HkLN8=,tag:IYzU87B+g7l9OrB01skocQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
