apiVersion: v1
kind: Secret
metadata:
  name: shlink-web
stringData:
  SHLINK_SERVER_API_KEY: ENC[AES256_GCM,data:bOGcilCCSCYvY80K2krv74YCL8G/+evv/nFSjEKF4afU1MxC,iv:JCy4w8VBOXz2Kxgf/dsq0OivMWBb8Y6jTfph5PPtEJk=,tag:UuWVH9pjUtvKAEbGn5pDhw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOHBsbDA3K1hFekJHMzJy
        RlVhaHJwZ2dzaTh5cWxZVzhpbjFzeU1TTUQ4CkRUVVRQbENVdU1YQ3FKZVhSZktl
        ajJZMkVOZXFDM2taWDV6RG1DQU94SWMKLS0tIEFXbnBiVDNoWU8yaGNmRTZJeTVO
        aFZzSFpyUlBoZTlxOXdwWFpiQUVkQ0EKnhOThUeZC7lntKKroQEgRQiHgmOSQIZB
        JgsSlsImksgdDbRil4SZjJmYtnP2+o5koV1nahfLB6ahSPemlXSGIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T00:15:09Z"
  mac: ENC[AES256_GCM,data:U2btNqZ5+3TKQs4cvSDKesWePW2GhGmOodEzVqyqiY+Dum85QfAkdy0EcLtNAZezioI1X3ORaX+x5AH3vKGKeH5GcPKFEuC/g0fyZbEP8hNZ6JAm1BZpH5ymbbWYYCPHKXl6hwrl/G1wUpjVLVQLf2wx3m6gz84oiG7roRYMqpw=,iv:pSdN1CVbJ4LbLKLlpAgkCV4UsmDOqcIQmbn1KCKNpTQ=,tag:O1mj8b/kjuUWRjNsRhTm6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
