---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tdarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      tdarr:
        containers:
          tdarr:
            image:
              repository: ghcr.io/haveagitgat/tdarr
              tag: 2.58.02@sha256:20a5656c4af4854e1877046294f77113f949d27e35940a9a65f231423d063207
            env:
              TZ: "${TIMEZONE}"
              PGID: 0
              PUID: 0
              internalNode: false
            resources:
              requests:
                cpu: 10m
                memory: 300Mi
              limits:
                memory: 600Mi
    # defaultPodOptions:
    #   nodeSelector:
    #     kubernetes.io/hostname: "k3s-2"
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        # rules:
        #   - backendRefs:
        #       - identifier: *app
        #         port: *port
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "{{ title .Release.Namespace }}"
          gethomepage.dev/name: "{{ title .Release.Name }}"
          gethomepage.dev/icon: "{{ .Release.Name }}"
          gethomepage.dev/description: "Transcoder"
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/server
      transcode:
        type: nfs
        server: ${SECRET_NFS_SVC}
        path: /media/temp
        globalMounts:
          - path: /temp
      movies:
        type: nfs
        server: ${SECRET_NFS_SVC}
        path: /media/movies
        # globalMounts:
        #   - path: /media/movies
      tv:
        type: nfs
        server: ${SECRET_NFS_SVC}
        path: /media/tv
        # globalMounts:
        #   - path: /media/tv
      music:
        type: nfs
        server: ${SECRET_NFS_SVC}
        path: /media/music
        # globalMounts:
        #   - path: /media/music
