apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  openid-config-client-id: ENC[AES256_GCM,data:lbVEVASOCvGR2dxVdXBI1EgQI+MwKi4wmEEVufeEcqACoHcXULlbdg==,iv:leKnPficbhQoibEW+ZWcduFJLTp3w9hYAjooW6Dv/kU=,tag:sxtg5bFWOhL3gEZG7PQsrQ==,type:str]
  openid-config-client-secret: ENC[AES256_GCM,data:wCjg1k2KbHg5agD/1OYNekcdNyyhtZ9P/DrG6tSVIVhI9wIxcvpeOgXGupynhIgA03mh4lcNk+b4h3N2z/mTC6vNaAqYRjJjRC0v3moUXJE21R/xjPAbp/7RSFjPquGAPd4RrSPe6NV+P6j+W5NqHCjU2EbpJn8QQOCpVM5dXEo=,iv:6lYgDGAebu9ORvKK6UPzklsEQSHPRuvwL3FDJ6r/AOI=,tag:04c0ufeTXBSa8L8hKRBcyA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNmFJSmMxbHdzS2lpeFVJ
        QVp4cEJwY3ZscXBtNXMrRWs5SDdwMXlYWFNFCnZJR3dtWVVpU3M1VUJjaHZzakNw
        Umo1aEM0ZUI4UWozZVFITUxKTmRiYjAKLS0tIGpFdUVFT0c2aWRiWlZaQlJLdlhD
        WnRPYUdFOGE4NWsxVGJnc1JvU0RZNTQKFEp+Zb/yvFTGMtLBGakgHTfBp4knLPFx
        HiscfWAZCym0bT6VJq/jGZoJfkgGJt8N/Kgc+lY9LBzcb8lhX+oY5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T16:22:43Z"
  mac: ENC[AES256_GCM,data:4v0MCJSqddV9O504REAUyEUFoK/B3wfWFsQW7jEUt3Ki4i9KU4lEbPcdhLLgLYscxOOxlDiTEpbfWYrQ0D2jhkcnHFK0yCaZBwLItscN2AHzB9gZFmu5Thj/CompKav7JnTMNTZI472qVNCdE9YOTR7n2n+hh+UntpRoznRObug=,iv:AP/RjGc7RLeD6fRx05j+k0yNvVj+XHzs1Ha4F1MF7Y8=,tag:eKaqxM4hHz1PjwMe5rOXqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
