apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  openid-config-client-id: ENC[AES256_GCM,data:/+WVIBdn9bCbrNAd1mkMLxI+OnFnlXmsP8yHlcwYr8Pl6s/HhyhCJg==,iv:bxA3py7Qf7STZmVsA5astRyb2n0cREIN55U5wtm6ucQ=,tag:4qSqrBdrSZjb/aUswIuI6w==,type:str]
  openid-config-client-secret: ENC[AES256_GCM,data:JhWpnWMJV8YnBc/IAPRQOEMROkYtdyVZfpBlZt1MFkQ5+oAfcFd5lhMxXCzFef9oBjL7tyRm/nhIc/h9roK5/sP7I+0LAU83pX3uAEKh6I/acq7hSScy18Gmzu4o/Hcy/NcOHVLznFbskrNDoLsqn5hbQ/r7HjLSqLV3bURghNg=,iv:8pdOV8Amsozwot7WHLrFTvssiZDUoXqZdQ1ot58qDNE=,tag:VmMu0TBlvcHc2fyKXfs9pw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bDNkZklUenJPdnB5S2Mw
        eXNGSFNvZFEyL3JjTVhyRHpSbWEwUWZUc1hvCkVwM0FQdlFOQ0YxZFl2RTk4cTd3
        U2JMbmZuMmw1SDRDVFZQWXJwKysxeUUKLS0tIDlRcm1zN1p5cmtrcHZCRElzUmpN
        c1V2UU9CVVM3OWVLQlJrNklSdGUyQVEKTmK3WrIDh4rPyDtzbCy78pn/5vVgJLdR
        91xtbs6bnfiAjAyUiY5Md5ZZxS6up8MmHlEgsuloI21zwTmlDa65zQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T17:24:47Z"
  mac: ENC[AES256_GCM,data:FSX4+UtDdkHp758AigezSbdMeYD0JbEhLyzc10SFWPYpZ/i4RV+jKLtc03reGdM2C6/RN89mUThwj8lY1sKQCflYK2hrXG8pRv0sTVKAoCSJK7N6pCnApJcvMNprlMYvRTVok46Zik4VjTN7RtrDsKjM5TxN4CgX9Fb34dzhW+o=,iv:FolEbcm1wqa+lA0COJ/qdLrJlabPb+6Vuj+8jQtozcI=,tag:u08Vn/t+954WmQNhiEm1fQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
