apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  openid-config-client-id: ENC[AES256_GCM,data:2WKwvxvSGR8S1EbkpK+gvN+4sewMiWQXZv9GC1mhc5NXpMsAnjYBXg==,iv:7XmTvfgMAErIUfAM/cel0AnYc1rm4r5wFBlvJuhVK3Q=,tag:b9se04L9Nt/lnb7KGA7XQQ==,type:str]
  openid-config-client-secret: ENC[AES256_GCM,data:j9ENUDJ6S3gSgD9Vbf4p+yGFlPIMnvAFrgB6Nzcrg9pmUHODQKjKaaE0OCq8mQX/33pfudYk6L3f06DACEgUmsfYPJ5GsGKd3h7cxCb6QKfPQQFW8xTv4K6oEGonZ/Uy5ZhN4AT+1GEkdHXXaHHYJt4OzElgGxHox9PInuCFLvo=,iv:BhD4wQAhAbAkih2aRk8FO2FLgvoryVJnddJl6y2Xubs=,tag:2QWHjhiT8QZqwq+eCSnkgw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOTJoMUpMV2o3eXRwdWdY
        Wmo2UlRaVlh6ZHk1TEQ5eGgwVnQvTjZYQmhzCjFCMHNaWTlSOGdjck4vdTVFc0hq
        ZmczTWxseUpIaGZuMEJWRVlVSWNjV1UKLS0tIFB3Q0lVcWI2QjVDSEVSVllEbitG
        RWtPR1dST0hLd2FEWkJqdEJMc0lFT0kKHCVythMGv5OZ6JxB0J0upGAZFuGZ40hk
        vjwhRFwURRzz/Qox+bDS2XdbO1+h424DcswUYhM24gCIQQKrg3EzSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T03:17:30Z"
  mac: ENC[AES256_GCM,data:n7TLp6bXx3M+j+QcjySXgc6sexh6EZeoDsBfnvpJXKs6pKuojMNjsGh1PXOguqIfyrxoJSQBvoN4+p5NaS5JU1F3sc28vK5sg5QPe02F9/H6ObyoxLFBkdD2s8U+YYfxcYqqM9LEecn9aVlREZLtSGSINUemrfe3uUdRoB2CDR0=,iv:UxoDxxwZTbE3s5881VC6uPz18grbfdkyKWlO2gGF5fI=,tag:vR2HHUhDCVMal0T4iShSsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
