apiVersion: v1
kind: Pod
metadata:
  name: zfs-shell
spec:
  nodeName: k8s-0
  hostIPC: true
  hostNetwork: true
  hostPID: true
  containers:
    - name: shell
      image: debian
      command: ["sleep", "infinity"]
      securityContext:
        privileged: true
