apiVersion: v1
kind: Secret
metadata:
  name: shlink
stringData:
  DB_NAME: ENC[AES256_GCM,data:FL3QDkea,iv:KkTk+20ZE15Eoc/PGadHsDtOnThi1AHVlUTGhkvXWvU=,tag:xXOZqBBrOu+GFMFoOQ+naw==,type:str]
  DB_HOST: ENC[AES256_GCM,data:j/Ki2JMavJ1oZfYCDnFd7Ugn5PTBeFhMNQ3vWWwOHDrUYlPwdkg=,iv:XyNbiID0N4uSdylQwqXEfa/hYeY5lPycLqWzMMkNbV8=,tag:tRrNY+umYcCRMH8DkE/Izw==,type:str]
  DB_PORT: ENC[AES256_GCM,data:lQvR6g==,iv:9oWiCrkd+A7KfEK8+E6ngGuKkFXIb3QGMBUi1n/Epq4=,tag:Sk7+nH5eEEOOTeOimPdhow==,type:str]
  DB_USER: ENC[AES256_GCM,data:w2ebbyP4WJA=,iv:zGIoR9fEmUAK0ajL/lmIVzDZW6IZ99MwlOSsApKj/8c=,tag:8dKh/K7Ai/RUmfYS+0CBIA==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:OwEs99R6I9RAaok=,iv:3awRH9dpnrMsZkZcrCvDkkD8/iZk8uX3N1+MTKstGcY=,tag:fEtQZCa6BT58SANkFtfrtQ==,type:str]
  GEOLITE_LICENSE_KEY: ""
  #ENC[AES256_GCM,data:l0tMId01+oyqG2pcwnw=,iv:p9Tfv7E2AeRBqn98avxATI1Yai597ml4+ILlEa7mPw8=,tag:W+2yLqZrW9q/rFXweABueQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:XhA6v63C,iv:u9MvIKMsjYgyS8f8MlUdYrnlFqJ5EMdJkTidiShkjd4=,tag:2wqDvX7X24XsZOVWhIGcHg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:QHReZOZTboxhAmKNoLnyoehHnijDFEIJoBTRB0hkt7Bzwho6UTc=,iv:LKOOmlZt27QCd2NOsBBihCAh6rkXt1LObmlBbxv1rQ0=,tag:qqP0QHarpxrCBw3adwFPxQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:uhHVrrITICM=,iv:gVioDhRmJKoOI9x6zYah3LtSN9g4yPnAOUfbrx7nJIc=,tag:tIdKWR/8c3s4hjYTNEdR5g==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:TrILT3pTpUCoajY=,iv:l6pL0rYifeBIfqrVKvsNZ4zUB7MMFrn4HmLK/AISCFA=,tag:AidnsGyX3sTxHVJklm05dQ==,type:str]
  INIT_POSTGRES_PORT: ENC[AES256_GCM,data:BZtNyQ==,iv:sbN/4VripVHixFSBrHB/z/oyc/ZnWniSyEhoLnxdYuY=,tag:8fZNR5Wc7UAxD8K13vEjgA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:GonafUmPBSPaljw=,iv:8RWNdAnPiVWK3+LtTwAyOnisRCMGSRSpUnfcgVKC2pM=,tag:X70bjOmqpQb7d1nrDX6Ywg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdGtmbmpiamlwWlBlTXZ2
        Y0QweTNPRU1lOSt5cjdXcjBVbHRpZGk0dkN3Cks3a1lFZ0hhalRlbGxHNTBhd3Ns
        c0FXdEJTUXZ0NmwwQzAwa1U3cVgzZW8KLS0tIHl0NzJRUEF5VXE2cEZWSDB6cHdq
        elB6bzFYaE8wMkVwTitybUNzYVJDdkkKs7ZDw3rVuKiQ3OLT9G8CEzwbO6EacY8w
        wH+q9Ci0PGQdlSyRZS+zDB27ahCTdQ+srpNg/jXvukaQ+g/ne6iKTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T15:49:04Z"
  mac: ENC[AES256_GCM,data:fruiWLsiy5betMDcte2F7ekX9jWmTHUpCEYTTWavtDMt5rCS+aEBB7w48uabHCmJnid8qXfv+lR+TWcT5Lo90eeCVYfykr3aNsarBTqaP3e+6AOcz5CcBU99zfH7N9yYHKUlHFPRYtWY9k/bwuKLNRa/lSZtELbRwXIE3/ZjeMg=,iv:LaLT4KDgjtPaV8ET5ugiGJ2PSnh+kLeHkmnrb+BmK5g=,tag:NaXcOYO2//YTjr616BY6Bg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
