apiVersion: v1
kind: Secret
metadata:
  name: shlink
stringData:
  DB_NAME: ENC[AES256_GCM,data:Crj/AwJF,iv:BPfBapnbpSuoPqWk69brS6s4ByovvQEExzggoHKHo+w=,tag:fstG/r9882wLgIGd9fjodw==,type:str]
  DB_HOST: ENC[AES256_GCM,data:qAqgbhmZW6LEIfqNhlBoYLnHnLUK0+pqQF2qsxoudn8S7yzfDb8=,iv:iqGmYqq/3MoeyBtmAl3702bYlNBQYvKiPTzDuxgHDgs=,tag:zosBCf/tXjsv/0CyxYoY/w==,type:str]
  DB_PORT: ENC[AES256_GCM,data:VporUA==,iv:+GpicNqDTdNKKcrn0mGkKkZGNdnFtPQ/r9CetjKfBhA=,tag:Ptpi2aW+UNDgQX6cYYU09g==,type:str]
  DB_USER: ENC[AES256_GCM,data:NML6Z/TQSZ4=,iv:NE6s82L1LqWKqkM7YKFFbnIgt929+OxyYvkdJSIxh8s=,tag:HA6B+Q51iy5eSoiBbxsnPA==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:pE3PojOgcSGTj0o=,iv:4zbx61QFoNhKvQC/PDUK6truizSJwxg6lzn96pixL3I=,tag:OKpvMFdMqGUNQkG8JCVtSg==,type:str]
  GEOLITE_LICENSE_KEY: ""
  #ENC[AES256_GCM,data:DUEDFWi7dUv0nHqK4Ds=,iv:x+8athJKWc1yjLakzopml4n8L4kQY6SrMlju2YBV3BA=,tag:QCUQBjwOJOvS1j3Tx+crYg==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:kRUKnScN,iv:VgNuIKha22hwpPBZ4EVSxMtOITtGElaPRLzvuvozAoU=,tag:NFCKFoK5CYBeK3bZpESFHQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Fqn68/lDBLPjp+ryhJEPU7ygKIIhEEmDGixIFxN8JSprJ5tcJQQ=,iv:fzxCn0LYuJvyHjl1h29rMh+ucQux8ObKR+5TfCyblRA=,tag:iLXcl7zYFGQoIiczY9NDXg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:t0ix3boANug=,iv:gkjEhrcrvuN5FxgCLtt24ajCnm5ynIntqWWTAWCc/c4=,tag:wFTm0f6U2DeZDS1dk9ExKQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:HE1QBQJ7kg68GoA=,iv:pzwAq+TozPziieTE/sHDJRCoPgszFuHoELWNMnJ0a5U=,tag:ZMx0TmhmxV2FcGlCz+fiqg==,type:str]
  INIT_POSTGRES_PORT: ENC[AES256_GCM,data:P08y0A==,iv:wWaf1ef7ES575sWStWvNO1a61nmS49YbwCIFOVFolGE=,tag:uPfwMPUFwqysEkiC0zqiJw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:BdC4mQTsZojW+Ok=,iv:DU3TL/Vkb02yxJKP4sMZCyj47JXaUbHF1uay9B40BBg=,tag:LWa9itOT8ALaf8XaiM4/sA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYTJkNHNVeEtqeWkzblE0
        OEMzMkJiTVpPZ0VWZng1RDJTLzlDL1NnQWdNCkpjRkE1aHhvMU5VWXljcXNkQ0Y0
        c25Ra0hqYVM4U1lZdWtuYVlENHpMbG8KLS0tIDVMSWVZN0h5ck53ZEdESkw0WnRu
        SXR2amtvOXk5N1dIbGZieUpPYTFLU28K7Kuq5avkQvpkGOqv8hMrCQ3XMEiRu8q/
        KaihWdWNUkl6G6mEtuRdRyDHvTkyixEfdnA66PO1yzh2xNVWbHrSIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T02:28:06Z"
  mac: ENC[AES256_GCM,data:4r1OXfd+TLHL5cvgYUrUqm7A/RiXyLE3+/NpdWU73X2v2VNQ35crWJcqNOKlsZ4tHrw9CKlpKJLNB2ec9lT0I72XzmHtAOaKxaiV4DFcgMDz6KJEk9TbkIeSayAsZzFsF5E5BwSKWTZtOhO0nuin84ZwU84nWctKaVbrQohnfi8=,iv:DbqV6UaVabM3w9CTn0E9B5gm1uA1kxwFRXH6XGUKjt8=,tag:hwaagpJZCaZ9YsRgGdEWcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
