apiVersion: v1
kind: Secret
metadata:
  name: shlink
stringData:
  DB_NAME: ENC[AES256_GCM,data:QIBfI6XP,iv:UYFgMQqSJlHW4fjNY9VpM3w070Ma9kZuKa8IZnb/YKg=,tag:5frSG0EfDtnX/Pz6p1p91g==,type:str]
  DB_HOST: ENC[AES256_GCM,data:RBdZFuPHOJgJfk4wSGzTf8QWuohxuxNfsBCXADaLWJOV63347yY=,iv:ps8JyPWs0qzmftQkK5IZURjCBblKjwn5IcB05AXNDkA=,tag:qz8Zs7qwPb0ms0MeimroKA==,type:str]
  DB_PORT: ENC[AES256_GCM,data:Z8cmOQ==,iv:D+L+cjZyNDQ6GocD9MBte8EXPi+P4S9ngv5scHbfT9c=,tag:BG1Q3mBWj500cPrQcxHJXg==,type:str]
  DB_USER: ENC[AES256_GCM,data:s9Rj/JAyPLM=,iv:534SONoi7/3Wuf4K9+TnXMmYQXsPgH0I8ZUbwqyz0m8=,tag:n3qwrUWU7j5KHRG5lzMKRw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:3BEcFELOZFmvayw=,iv:BMljp85pA2kCeUU4iDQ+fKorHr8ZDqxlCLPhLIRfSh8=,tag:8ZmjGmhzt+J8GY82kjTYbg==,type:str]
  GEOLITE_LICENSE_KEY: ""
  #ENC[AES256_GCM,data:AyUmArhTDFo+lhj8guI=,iv:rQndPsV4LJZ6S1JNualmfhAz3wesRdgHSyhgVotClds=,tag:J9s049LjJ7JkqDXiaULaQw==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:FiSoER+s,iv:6rvtBut9dTVu3m5L7VTvi3o/sI59xPeDbr8nFImOXBU=,tag:5xfCENaLu5DaIbpQ+4JgLw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:7tnuob5OJW5parJxWB2Kks7CtpI41at3sMd+IuhlkFwbpF+x6Nw=,iv:656+/eUjSLyaHOj63KrENcNxieSFtnMbDkHg7xRLa2U=,tag:9JPyq49v53+2y7224aNqCA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:GiTPoPqAYho=,iv:Hxcsg+vlkVjLdVZWSXXharHmdgigZwdlGUSNzaqT358=,tag:tjWvQF9s4AL7/qoIo0vUrg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Ave/v3hWpSjwefo=,iv:088alC5r8vK14xV3UGyHRO8rc5XRonM5MPIFZAaaq+4=,tag:xowJil5enRCSOrXqqxk1eQ==,type:str]
  INIT_POSTGRES_PORT: ENC[AES256_GCM,data:YTMsJg==,iv:7778x9SjUXuZXo+FOPSUeTnrzvA+N2pTiQGOEWWQft0=,tag:RvHS+CFoJp/nmPWGS28HQg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:lhbQ6NXBSyvOohA=,iv:VkRzX2Lk01aOW9CY2vjJNzuoawmokTQ5GVynLBYtYHQ=,tag:q4oSEn1itq8nOPZTMtlxeg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ODFIUlZqYmRTR1lBYXN2
        ZXEydzl2aHpaU3h3Vi9sSjcwUWN6R0ZQdVhBCkVTdU5CRzVVREpIeU1ZQUl1R0hp
        ODBuK0dQMlFMSE04dTJka2VOb2cwZG8KLS0tIFpYZm9LMlpsajRCaXk0YjlSMkN1
        cDErdE1wK1dVblNvUTc5QjczeHpTb3MKvrwi1mr1TLcf5lOdosnsj5+TIITpsuRg
        MWbiAX20z+ok0aqChltaD6F7WBSkaMfOuVMyXCPTT1/vZ84YXGpdpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T16:55:23Z"
  mac: ENC[AES256_GCM,data:83Tc8sMWRU+ahCSfssBKWZqmZur5ppFaCwpVDu0DTbSMxp4L0AFFbaEf/GrjZ9NcLQVNuT+VTkrmhJoAPb+QuwrWxT7nwKFdhudczM06pTa/U0yh2c5Shblb5aPQ7YRFAW9HqNKUDY/AfF6hGYmz6mQS4MC7tkE6/s55zuyfPAs=,iv:OpQTwp4ZfO7d9nH2rYLghQLE2wHMrfRAFGyGp2Sdz8c=,tag:KUaEoLUHQrwoAIEpsb7wxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
