apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:hoQxWnP0,iv:FP2OhXXlPGPpyLS0aqHoQWiKxbZIr/h9scP5JitkFlc=,tag:zYITTe/UKQCfafWRlgNR5g==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:W9AzkwMzprKu69IXS7xo+DgFOrvCk1YGNh7s/OLxWrg=,iv:+qv3LEnLfXZp5LP6/z5YbhPON9DZtYgY7vtd1dQkK9I=,tag:tkWvGns0bVeRQO1qXbyUUA==,type:str]
  openid-config-url: ENC[AES256_GCM,data:XgLYchagjLk8zWo8IGlLLWc6B7qQ2R5l2fo9IKx08bmGC7gAXgaUHlLq6aiAnEPetLk29XfcFpciwDBCUjqAb8+qllXbFSsoj8getqI=,iv:3xV/DnRLRmBkraAt585M2wN7ck25fLt0CctFnL5hVMk=,tag:TkZkE1O85wwGSac4ibVHaA==,type:str]
  openid-config-client-id: ENC[AES256_GCM,data:dBuPI3DPZ5b2GdEw/Dupcate1oPNQoZ1VbJjtZiR3/5eeFC8BumdwA==,iv:8Y2g18Xk3JS+Ja4k1WAbH7i841r8Azqt8rdFIV3GWz4=,tag:xHL6fyU2zgK0TxIBhsu8vA==,type:str]
  openid-config-client-secret: ENC[AES256_GCM,data:SE+8zGk/5i30g2sN/HFBoi5CPSbKotp7CMnMJbDmMd7KmO5mvHAHhFPd+fY9MMnB58p8ULoue7AxwY1DPLhc5x9XoINT0uT/iS9VRW+OaxaI2z0XoB1A+cEr5ExvKVyWP7HVnGH71zeaRdRwjVIwwkuaiu+aY/LZLINmuf/7I00=,iv:JbUC4Pta4VQGOzbi865Fnu54/HKlOPmarGvdyOTV+5Y=,tag:xox37OdJjmJhEIwCKuhoNg==,type:str]
  openid-config-scopes: ENC[AES256_GCM,data:+UDj9w5hSbc8rEZKhxZMrFAmpmLHhAswXjc=,iv:NYikRE9MBb63Fmjmec1pkagT4ZKnzFjITrO0PD41m3Q=,tag:KiyRT1KnphftXJykBh+7XQ==,type:str]
  openid-config-callback-uri: ""
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyelUxQkVDLy9HMDdCRzRJ
        ZUV5aXJ6a1FKSS9BRzZZOTY0WHhGZU15SzJzCnlZUDByN1FPMFFRVWRxZVltQmQx
        VW9TSEIraks3Qm5yMnhmdnVqNGVRK1UKLS0tIFdUbWY2eExhRkhtVWFab1R4OUxU
        SCttOTJLb3RYUEhnUjJnb0dhODJLbjAK+wIsIRyN2ARwi0zZjzKVnuGlpGiMBc2O
        q0nVtLmR+Vtr/hI/kElLjPq4dEiofkj3/DZnlhlCUM7oV07oi5bKTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T16:01:36Z"
  mac: ENC[AES256_GCM,data:R2TOdcvD22bXHbe/02kITlAkSmbqQecBDBzzUMcX8ClHPaWucY8vsM4Mdj079GF83s2oUPaPZj0Kvq16KHLYs7zL2cozJb4MagcRekdBblAQf1WTbqPrd5uwAZc1Yb6BfNrsL0KpeYlQIakwRRz+WsT0RkjQx5MWAJMt/le85ps=,iv:W7Yvlu55blxyJrWxYb04B92snPqkC5nFvlXmRChQqn0=,tag:H0uVDNiAPMvR4HONDZD7cA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
