apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:G2Aqx1Ze,iv:K5Z4qvxglYstONPRl/u2iegdrnBcDwOXgROtkUADx8Q=,tag:UJsfewg6QLpMfsBnHN9+Ug==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:cV47GoXLyF+Ig00etS3KlRxc/KaFdUyapMg4uIR1U/E=,iv:LVjJKK+Chjkp0ecVasZwhc/0LxX3aXgDD/5wObbsTMY=,tag:6hBspZXpFm3zyXCE045Mng==,type:str]
  openid-config-url: ENC[AES256_GCM,data:Cth8KZtnXfGp6fbJ0rRPi0oEWQkqRf3UFRbZefe83THz4NwJzVZ1zm44UHiPvcjX666rRO0vvXY76cMmmCKXclmOVLuLfkxPpaTWOvY=,iv:dpWz4eknl9RIKy2y+fWIltCJDAWVAWyNl2KiaigOReo=,tag:MNHrlp9BF/rxIW4RXURoIQ==,type:str]
  openid-config-client-id: ENC[AES256_GCM,data:SqSFdz9cGC1g8X2AuSyDvtwhJzxtmiQgacR/j6VLaQhGsoLlIv/0Og==,iv:/+g8d8AyzureX1LZUqUZNjKkLvWNOeWuWJxJMAOXWx8=,tag:+6woEKiXawOLAjTnNP0L6w==,type:str]
  openid-config-client-secret: ENC[AES256_GCM,data:4+lXpuS8O6oGIqLSp7LlXAtlWe+i2q+AMWd/h50Dc5EkkcoWeDXxMS0+Ez2Nf0mYLFffUBhYWdaAn8oayw70VyepKyRNLtbrzMDv0CRk0lRo1fdhlSdq0zx62vxJRnLU3qvizh24B3TwkM2gxackKE7BGXY0TpZdNsKGe74lIkY=,iv:ldwoXum/QwBVuErzrxfhU+DDROtrARf3nYedoq/w38A=,tag:6Mv+l/zY7D2vdJoiI/V2IQ==,type:str]
  openid-config-scopes: ENC[AES256_GCM,data:E9Nlp7K/2qpUfRaIGUS5GxdVGRtVCcE3YX8=,iv:IGS4of8ROO35N/FRs75vKZOEy0vDYUD39v1bLUIguFA=,tag:ZNvw26dAj9f6K26q382U7A==,type:str]
  openid-config-callback-uri: ""
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcWE2U3lmMmJOTC9SMHgy
        eVZ1d25Ld1V1eExiL2x2MVhHeUVXVVFrMkRJCnJWcUZvOEc1NndleCtyZG9xSVRE
        TjBmYzduOThINm0zSFhjRW9lc2gzc2cKLS0tIEpNNFA1aEM4SFJUdWpQUDFjSElL
        YUxZdHZwaTd6ZURrOGNpTy9ybFl5Z00KU3A/MqeHu3fJqaLSYQ8BcrwHp7vtwmkl
        zfpxifFse28mLm4Rjjuj3dnAw7JwogL7y6dYv+3djzcmbLtZo4vHhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:38:19Z"
  mac: ENC[AES256_GCM,data:Hf8FzXFJboXiDtKduFQIWlAueL7WYsYHoX9kK8nX2UOO5cBl6w+M9bJlG0foKd7Lrac4q0NOlVLI/qbSuBB+WqDqglue7CMSQcqlQGnqsDhT23v+5luioFqAErqvP9uBGU35AsK5XL1SdqGTn9nF7zikGJFBEl2zKSs50vmB6Wc=,iv:D8320RYQeUsdo+vE00CjzFXQ0UHIIbxez94W5VL4kow=,tag:dVCp4Wi6eNBTVFXI89MT2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
