apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:g8NT4y/P,iv:0bgYG7AyhtGa7qZtVuzdI4W8zITzVoG/Bz+DxkV9H54=,tag:jxW20NkM4gP0w7KK7xIFnA==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:UdeXf99TiHmp32uWpQTaHyS6wtrXVNE/EgEsAUoCgIo=,iv:iq3mCxsBlSZ3X+bkcPsvVvS5ZcaUsL05n6OWdzfz+D0=,tag:2E20mZB7YCBmvJsNOKWVMw==,type:str]
  #ENC[AES256_GCM,data:uhqiqPE6hH/DRGSwG+J0hHkV78KTjQ==,iv:ygTq4Nwl7ZBNmxsmVbpitxoEBLZkORYAuPPaM99Wb3g=,tag:/FFgCe5DsJxwLErTwU1UeQ==,type:comment]
  #ENC[AES256_GCM,data:PPT9ucRrNHPoWQKDIOSEBW7Np3b3pJIGHWrWBg==,iv:lE9mrVztD7PZovLHJrMyQ0xy289Bb/s2izRxnA72gUU=,tag:RNMZkQXz03LGWfHPETNtCg==,type:comment]
  #ENC[AES256_GCM,data:faChSbtpN0AV54fFnO+d40ChjR9eiGnMzPTrE7gYVTQ=,iv:fa8/9bRSPLik6elIpyTd5r11l+txCN4VwLtRkkhjczM=,tag:F1dLM9OAt32+nu1AKsGR1g==,type:comment]
  #ENC[AES256_GCM,data:UbUMzaOsCJdmoZHUMxISKBAgEfHPm2mHs1gTIWMuTD8gmTov0YvVBaSvdRjW85i+goU8,iv:OfV0BdxeBtaBx36bp6vW0XPttDSi1PsxAaOZqDiI7WI=,tag:An51LITQhHMHKyu4TbsDYw==,type:comment]
  #ENC[AES256_GCM,data:65rbdEE8iDGc1rViWRx2zv2XhbK/QEx09cS4H0Gvpg==,iv:TZSK6bVulmmzL0J1EquTn9pWBAib1hu0Be70Ld/0HzE=,tag:3a5FOAlp6EBw9Mi3l8ZgTQ==,type:comment]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eUpKWHlLSGZmM0FmMTYw
        UU5nYzREUWpEV0Q3Ym0vcStnUEJCMVErTkZBCk8ySlhJNkRxUndBU1NJMnRjY0M4
        Q1VsckMzYjlULzUrSGd3TjllVUhYekEKLS0tIGt3OFZ6U093MVVmbnZJYUtrb3Nm
        WjRFU0NLZXgxdjYvd25CQVdreDRGWVEKUItHQsy9Lhgr6dpMmruzVOIw98prZ8aU
        4PqfEXwMYv18hlS0A0FjqCJXuXHf282HYE4bqVKH3WYsbaKpAQCgRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T04:58:57Z"
  mac: ENC[AES256_GCM,data:x+A5Qwug1vlDzN0RGFomkjUZhCgk0frG8U1jQfHiS0UOV++zzkJQFw2fMal3FsJ3t9hb2Mg2Aq07++ncdoni4to1a3iu9ez9QtM6QAAZvUbQl2bQA2QHq1srRY5wwdrrQUsxRGJG1Vdf3Jn3kqqsqGIiBAkfJh/MedlWkKnn4oU=,iv:Mc2uAWwDcTXaCScnOFTIe1zMZJO4Tl8xTdNgpcHuLsM=,tag:ZZHiQrBsAsq+0UMcSuhKug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
