apiVersion: v1
kind: Secret
metadata:
  name: n8n
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:5QwIc3DrnxuGlqA37My+La64SFx+ga0Y9X4ct8LnfDb8V4RlQRM5bpfsPU1ZLHYNoRMv+JO8I/LEjle9,iv:sTq9RlYtkoBYfMVyCTdsX8fTyijadJqHiIt/xIpJ7ts=,tag:qLAvPnNDFDYDoeQi6xuvPw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eW1CNG9nSWIyNEtiWWRw
        WS8zYXRiM0hFTG5IaVZybTl3WlVGZmlIZTNnCi9nWnV0ZFUzVUlyVnB6OHYzbjR2
        K1Bwc1oxaUNwTlZ2U1BIanZzVFljQzQKLS0tIFFaeXVwQkVYM2V2bXNNMkI2dStt
        TjV1bFdmNTRJSmNaT21iYVF6V25PSjAK0WbYHXoWzNmn1VZgCuDuOklqbvK8AaQf
        wYc3TGJQOQTZQxX5+ffRUMfPRUdk3EvuG1pCtzq4IVX3gzuhKetJcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T17:36:34Z"
  mac: ENC[AES256_GCM,data:mkP7F3LqiBC4oBQz1dzFSf0HiH49DH92TKxPplE0zj4I4jZqIws8aUrIZxs4koMyVGmAehbv4ovL4qtlmZuWyY3UX7JFacvvqkXu4FWdIthnDN3WWS6SrvJzVCgnzXa32+dHy/ta3v9ly7VLFgmIbQG1/ya0SDr0wTsPrx0yFJg=,iv:eTQlGPvoWzPbOJOpgbHw5WJ8iPOB3pArA5K/uiWJGco=,tag:8rH2/1yl4fXrJiN8aN9BNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
