apiVersion: v1
kind: Secret
metadata:
  name: n8n
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:FPsJPyjN0pEv09Vcqgw9NzuPBE4h5WuvgpQgkrFH/Q0hifluAdMZKgahIPfMZYbqjneXY5LR4SyTL/QE,iv:u03Qe12tx51DdIfaQfZ2yM8Bq64nOMQI33qE9Y5H+jY=,tag:T/qtxwxROQJw172L+YgO1w==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLKzR1US9WZ1RlaXJBSW1s
        aG1PcXN6TnNVVTJEaTZiL29kakNDUmRUSW40CndnTzJTN20yTTA4YisyQ1Vmcm9J
        c1ppUTladXdma0U3enF5Y0U1MFJZUkUKLS0tIEVTU2x0bVg1MjNpK21EcW0veDhp
        amh4M3o5RDZKKzl2bnl0NjRmTDZHdkUK0/zore1nUIj2PPXJNEGpFsTUG1VUtNfI
        seVEfedHi87eFUuzAsVcDbNI72OeSUltVF4trBWXgZcli3FDcx8mwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-15T14:57:29Z"
  mac: ENC[AES256_GCM,data:FqFzzeTbVZPPcJtV9oGnLh7TdwX7E14EoftfKUZMYNe0xrabvTiIubG2vO/evrph2VOpuN2rDG5B66/+yi5dbTKS42Zn7n7h5Gzbt1nPhPPzXe6HhjNlSoPVnOy7VK5e4fA4iKKjgZPIpHtXdG9ZWPqcv6GkUVWriI5t+Y10WTI=,iv:mm3DN8Z5XELS+5E8/xlKeO1D+TE5IdxjrbQzvaZH27k=,tag:h5c+p64MO+1bTNpcpfqM5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
