apiVersion: v1
kind: Secret
metadata:
  name: n8n
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:PGbXJivtftuUD85oy7BDqdgtimYfcX3eH9BSb9OOcqSkIyF2Oz6vSdfkBADZsgOyifKa5+aHMGn45CkX,iv:m8wFiO4TMwKoTfhLB51tE5bLcYUFO1WeX21n8yotBU4=,tag:BhUzmu7KIPNf1DD/cOHYFA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ2VPY1RKdVFkdXAwNHI2
        a1pnL0dzUndQdUo1UC96Vm51K0Z3Uyt0VVZZCk5VbER5b0QwRlhXdlhUN29UQ1FR
        VEVBVmRPSlp3aW9SN28xeGdSN1dtakkKLS0tIDZpOGJLbERKOXdLTTFydk5iaFBI
        eFc0MURWRlV3RGt1K3VXL2ZiRW9tZWMK3o/7tDAGPQE3x528qUfpsN9aKUkbHcFg
        48cny6uHftrPaalOv9c/vrpdvEZ82F0AeXwk/lqEO0zdAknyovUkUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T10:42:17Z"
  mac: ENC[AES256_GCM,data:2f79OtReiaBMNGWFgbyRa/gjVRjr2UIv+a45es6XqF29aIPKLYz1kD6gXR5Q44FQ8kWzdDGydHAPfbfNDuZGByRj1rtKmWsEeuHz6Moy/ntLu08OjMrFhDbRhelkffWeMxE/JgZhMJo+UnisgitQFqMjjXIC1RR5Zqpf+DHae2U=,iv:juZOTlDXe5q6aSIArEiNukr41wvLYQR1L3HIJ0Szyj0=,tag:mqbT5ckzV3KKCdsThNu2Kw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
