---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - targetPath: githubConfigSecret.github_app_id
      kind: Secret
      name: actions-runner-controller-auth-secrets
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    - targetPath: githubConfigSecret.github_app_installation_id
      kind: Secret
      name: actions-runner-controller-auth-secrets
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
    - targetPath: githubConfigSecret.github_app_private_key
      kind: Secret
      name: actions-runner-controller-auth-secrets
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
  values:
    nameOverride: gha-runner-scale-set
    runnerScaleSetName: gha-runner-scale-set
    githubConfigUrl: https://github.com/fiqrimasngot/AMD-Global
    minRunners: 1
    maxRunners: 5
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.330.0@sha256:ee54ad8776606f29434f159196529b7b9c83c0cb9195c1ff5a7817e7e570dcfe
            command: ["/home/runner/run.sh"]
    controllerServiceAccount:
      name: gha-runner-scale-set-controller
      namespace: devops
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-web-app
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - targetPath: githubConfigSecret.github_app_id
      kind: Secret
      name: actions-runner-controller-auth-secrets
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    - targetPath: githubConfigSecret.github_app_installation_id
      kind: Secret
      name: actions-runner-controller-auth-secrets
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
    - targetPath: githubConfigSecret.github_app_private_key
      kind: Secret
      name: actions-runner-controller-auth-secrets
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
  values:
    runnerScaleSetName: gha-web-app
    githubConfigUrl: https://github.com/fiqrimasngot/school-scheduler
    minRunners: 1
    maxRunners: 5
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.330.0@sha256:ee54ad8776606f29434f159196529b7b9c83c0cb9195c1ff5a7817e7e570dcfe
            command: ["/home/runner/run.sh"]

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-kube
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - targetPath: githubConfigSecret.github_app_id
      kind: Secret
      name: actions-runner-controller-auth-secrets
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    - targetPath: githubConfigSecret.github_app_installation_id
      kind: Secret
      name: actions-runner-controller-auth-secrets
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
    - targetPath: githubConfigSecret.github_app_private_key
      kind: Secret
      name: actions-runner-controller-auth-secrets
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
  values:
    runnerScaleSetName: gha-kube
    githubConfigUrl: https://github.com/fiqrimasngot/kube
    minRunners: 1
    maxRunners: 10
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.330.0@sha256:ee54ad8776606f29434f159196529b7b9c83c0cb9195c1ff5a7817e7e570dcfe
            command: ["/home/runner/run.sh"]
