apiVersion: v1
kind: Secret
metadata:
  name: open-webui
stringData:
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:FBFEoOuIihzhsHLgGrmhKurC58WSI/ZomSRStE4LgLjaobjMELxqLA==,iv:03fz7Ol3nJ5WeRe8wWSWRhxlkLHPyqsy7MsUiaVthEg=,tag:fh5zXkUnScXT1COe3NjD2w==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:L7J5ZtFsnFe3F9GHGrIV7cgALmmKiqLZJXQBTmlkZx8a1pL0p1KU6ToEh6zCJWgcJENi6mK8Dg48QmE59rA11X+p79I2AEg2d6+OF3F6VGHC5IC/Csz5XJN8AAngzfk2i+650UAgzAvcFAJWsfH33N+qd8+cr0N8q+YCr7crv+M=,iv:zUTgSRizKhkGtUd9QT/860zZJsrzNo5PVzr1X2z/qPs=,tag:gBeVmHDCGlpCe/YwhQjB4g==,type:str]
  OPENID_PROVIDER_URL: ENC[AES256_GCM,data:oz//StdOAPl06GvzHcpHMAxhHfP5zE+mnJXBEPKoLCoEI9PT2y7VeO2W1yjuECuXwmYvM4RFVnnJHmAS3WZ7krgNNc8RIBgC/3TEpo2P1vfxDA==,iv:UiRJ1Fvtpp+lUiWpt9BTyQAp9AHLg9+OqwwKjSbohig=,tag:x8JLXK4EUBsPsrSCNuTBDA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YlVZT2tDcHZCM0Z2cWdG
        Z29oU3A2WjhIUytwUXVENGxKelh5WjArdVdjCmc0TWNYYTE1ODVCUlpVMDM1bC9L
        YnBqUXN1OTFCNXhSSjV3UHdvMWNFQTgKLS0tIEI2ZzdQOEhMaWx6THhYUnRLL0Zo
        STNWWW45RWpBcGhFLy90TVVLMWlWcGMKjxodrNnz9B+OOCXw0jBMHOlTDjSX5Z+p
        vs2XcP5NE/ClcdvXKaiOsziZj0bp//inMSh/y2HynqO7UhW9ROZW3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T10:41:46Z"
  mac: ENC[AES256_GCM,data:s82E494lh20U9Q8f3bjKg1N+3KVxX6KojM1CYP7F9rLHcdtLEwb6yRNMdnZbaeuROCxJAi883p3YI2sC8PSy4jWFweYl+zvNxKl2hBfZyRI591gMttt8HmSBaz9nlTuMQKpOi/uQXzZgE9gOZJg68Pb4AajSvMrspO/nZCVijTA=,iv:DIAAOdVs1AsYbQP5k9V7fGldxcNfYaPyxxcTLhoirEY=,tag:wDyPGTgi877R2wK3T/iP8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
