apiVersion: v1
kind: Secret
metadata:
  name: open-webui
stringData:
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:qs115ptuiWi0dXA4R7w9OWQHsgu71pk4A3LO7NsqL1tU20uG6jcf6w==,iv:+fN4amVW7aYwYRbrGEKn074k7sT2Ym8VMy6tN9OX9BU=,tag:z4DGzPHFDeq2y4B171mn0A==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:R3fTDn7lg90+bN0l6NE4XRZl8xFGRHyAP2N2W7ONoYqMkvPtKTNZxed2/TLUWgkL+CmFYQ6uWu5IolQEyGjZ6kzFWoi/El3cVy3Dn859sTZQFPjYsm5a/3QSaZE43s8Tw+xwoOZT7/bs5nNbIsasQ5R3pML3/FGFxY2Sgov4YHE=,iv:M+wd4J75u1i/HpAg/LFdzJrVPT0hHWeAs7/vuQnX63E=,tag:tKKLjHLGKZnmljXttW9Ozg==,type:str]
  OPENID_PROVIDER_URL: ENC[AES256_GCM,data:3zHIEtrWv4makjbM8sXlTmhK6rzkDRk2sNitJBEzjHyW4Lq/2lrI7jPw7txlO+qkAQ9OuBaPEE81EZxJHkVKjsWIF8sPnvLU7s2jvvNxRKE3ng==,iv:nL9/QUyf9NO5Hr9V9jYxeQe4LpiQuBnFP/mGQBkMafA=,tag:hXoa+VIbHEYSPJapRmAiNw==,type:str]
  OPENID_REDIRECT_URI: ENC[AES256_GCM,data:2qD20qRjSwVyuuO/THJES6Q0hEDb938EqFMBUqxavAACep78C3qA4Iyvm7wWZTf/iw==,iv:C7u+CVy36KSYbZdfGcmuuuFN8yXCGHOIjUQzk1sk2SA=,tag:cH6p8WGEO8g53QKDs/JN7g==,type:str]
  DATABASE_HOST: ENC[AES256_GCM,data:JubwBehwxFXCBH/ZYobOUYrVuczpz/tE6/PHiMFRSqs5sLtAA2o=,iv:xZpQwhEb1sDjAPZ8XF3xRxHzcJBt05m7BgJ0xR81yCI=,tag:WBy/eG9Rp0fdMvLWX699vA==,type:str]
  DATABASE_NAME: ENC[AES256_GCM,data:jsFqZrGTU0+jPQ==,iv:6XVF+e5XqkeuGTpyt5r+hgoqAGntHE0iqMRMaZ9c1mY=,tag:BS8La2X0khlsclGv4BzUEA==,type:str]
  DATABASE_PASSWORD: ENC[AES256_GCM,data:9/sb8Dwge9SJWxY=,iv:QR90pHFdQrSwFP6KAwdN9tdb9qI/noPYS/xw4XJpQA8=,tag:qF2PxJBE8cmNMOkX+U+hOg==,type:str]
  DATABASE_USER: ENC[AES256_GCM,data:1iF55FMxKLo=,iv:OTsme/o1VVgWqAzX7E0hyFRCxjhl/Zkz7v/Zew/h9Dw=,tag:qLPwvJR6q8GC+W3JYaTp5w==,type:str]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:P6FvPWf2q7Vv8x6Wq65hkfQ7MdFrz+LAgI6C3xZzmaoNv9XkGHFVUNdDrefJwxE+NNY2xZZXpytYBTTVf7v0Ueu253g3cGHPrLfvDc9uUInpKrOItFaADtGWjXZSJRAyBEkhyrXBBxiTXx8KzmqbOS0wmU61pizBKdsmc8/40ek=,iv:eqsXnRMafYPvfo01C5983ktbVk/vx+QcPeONY+OT/ec=,tag:25dR0PPbDBVNy6uEKdx0iQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:J8VsV0KfCS/meA==,iv:GykBidITO/EfAF58M7ZthFHLIlyW0N7EyJjrgP4LQfs=,tag:MZMaufMkxa/nt2pnBdkzKA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:0RK+JlqHApdO5YHa2t3g76pgQ04go1AAfGETznlCH5KVzEUB2EI=,iv:h+xb694pyEdvravLbADzYJ2lR/S0EL7ZRtoqsF90Hgg=,tag:m6g9B1zzo85xBjPLHX2wMg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:aACiKRQc/T0=,iv:jzkeNMV363Lrri0M2vqXsP3odzYgxcXa7VWLc31ZJHo=,tag:3FB6mmOEo1ermsIYPz583g==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:gUMpmRRqqxgiYJs=,iv:DCX5SUbdk2RBpgbfJyy4/YpZ+dwcnPIs9jLb5yUP5dU=,tag:KzRAnNpeapHPaDYYwJDEHA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:QGld44NXhDY8uGw=,iv:YY9brtSYMCiptN/yJGBLLsBXhDzxYR29jqJhr/TJGps=,tag:G7GtPvnGFO4KT3NDUXp2zg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:eq942la4Qoo=,iv:ZfM/yIT3oDXVFGQVMih1GobBSRW/o8Lwjzv1yfOUq58=,tag:Fn+tlUO3JQIkIB7kDKd9Ng==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydmN3ZlpzY21Pa1g5UEdT
        bk1JZEJjeS9UVE1qL1pPYndxYVJ4T2JsN1JZCkZaZ0hTN0VoNGZiTXVMNzFrQ0t6
        TWtubXZzdU81aGdDSXRCSVN3MHpvZGsKLS0tIEU0RmdjT0Y0TE1qYSthejZjbllX
        Q2NkTnJLUG1vVXJNWG56MEliWm9KazQK7C4whUx2FvP1kRZu9VA0019zuseMxNNl
        bP2pefrVG7pSvWdf2F+o1yXy9dGYqrz9W3xbflnTE+v/lOhK6I/GNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T06:35:08Z"
  mac: ENC[AES256_GCM,data:SESLyAWKDccRJQT5hwasy0daYkZB3adAmJg2Y0xF/12GKAGk5Et+JzMORlnMayCKPFzLY/oGi8wJd1eFZjPa0Zcqqkha1OH+Ts6qZLQaT+p7L/sZ80q/rK+Yg0lmGnnfxngkjrR0Kk8U9qVAqkdTdBzYr6Kl/HvxDncrwkpIkMw=,iv:QX01FeTUlY5QibGiA2Hsu3yJExuKBjxJmatXZRFtQzo=,tag:b8MQMSoNRzdejfz6P0SMUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
