apiVersion: v1
kind: Secret
metadata:
  name: open-webui
stringData:
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:lrmito2An5OcQmQ+KXRkoRLoA7nNIhw0/gOpcynTVBhPTVxqeoEyhw==,iv:n1k9b3XJlgxfRzXma9rbrQd3/XdKXeEghkQbPRfMRgw=,tag:xidrWPmGDrw9Ry/G/un24w==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:aevah2jDXqY3cb70QAzbo935IYZZIwa/DExvwFfIjipjjw2D1ZzM+++vbhFOvMaewev4/z5wqEhrRPD6cDz+lknUwBSHtWuDbT0V5LMN8KIjBXTf/QwFvZmuE0Zb+G6MkCMPlJlB49ew8w4pbfzKCJSvQoFPaObiDbMa0UflsQk=,iv:grrf9JucOhA/lMgfXAo2npm2klo08YZB8pfiZXevJEQ=,tag:ywinm1uBCd+qbzJCXZ1ZzA==,type:str]
  OPENID_PROVIDER_URL: ENC[AES256_GCM,data:76zkKNIEz0LfBlWlozgdQnk/hwDeafCTBo6A2kNXDPbxAQJVVrFvobX5hyHJcb6AhnrwCWb1ulfbpH+5lLLLXv8OjIGdttW0zAfYfCdwUwikfw==,iv:QxOIgdBDCLg4kwLzW9bdgXKuctmpmDq/Un8RTfdpiAw=,tag:XWERm+7ElnRxnb0ZeP3JsA==,type:str]
  OPENID_REDIRECT_URI: ENC[AES256_GCM,data:cSAT9AV0pSO6ndQCRT5PIiXStYfgHvY+2WPk+xbGW85JdzIF1vXUHqr5j5I/a5oAxA==,iv:EuWE5ePAc/sTKXZRTXJ2Bh8vA6uJHcyAoNDUIlUnjCM=,tag:cfKdUkyAdGDDms1fFjU05w==,type:str]
  DATABASE_HOST: ENC[AES256_GCM,data:5M+TnNATdsKd3j6ftfHfBTXfyaeB0xhZaEz/BoMTEUkd/hcG1EM=,iv:AtfBNjC9RMUwgahWEx52+gspHqchukTp+QKqkCO7u28=,tag:eNcyILcrAro1pn8Ke5uwRA==,type:str]
  DATABASE_NAME: ENC[AES256_GCM,data:cxVEYZQFO1jp1Q==,iv:dTlPAbGRVj25y3f3/YHb10yfCbe/kwmfoLyOnQP6XlU=,tag:2oRn81n6nJCFNr4KWuHniw==,type:str]
  DATABASE_PASSWORD: ENC[AES256_GCM,data:zaLG8st+4YZobtU=,iv:KxwesaiP4njSRljm3OF1L/wmpJVRAfMExPq+z6TXStI=,tag:yUbKJimijPaIiFayCVS3xw==,type:str]
  DATABASE_USER: ENC[AES256_GCM,data:ZV3dlVupLS0=,iv:uXHOSdczMz2o6SZYWHyZ5DAJ+AAAttbmF1pVFWNgUhs=,tag:c6pEC29vLN6gPF1MvmEUsw==,type:str]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:LQgaTNfQjWrsDlYl4oM75h1MWDCSWl6mxKsQiB4Um945coQSw+c4cJyQbdbg0cycIY1x+ew+eHQriciVikEOCcknLVdeeJUwSJAgBxtz+84ssvrDv0Yi6bhK26RWYnf6xTxSahR/Qp61xgZgfBOkl++mgPc2rP1XTbTJBHNz4cg=,iv:xQEc56pkYCuoRWJ5HnH3/KX/Su0U07C60nLVeaLLo30=,tag:3D+fDy03YO2gvlFR+1COzQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:B62kQKtgfbpqmA==,iv:e3l9+mPFxqNeuYMRpYtC3rRi9QKPwR20RdBYsdRDnCI=,tag:OodIr0wFXotAcvO/694ndg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:38PLgT++8qDaxiQwZXDYjwylZzKYkb/RJwKoZDBt/ddDKFxr7Q4=,iv:iXOfR7dt8WRrXIorTLGM40yzRhLJlbNkt+o7ohtpyvw=,tag:6TiqAea/doBBn1cTXcLuJw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:skdlk9Y3f/M=,iv:/b85b+W65HnKe5s5kV6gL1/dAJ/MB0lutTP3sJvzGLY=,tag:gZw5TFv9767wT6zjMkRhpA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:2vE4lvfczov76x4=,iv:21En0bAFzJaRLJeBmHXYqLCgIiNnymmp0C0PsqLoBoQ=,tag:58hqmQHyfXeZV9VuKKRurg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:YF2pZQusnHZ/dxE=,iv:VuWjao6XFPTJ/yIYHRgKgREEs16xnzIw0Bp213cMr/c=,tag:VYPq7LJQNLEOPZpPL5M8fw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:GoNtTdJZwWo=,iv:QykWB0w20+m9mC4GNXCt/fvioGzOX5HKbZOP4QQGJMo=,tag:lMpBm7kfbghb3vMF9+OeQw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRmdBL1pHdnV6VlBFamF3
        cXJXYXlkM0lFbnByOGpSNTB0LzV2RDR3SVRRClFpZDlYQkloTkZIN1JQVVpWUXRV
        cEYzZUtxOW41QWRJSWZCUHhtTWxkZWMKLS0tIDBFWGNxV2dYM0lOdHJFbEtRUncv
        V3pEVk1CSGp2NU5VMCthSTMvV1lZRFEKllxlUc+/ALFMc70HYt9FW1C3YKIuSIJ2
        So6TPBZjIo0q1kdtMrlkLP0Lltxotklkzy1XtRKbPtcKatTdVWRNug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T18:34:12Z"
  mac: ENC[AES256_GCM,data:WvsEHUlOnIdKt+I8UANNFmYEJtTW8YbxyIyjTBa/tgE09StlqCP9BbInsF00Vn0WmaM2G4w4WTcNndxPEyFcv9YpO+TSRHuFpUzRtLiPwLp6hNkTEreRRw+P6B1DVBgsP+JBnsBtz7McG7pmH+9t8lhF/aBekti5q8GE5U5JR94=,iv:/hJYYCz7T8uTRsqWYbj2DAIvjwVw4EPZiXXB+NDLFMA=,tag:/9Mx5ZeVF7BiF1AyUjImGQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
