apiVersion: v1
kind: Secret
metadata:
  name: searxng
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:4S9lFtrglo70hpCLrFVFgQmQnFE+yuOn3Pcbv9L15IY=,iv:Ib7qe4aRhC6iVKfHnk/rAxkDp35WtufCdADHhiEJgdU=,tag:mfiSWt9cFr+d82YYWIJREg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcm1HeGJOd3F6T3MxcnUv
        NzhxOTArOWNWdC82V0d0SjI2OFJMQko5eFEwCk0wUGZyeXJ1TlRZaksySFN0bEgy
        MVhMVnU4dEtTM1lNazR0WEc2YTJkd28KLS0tIHcveFU5cUQvUkpCTHlFdTZiOFRn
        Y3ZEMUExUWJYckpvMUpaN25LaERLRzAKKyntuX4EttJBgEjczyEuT/ajE7p93l/9
        mj67wPjFIui1d8p2Yk3c/14GeuNmiWhu/6qPiom3ll3zMMsbBiq+Ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T12:06:13Z"
  mac: ENC[AES256_GCM,data:uXNBLvzCb7gyCbILlhpq6sz0/XY+OCc44T8uN9DZUsL+afB5cba0OZmG0ScZ+D5kg2HIWve7+c7AbulATb1l0a8jDqNUT5jv+42Te8HmJ34d9RoQnyOkcS34DmNt605ioGTrIKQdmlHnsDqWaHHWGFw5+pA/B/QAzhPh/Gu+LoY=,iv:O2vxbd2MSYrFphD93nF0/fcjAjMZDqVh9J9PuPfwxfs=,tag:cqhYgRJOe18C4+3tKZUXtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
