apiVersion: v1
kind: Secret
metadata:
  name: searxng
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:UaoR5Tz3h6I6s63qgITPJjrIbYgzgw7i0gMvq/KvgnI=,iv:uKbk55JMH0b2pubt7GfERfw7PiZ6PAvnV/VdiUMUrMc=,tag:gMQwqBLHtAHdT4vmhdrxUQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cnZnZ0VlZ29GZGpzMnZ5
        clBJL2lHcmFWVklYVVhTeGQwcW5zK29iTEhNCmVJc3dWYUhpQXJndXVtK1NlVWRY
        cjR5STdHZ1l1NVl4V2ZBcnR5aWZTdFUKLS0tIC92cXNwaWVyOThtK3VrNWN5WTRk
        SXhFT1lqRGZRUTAyTmZzaSs2MnN0dkEKfAgy5IkQdlRPV1zLKhle3HJJDhOnw1bF
        O67IV4CKoevEEyFqkJs0UH9j22PVrH8h+SdmOXB8hiXtTtDzQxLG7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T17:12:02Z"
  mac: ENC[AES256_GCM,data:mTXwLPtG8cAI4zMSEdf77cA1yRDf9G2wlK27nnRCkaDNLragn541+a7Idjc8pdNIzz2ybfrmPR4GyvPeUoKeWn59U4feneqTEVO3kjqA2v+Ot4yOPEXDOcF5FAnfbWhHImaFLz2m0a1CNf8lXi+rl2htyAn8vKhD85jScPn2tdo=,iv:y7ISEc/fyM88mv7Xaz0GmhK6SVizXA6GBrcq+cOQSTo=,tag:oc80zBrX+7y5VXmfgfQsjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
