apiVersion: v1
kind: Secret
metadata:
  name: searxng
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:UoQwQNKg3yhV1WHctIPBhz4xIXCaU1qWazG/pyqe/bM=,iv:3foSmjXsGPtuEAsknwjw6l+QB5GDZqR/pHDakzMx/3s=,tag:UJLaaUpeBB5ygeEeHoeDLw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QXBuTHh1SEtCQkpxbjBG
        RHQvQ1lqUldEcHM4bGlyZElpRGlpc0dGcEU0Clkwd3RmRElXVkZ5L2xIZUFQL1dy
        cGozQWhBdVVoOTNucFlwVHN6Z2xiaVUKLS0tIDdab3VYZEV0YXRWSzRaTEpnYW8y
        ZXlwVDBoOWNPdGljVERXTDhDVVFPQkkKWSGeG9PTyHw9Uut9ftEgeayqbVwkDth/
        IDDGo6IIKSR3xKaSg6GdnpmYTOrSVxELNZOkswnZTKbuu6awp38vKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T17:48:56Z"
  mac: ENC[AES256_GCM,data:KsfIQryXKP0aKpRQ9izktVaDSTOcXdgWpmBaxsN7/I2l2+lnhPDEXyNADhtNgIyyy1I3vGfPNLcW0Xxu8T29Qz1431Nb3BGjlW190xN+9aOzgjIoWrGCtuD5AvxmqSQrBnbgWNhJPmMbPm6zgDzl0nY9IWCxum5qEeHWRwBzR4E=,iv:XB8YhSTQnBqu6lCW8E7fERnCmD3SPX+bg5EFvVMiGxE=,tag:NK6acSITjm7hzlPy3uBmkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
