apiVersion: v1
kind: Secret
metadata:
  name: smtp-relay-secret
type: Opaque
stringData:
  SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:ocvkOqUy48t/tKAs5SWhTO0KXFdVQQ==,iv:xNM6Rv5CRD3H2jwwRGR1JM2AME1Som7YQz5s9cAG+AM=,tag:TZ173+0Te0FgQdpAZpsSfQ==,type:str]
  SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:lyomH/ws7YgV37v1YC4NPmnzYn2oUJz52ldyqS5mxOPieBfgJ+kAJNe/v0BxO1BDeH0=,iv:eo8yrrb1o+EoiMeJGCUeE5g+c2Hq0dU2KXkhy1ys2CI=,tag:s2dQ3LnCOzVjh5P1LjLsXg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMW1kMkV0aXE0R0Y5RTFp
        NkdoUDJBWnRzeFFpR2dGeVdJbGVNV2wrbFdRCktGOVd1UWxGL3NxV25vSmFwRXhy
        SkV5UGlYNHZPTkRsTTJVZ29YOUVnYlUKLS0tIHl2cnlFUi9zYWJlMGhmRWViUjd0
        TEVtWEZEUWI3c1diTGxUQWsyUmxvUlUKQrJjvndaCUG/ZbcEXdUo/k9BoxIwrx9K
        5BhhS/cey8utjfKjo/YMDuR2Osdm9hS4sVUgHL7gvJfuWDe+KJa+7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-16T17:27:59Z"
  mac: ENC[AES256_GCM,data:DLDZBhYVhOBAOVcv/PK4V8yq0DIPB4I24jtReXi/rQgNC0CPVt1M+3M/hMN/xaDVwiwdGvmObdnGOgNPlGn8AGwK+v3Grx0ebwP5qIktJHzAE3Y66vIjJNdc+zT/BWVfNP/+2aQh2d8UW3L2KE5EOEkMfhhJsNEh6uw0u1dwFkk=,iv:S8HQJeAH2oLcZap7owde8utlJuCPxwqw7rvqOXD1Xlk=,tag:A5P7EoENL7aP2hEO/6DH9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
