apiVersion: v1
kind: Secret
metadata:
  name: smtp-relay-secret
type: Opaque
stringData:
  SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:pyQ1LCycwbnwWFICdr7sE+Lrf0KBbA==,iv:O/F8vHh/BuxQQtIjaH6eUGMFb1R1TwYHODvR4o3sc8k=,tag:wMklORZ0QIFg2pnb8EcGYg==,type:str]
  SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:eJ05KdOqBy0u13f2bX6vKHqNG2xZ18/kJ4PUw/zDUp90B5bYXXi+L4YslVtOmkGNQUM=,iv:oEbBjNpR7qCT4nSF4o+6Um4aoCGuAwgA7mSU5gQK8Ys=,tag:u/iLHxLFCHCk3tORIH9YRQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN1pxUmNaZTEyelB0ZVpL
        WU5yUDN0TnplbVBKVzQ0RytHdWtTL05vaDE0ClRtS2o3UnFNUGF4dVR3NkZ0aWRk
        VDJNT0ljUGZvTyswK1ZMdVdpZERJVWMKLS0tIFBzOXNMV3hoMjZsMzkxTUk0TnND
        aWtNamtmcmo2N3hIRnNEWHMzK3Mxd0kKvgQvN+R5zLV3yt+yDj1XgHkj/jh5xRH/
        n19Wti1NUVTAoZMkOLH1M+o1bYpSEP/l5RVysOBEV33ukXXU+MbFWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:27:55Z"
  mac: ENC[AES256_GCM,data:UzoJqf5sTn8w2RPDLXuO5bkSupl2ibBUckZxMAexemYEOtGFDwgZkUt5JqdJoZHBTNtNibVYHRbRsJqCPioNxfM+3pYbWRBkL/wFYXUIbArnl26IxCDnrocYtkif8WVu4AUz7QylccSg91SsAXN1F2T5Rml2r9b2KnlBEfDof+g=,iv:FY5z7iJi92woyAHilMR0zeQr0Z3B5AeG3Vyj8K3LAUU=,tag:gGALP7wuMMA8PH2rP3J7xQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
