apiVersion: v1
kind: Secret
metadata:
  name: smtp-relay-secret
type: Opaque
stringData:
  SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:KPmqY1rstSZCVSDaD9/ZxCcfI4MOXg==,iv:TAMEi5yhAmv/5KDJOjwZh1ebjx8qkjogn/tnTJzZI80=,tag:LPpd9t1iFIu8Xn5wGxHrWQ==,type:str]
  SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:Vj3PWAa3/yl70EU/4kBLHWGftysPOFQw4TGQmdLt++JiCXesigit4+kMPMIyG1EktwM=,iv:SMcCjP8XGDPgm77neRlzDBDhJaN9k9szNlj4shR1ydQ=,tag:Y51uCzQf+yzIG/MLvmKyKA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L2t0bW9uQTdmOVlTaVgz
        QWZDaXdpSlM1bWhYZmRQUkNIOW5NM3pFWUdnCnJnazB3RlhRcjdKNmhsMTNzNHgz
        WW41Rm1VcTI5cE15T3U2a0lOVXVjdE0KLS0tIFBIN29ubVJTbGhNVUNWbVluaVpK
        UkY4RjBUTHFyeTJHREJKNUNGckNqeW8K+WSftbArnAsmyEUVkgTCqso58nWhrsPh
        NHjKEBbuBODpa2tQ8Q9vKWdx1h2TSyrTzQvmL9EfV5hi7LZdHqLguA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T16:46:12Z"
  mac: ENC[AES256_GCM,data:rzV4Xtd9CpMiydQ/mhoT8djbCZr8UZfdhPVPenTv5Zvnk1h5oMe/5Q9YpRKbXLnxsAiGRXj0xTN3R4TWlLZ34BQFPDK2RHzO0ynXjwB3NuMYBp0VK+zXxWsAMmKtX7qDL3Wrj2n+JNBgTJSCmAMxz4F+C7uAdHe/ODlwWUgFMWc=,iv:RuaOBlCjblXnzeOQ//rrV3lu6JwR6QLnqkb69W9CePg=,tag:3N62t8qSo03AJcKWwR9HYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
