---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "4398046511104"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: media
    namespace: media
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: k8s-0-library
    volumeHandle: media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zfs-k8s-0-library
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: doc-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "4398046511104"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: doc
    namespace: default
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: k8s-0-library
    volumeHandle: doc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zfs-k8s-0-library
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "4398046511104"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: photos
    namespace: media
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: k8s-0-library
    volumeHandle: photos
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zfs-k8s-0-library
  volumeMode: Filesystem
