---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Ti
  storageClassName: zfs-k8s-0-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Ti
  storageClassName: zfs-k8s-0-library
