---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  volumeName: media-pv
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 4Ti
  storageClassName: zfs-bigboi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc
spec:
  volumeName: doc-pv
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 4Ti
  storageClassName: zfs-k8s-0-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
spec:
  volumeName: photos-pv
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Ti
  storageClassName: zfs-k8s-0-library
