---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 4Ti
  storageClassName: zfs-k8s-0-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 4Ti
  storageClassName: zfs-k8s-0-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Ti
  storageClassName: zfs-k8s-0-library
