apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:opCdL3GI,iv:Og9sVjGfccHm9rh0DfCFUYX+xxN99UHyFNrZgkzgjDQ=,tag:8SlOW4HoLYg7pE5rp5DxXw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:ifxzOF9TVq4ntU6SxmrLCz8WgLpASvIyxsPy+mndB7c=,iv:nG7vE9sp6KIfG7Bmp6BWw7JJxmtcUHe2flaLiXLoMxw=,tag:TBsJCBnoAdd24d6NA/3CpQ==,type:str]
  #ENC[AES256_GCM,data:IYmtflRgx0VKL1s6bB/wp/SZuYgP1w==,iv:BikxOczvQyHmC4ZfJfuYRN4B96AVrF+hLe63wnyO52Q=,tag:g1U4eUuN8Y/EAEPHknMt2A==,type:comment]
  #ENC[AES256_GCM,data:7rNYrXE1BGpzb1FwN9wqvgjWwxKwXQAgNfhF7A==,iv:+cPXcNgpJb3YwM6XWi41uVZvxS6zRMV49tmFRIMGSFs=,tag:ZHLITIm32rH+ilq6zxU0ig==,type:comment]
  #ENC[AES256_GCM,data:R243js2HmeSHKDxQV4yzETIzkzVhx1oFfiYaJTafcp0=,iv:SvmLlEIdSMT63T/n8DWbQbq7XopjS0fdO82P9n0pD7Y=,tag:++I74lyZ5q0jOE91g4fYdw==,type:comment]
  #ENC[AES256_GCM,data:WMHCbBaXI5JCpvLrsbS0DtL0tSQNoyQHHw+gUlUF6boJfMtZOF+jmTTWm7Bk8UHVCPyZ,iv:xB/5TG6vhTkUoOgXkNsRr3Ln2lpFPTt5lvTgEup8liw=,tag:fNbL9c0DDSxbrXqNT4/D0Q==,type:comment]
  #ENC[AES256_GCM,data:UpgwIgFkOlB0b94d4qwRN63zP+2Ib5Y4ASpaqTVIjA==,iv:Bnbj/ZA2hscURboLhdUPLj/VGmpzRJPkoNYL6Yn7D2c=,tag:Q7c4gKV6++vHLywAA0dlgg==,type:comment]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdklWYmxGVWJ6dUJzUHFZ
        Nk9XY2dMOHFaVkNqRzVWdE14eGtBV0d6alZrClNrN2JXZGRQbmlaRVZkQnFPVTRQ
        aER0Y2lnelN3RkRheXY4Nm9LS09pU1EKLS0tIGlPKzJsOXFkQ2NzNytYZGxpZ1FL
        V1V3ZEx1bm1nekI3SWFhQm5nejNZNlUKxBKZ6FePgpkG1xY86gg+a40gY2b+UrBZ
        wegLc39As1ZLSKa6fvNEUeiAzqsqcb/Dmx8jmq4Nw/Ia18soKKp6NA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T06:28:18Z"
  mac: ENC[AES256_GCM,data:PuPedxw3HZLje/W2iMUle3EQ6ywZa/Pl+PuzcwK8ERQlrQDkUVezUI+GF+iabcvGKJDUpvXG0bpOpa4ZcCWcZWvvninG4DJCeFfzZcrc9Gt+iZc6Pec6il/2zJaE4hCqzQ/57UCyhcB9RBvWjBeOf3O2OdG/OHdHX0oqmxlP84A=,iv:+363L2H0uJNMWiUsT/oZ43QxqSNelCh68U92uxpw6zg=,tag:T7OheHkSSMqbMRiXwIvRBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
