apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:mpuDg+vZ,iv:RmPiWLXE4c3N0DHjgKvuUYt1H7vEMcGnkabmiQzN7u4=,tag:XQiw1JBWaICNePC4NXlWjA==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:DrYqdY3X2wkcZMufeudpdTNgZmQ5n0ut2gQkeWk2rWw=,iv:j/RGyLcWmCdixw41PpHHXC6MO/zdLfsbNP2FMKu3AaQ=,tag:KkrwdPWSslveLVYQHPxwkQ==,type:str]
  #ENC[AES256_GCM,data:V5AtQoBtbFElHa5i4u5uO0Ovt9fgyg==,iv:+hqMOCiOBWKw6NrE+oMIAdI1aVJrqsxk18z3/tXbd7Y=,tag:bSWFl7nlxThSpRDn/Tc4aw==,type:comment]
  #ENC[AES256_GCM,data:myOn9u/I3umi5x7E8hgBPB4BPcJHjq56eloxxQ==,iv:pwEC/lZhHS3rqpJrcuWbMedz1/DSnd5haGxLY/dFtQM=,tag:rpFgYz72pzOMRHCqnZVirw==,type:comment]
  #ENC[AES256_GCM,data:Z9LRPDPYLzJD45NXljgOOCAp7Ztj2Tbv61BLE9hzhhw=,iv:Ar/xRBBY3g4Dg+ZPxQg7PJPN3EFjudgE5ESfEQDFzvU=,tag:PFjLqeYMOx4RW+q/Msh7jQ==,type:comment]
  #ENC[AES256_GCM,data:JYFSKMlCL4eCSen+zFNyK/CL539CXyopPXyhHh5NfS6hJylchMwHOAd/DpK57H6MvYB7,iv:C9lsjjh1O27esW2kpYulLlFa2KtBee40l6oqCb3wQ50=,tag:xb4eLGTgHLZIazZB8xr2nw==,type:comment]
  #ENC[AES256_GCM,data:jSNvOK4fQASsrAfOU6/5Qt0jfMednn6/QZnSWIurlg==,iv:1QK1+ukKnRoPIAy3ttIswSEj6D01Mnc3wPQeO1HfC/4=,tag:7MGnTpXwezqrQSLsK5tFLw==,type:comment]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aWU5R0t5Y1ZqSHMrajk1
        M2V6UEtqdUxjcUdoWVFIblAwV2NoZFE5NUNjCnlkZExxR3Q4NCt1NENFWTYyeFpU
        L0VEdXY5aks4TWROdlJLOXpoNGNXQmcKLS0tIGU4NDFzcURKSTZMaDV6Wjk5Nklo
        NUtEbXhTOThwQW02Y09ZOWZYM1NXeDQKkpFfTffE200xn8jgOMomM7LLVROwgZ2s
        29hRCegYQmL17sq6n1vqlI1XgS1At8+iX25kzGB1t0Qwd+voeb8Ltg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T11:41:22Z"
  mac: ENC[AES256_GCM,data:oD0TThbCilJ1Ywztei6iBl0/WfQB+QzzwVMMBI13Jg08ZLLjtW6uFX65J+T64quguSnCbfOBAM8VtGP+6a1OOLsroE/lcENzV8dowd6Pj3obATbyqcT3ig/vBAQenCI0kFKCxqvgkSklTNbVsiLYoy3yM0GDh3zHp3bNDF1ocTw=,iv:Y7XUxivRBlS+itMOfInxTyzXHEFHhH/d162I6vrq6vk=,tag:q73IXOLK0yJ9vv6YnAF0Iw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
