apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:KYAVOXCz,iv:vMla15fwaxdcxoEI0W6RcyMRNwxzdCGrF1DS3W51lzo=,tag:66T8RNl+B6Gc6Zn07eT7+Q==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:SuCS+HHmAa391wIlSEi5dHMzJWR9ECSe/WYfY/cVATk=,iv:WVCIyul3vMR59JZG7XHkNXHBc2VILbSqMLMBLRH+1OU=,tag:TMQzgjEEiOo11/Fjgqe3zQ==,type:str]
  #ENC[AES256_GCM,data:kNweJUJzBWFxIUxBNDPY5uT+IN6yvg==,iv:MMHYdcbW82hR08i4/T1GIS2mEWPYdJNOa+4YmEDnq9A=,tag:J9JDzB1IG+8cosJ72w6oZA==,type:comment]
  #ENC[AES256_GCM,data:FDhZZgCdfLp4w+KL/g57DaRJ/GcSoq9KGWtcIw==,iv:DB35vtgSiGTNlCzVp0aSd9Kolq/p9iVYGAMH6hSPcdY=,tag:xWMP/hR+i4/7nx9zUpF4dQ==,type:comment]
  #ENC[AES256_GCM,data:IVsz4kJpHQigPAzXt8RrJ3uQzdnxNMv3ZqT44FTuTQQ=,iv:CElr4ktPxBQrYQ0/tmxalRkofgnPdt3L7bNhwc/pCrY=,tag:NFQPaM0jNJk5SbGgGNYtDw==,type:comment]
  #ENC[AES256_GCM,data:npbJ9BPc0hVhA1az9+h3GFBD2k5oFFff3/2cgSBVLw5jYlblVwZaYfW9v7/OUUsEZtoz,iv:2dkxU62klTOrktgHOvsq4V3TYHsg/TmUuzqksTE4p4g=,tag:zQr0S+6kdZy7d+p9VQSnMA==,type:comment]
  #ENC[AES256_GCM,data:/JPLbOKTf902msdA1E+MZNmGbtP5s/N8uz0ZL08QFA==,iv:Hea+v1DjaJ4xACAC5yDne8uo0Q8jqHhfTAdXPEuNa5o=,tag:EUTBdg2rGZ5CFqydl7A7Bg==,type:comment]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MWNUK1gzd2JJSWJVUnFL
        TDc5OGlIcTZGTXJQSGFWd3dkYWRKSUxmYVZvCk5UT3NNSzdXVEU3SWhJc2xIN0dT
        SmVLUHgxY2ZOZTNUbUhUUzk2YmNNdFUKLS0tIEtOcXU2YTh6K0lXQTlEY2w2eFNn
        MjlublhaQVRuV0JCaVloSnFPOXkrUWcKSBAobAGBeQfLITmOouaHAI8OKcdNvK38
        TTZfDgeTmOOwxJj2zG3Ge+rKFWC2VRzMRj8YxEBYdnqbU+O6vMbYIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T11:35:51Z"
  mac: ENC[AES256_GCM,data:ICs+LXCvAYYN8e2tq5rF05mRKP0LoZ7yNwpaY/CtEiJAlvRIZ7bt1jpU1TQH4tGG5kcC/oZn7QMsl+lcJW8f2grFmuEG7mmPTOqGxgN1F0f0atWJ2d9ejpTmAvXOqqehsYPqPcSQTC8PmW3w7BL2RyWgrdO/h6KGZludfLrLc4w=,iv:O3rv2ghbxwtS9H+JlT8GtqWEO0ViE+WcmY9cun1P2VY=,tag:ZPMWxLvNposIaGfG5CLlLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
