apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:uizevANHC09kTJ/k,iv:DEWsd8Y4D8KQeZ/wpV1kRHea2/6WBxzIN9nLOra1EMc=,tag:CGaEk82rQ1hHdVkRQ668vw==,type:str]
  ADMIN_PASS: ENC[AES256_GCM,data:u71DgUvKJ07Q1t7EIgc/pRa8Llz5oO5diX6/kgVH8DU=,iv:A65rIFyrPuIdDh1n82aSf2nTGTXDukyhjXR12kPxEFU=,tag:6+H8KC0uJWCO1NCESDPh4A==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:44E8mcRauZIxsqiHW9c6JhY8AvAD4AvMgTN5KIE39KA=,iv:vImnrIs3/VN3BSYxgTAwWMrPHOO3YHARYkHwMO3XKzI=,tag:v5sxfZOHEBhmwPAJNIEjZw==,type:str]
  S3_ACCESS_KEY: ENC[AES256_GCM,data:2PQQ0TKH9CrfKb5Wgb/jjiGJ28U=,iv:+pMcdObjwg7hWJR7w2mhVjSKvfG2zlaNox2xJgfb1wM=,tag:fnOmKxYORYk+E8fuGAPb8Q==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:0bg28rSUA6LUaw9pK/XhIy0IWlJ6tKRvPtJZ2xC2LwBbZzbsT+oxAg==,iv:xGY4mKyYmUQ1iP8W+ti5Tsh/iX/Z/flMcY9tVwbHOJo=,tag:mPk51J7Xsa3sCLyGfzav8w==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:mra7eGy1gkaoeWoV6UWyJQPzRnhgOA==,iv:r0puXXy/K28NTgDKdy/HKbHR61fxjgDFWamy+w7gbas=,tag:TAJrTlOyGy7d2dFkD8MsbQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:9eO47BRfHSMI7Trdd/VIDK1xORVWFuWRxRYdgKYPpdQVBST4Igzyl0vl6IUGvWtgxk0=,iv:Zn170aa2jVgGdGDcv3qNp79v0Om81XAGleM8m5qEzLw=,tag:p/ZhqVStd81Oi5vdfE76hQ==,type:str]
  TOKEN: ""
  SMTP_HOST: ENC[AES256_GCM,data:UM4jXGrgTMmd6yYSKW4XRMKypp2I5ErSRIZLXAiXJsYawlV3,iv:wVNGKSTNzKBYKOM2sxXM1tHMhKfaBlqAlIFs3qUniSU=,tag:EcHcRaszoCoHn8wGGdCxGQ==,type:str]
  OIDC_CLIENT_ID: ""
  OIDC_CLIENT_SECRET: ""
  #ENC[AES256_GCM,data:vWhN1SEpJ5XgMZ5Ov4k=,iv:U4tw5Zp7RpRB17yx2UyFU55OqkCh0EG2j6kn5//ORXw=,tag:ncaOAnj7QsocGNom21HWfQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:CPILn9San+Vf,iv:ukmxi1k9IHrDpU765qiRXishTO+4gBMrvsDKaURTneM=,tag:vZgCIGJeI+pJdt7+8HBi0g==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:tewivRXDebJD/T+V8ycSMcjviBGGMXq3EpyTSjijuQtgCzRfOQI=,iv:7HKFeQk/bTYNmRrx9eUO8OEOB6dJBA/idqFKEtI1dxk=,tag:qgqyvt4MXPRK7qmffpg/Hw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZKJoBvApb8BP,iv:wXO+I1p0yweZycv6wemGWaD6kjbmeeRoATZ85i4Yfd0=,tag:uM805fGwLsIh9iN+nCAuPg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Pmfaio/0tEGRQb3BSAY0Ilyk1Xc=,iv:qPBJM/EognQaTxfNjLTz7dajIXrPM7wDRjgiun11Lgo=,tag:7sszKFxrPl9361TPIUo0GA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:r9F/wUH7TdDi6bE=,iv:D2q+jq+6WWr5EwJN5kJs6xAQrtVDI6k9LQz2fBiJ7TY=,tag:mZlqrPvO5aYofUpXLuxOOA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WmhnN0pMRCtTeTdaQmNF
        YjF1MUpnRWFLVkNQVUFadDRVdjBMOUQ0RzJZCklwQS9IK3V5NFBuRjJKemdrT2NN
        NHlrcU5yUWtDQVY5SUtVS2dvY2VjNm8KLS0tIEZJeEtRaE5aSE52WVV0TGJleVpp
        ZFBIT24rajBpN1FYNXpNdk5tYVF4bmsKccVDtt0Q+vtLGfo4eS8o+9+vIjwaf0WU
        aUZVfdyYXnEijW9k63v02LpXDe2RW+2mwPoBnC/8LaXN1UYN1qGP7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T05:16:53Z"
  mac: ENC[AES256_GCM,data:ZQsJORcBPy/N1WbxiusB0dQskx8KVlZUaQlfGiq/PEm0rlOMPzi65yvc5XZErE26qUH5YvuDqk1tpkSh3J/mWniG4SqEBW5sx6BiqkcyDTqbdG6gIrkLDJNVGxp9bBpbalQiWKW4Fh51dMv1YKZwMWg8MbvzbifvFMvjHuJqThU=,iv:RxmH+RDaIYpTXz/S/llZTZ0FKkyceI9V9Txn3iAvu+o=,tag:lNp6+Hamil3AZ19GN5lcbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
