apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:v1KqTjDbVnutLfiT,iv:xzrQdY1xAIG/HAVT00hWksZZ0c1f/nnIldlfOVsqwEQ=,tag:k34hV1uD6RpT35tBWjUd3A==,type:str]
  ADMIN_PASS: ENC[AES256_GCM,data:yUiY2x0rXw02HUQhJtomjck2hDvz/g2koOuI/rSKrAk=,iv:OHGsfK4ek1JOWIv7Tu5xJXk3JjkMQUp9hFbdSFzv1jk=,tag:sTybyfl+ifMD07oTqVSiPQ==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:f3vp6EpWhp3PEWCsWeXBucGQw34QWkaOKoAL/3eRRUw=,iv:PXg26p4/EMMYw3rpiieAkdjbR6ifEoGlRyX64JRMbKk=,tag:Are09VZHCI7M2MvExF0nFg==,type:str]
  S3_ACCESS_KEY: ENC[AES256_GCM,data:q4+JuujLAyCd6k614unNRs/ELtU=,iv:tcHRHLJMjisJFBBRTa/FRAaFWwknycF5wHns3zmangQ=,tag:msjQBkYmCVpyioD3AjDSBQ==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:/DQr0aYWDanYtDMW8PPRXLgkb1ezKYMRnZ+og5yW/KZU8BiULg69Fw==,iv:OYEVttYOEgdzJqI6DtC4/cSMe/VCTceLwzhJ5vRQg/0=,tag:SfSw/+YpDxO5ZN6C4M4bag==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:rPgIYQdvik70AiTdUwHRs5tMl3F/sQ==,iv:bBEAaGwbbdEgV1286lurVXs7xY5C1TIATxaxG4VTnhQ=,tag:LFQ7CqIT6IfWKR7zeJBr4Q==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:DU10Ly/4j7ucJnIlb7k3idPpC5X+0P17Sry/teHYPsHY1OCESiG9FKsf8lfPKT6L7Kw=,iv:ig7gMO8NXQzkUy9awWjdlU0k+aJVGpQwD6A9e+3SqoE=,tag:ki3Fas67wt/SsX7RaGyfBw==,type:str]
  TOKEN: ""
  SMTP_HOST: ENC[AES256_GCM,data:D3xfVS1e2KvIOnPM2p5y4MNPhzG2EPo1btTgOeDs8mHEOE0K,iv:zAAvp0NGXRYe33NlsvmX65JyBnHT5900YPURhYrfJAk=,tag:M5MWZLAFVRfiMGKE1Ruaow==,type:str]
  OIDC_CLIENT_ID: ""
  OIDC_CLIENT_SECRET: ""
  #ENC[AES256_GCM,data:/4YGEOqOJPVTnIciFoM=,iv:qFsObSqYJGnwdT8Ik6/1Z+/mKxY+01uAVcOaJ3tWuAE=,tag:fnvL7569PJAjg5+XEcKV6A==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:PKiR9R/TlAfh,iv:Z8CftZRyrr9rRKDKaA4jNrW3fJTqPFnEgwB7BZVFT4g=,tag:XxBlwtpaTJY9zBm40TDXQg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:nKeIQ2o1rj8a3W1biJGhmTjFY9CAzOj6xJ7tF+vclWReIPyFX+s=,iv:+DMyvCEgoEz31P04KjqhMtZdPpYCM6iHJuk2xPPVlXo=,tag:NddPymC9eb0y2iwGWNu3ow==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:YBwqNjz2q6A=,iv:B/yHuDRmakgDIp64hHDwW0YBudeaWSqe1rFONX2oUjk=,tag:xRmlIEGS6DIjAiG81BqnYg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:W7CnOqtoKUwKslc=,iv:MLRSSond9lR4S6SnMU9UeGDDDYC3m8XI8bPHwBmNOBM=,tag:z+XSG3upOZYbjoptK93hCg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:An71XdTBSmDAOTA=,iv:8Ze0uC1RetnvHH833biGy5BolZD0HXEdmiFwMaNos7E=,tag:+noL67aIKSsNkYIuUWvawg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdGxpcGFqdzNVWHJhVnh5
        QkpuUnhjVUNJbnEzSFRubGZRb0JyTVBKWVJNCkJESHlVNG1sVEo1VGhJbU5nSVpn
        ZW1kSTdPaEdGL280WWE2MkdzN2dLSTQKLS0tIGtEUko0aE9kR3hkMDZYZ2ZDT3Jt
        bzZNOWZFcGFRdTFtZVFabFAxWnBEaVEKW3sEu56Y0AnPAXe9cA/flkjuHjJUpgLP
        U+MmY8JNhAMwV4W/+gaeW31nOGe+l+umfR+zJyu8DRHW8HUUz+2BIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T12:28:24Z"
  mac: ENC[AES256_GCM,data:YBTTj3X5uMB8DNeDceHHQ3dl3EMtosvKGoKFuxyztBAwySdQefdt3Vpm1pyqs4MWJvC450Kms8Gy7z/C15x32yCHOUi55oZ6bAj8hFnDQMN2aJaWna4weHbS/SMlJek2G9zJtYXFXzcMfDbgXdC/+YbV7KfRRddbutd4GnHSE8g=,iv:t9ARk10NW4n5efY9bG3ZbvqpC+SDnxwPpF4rxP02iMU=,tag:l08YmEfW9awX0t9Y/kSI5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
