apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:1QeFgEzGdLLPkEB6,iv:r3qk+3UeYULdLD0HXGwQYHr9xe8GFHxSf3LstuXjeB0=,tag:BT6ZBf9uBK5vYUEwzmmmnA==,type:str]
  ADMIN_PASS: ENC[AES256_GCM,data:Mlu4cbzbeTcm3Hum4t9KGpu6j4XOa/CHFwubRLBLoHE=,iv:fsL6QzEMhAg5Noz19bdUd1zvh7KKv/qxtkHA7US4V20=,tag:Z4wAFk0o8dAGHLC7nch3lA==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:PbfHXUPpqYVuMe5YkcO6F7Z7ZW0w1ElU1pEzepCHUKg=,iv:pHhSsF3JrANcARDEtIcAB9epgwpUFd+7YJj+hpf7SI4=,tag:CS4W5NNXK61dATAlTG0JXA==,type:str]
  S3_ACCESS_KEY: ENC[AES256_GCM,data:G9+Ac0XEdcqTuYoNOKC9JIFG8rA=,iv:1lYucotKt3TaGIdHG2D5ABROWbvR9lldv4zou5UPHZU=,tag:8jQ38NWsaidje7o39YHb0Q==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:ZccR8es0euj0COKvsLdOxsGF5MGQgjSLxtZQSWazc4E2do0dEYId1A==,iv:uxM1q9KG7HvIKFylBx4Zu2khr3osrsmDNHFEX0pe3Cs=,tag:WNBzw5+RfcjswAH+3KAbIw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:0ad2tz3lSLsURtgrTlgGjr/x1jwdrg==,iv:iOy+4257+5Os0ajcQjVlNGQF5qfIYCpRTgHkBh1bg24=,tag:WnyJl5W+2dtAocX1BxDODg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:be8+ZxERqDjdzAu+hpeDuzfsZTjsrqEyGbdsZF2d5alVBS65YfQnNV+HR6sU6zFIwB8=,iv:kHo6Kx/znI070BVxxsV6cZ+tSk1vhqSnNDShoiR7Wc0=,tag:5//4TBjH81vbTZH9118uSg==,type:str]
  TOKEN: ""
  SMTP_HOST: ENC[AES256_GCM,data:zaFiVDtFFLicHhtB8Vbd869oYZ1Plva+tYGRartYqSOi4NXG,iv:VkuFWy/V2JuP1EOLw7qlwqAe341oLH+yS0pCiy1kHgE=,tag:nW1KsNz0N9AbneEXKK+g7w==,type:str]
  OIDC_CLIENT_ID: ""
  OIDC_CLIENT_SECRET: ""
  #ENC[AES256_GCM,data:kNBcyz+5d7t+qG0+SLE=,iv:E5xuhdxN/sJdill3E0Y2aDRNAif9QwwT+m0lPB8+pV0=,tag:jHs6Fa/LWOExNV9/Qz1UtA==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cXykqk+gxE+r,iv:LbQ4cqWI3p0zSMWFgegpeCPGxSvPV/rPcpPi6QMtHM0=,tag:Gh50FXbyc0L55Wc4UKdk7A==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:xZ/O4UJCKYi5S4JSCH1Yyv3ppKKOzk+WzvB9k1x7Gh0GppwZ/4E=,iv:RVjo5KlRlkV7/qmGLguPFsn2/5VUA9gFMgnfFAbz5Xs=,tag:4BDW9d9CTFC5KPIIKKpseQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:fq1UxJJDOGzU,iv:DKj4hmSuQVulFfCIgmnRlw7IasJQwJ7PHC/QsZ7cKDU=,tag:GBxgnlM6j6sWPK6Dz1eZSQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:t890r5IMco7nj6I74f1sIxNtrqg=,iv:oV6e3W0gk8OcsjNnsv1sKJIPYzjhZSXZ5VtLCNQS30E=,tag:bhLzT7ymKTEiIP8AT4M3Qg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:gJc45y99Ltl4ubo=,iv:IxzKygSppk3gipWY8gWN+xNvQh2x80mJK73EAFUNd8s=,tag:jCrkLhzQA0MgjTXEb192VA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU2czbHQwQjdpYlVCQmhO
        azEzUXplWUNXdFFSZ05HNHRsSmliZXVCekZvCnVmcXdoRzJZUGRPRVU0YXVLSEhI
        WDZRMjlIcU11aitSaHUzMFBQaXhZRGcKLS0tIGxKeGNneEIwV0h0cVBFQ29ra3pq
        SEVjais2OTF2UmhTZ2o1QzcwVDlrT3cKqA7tWt0uVwI+C+PfZkzXqhLXAlI+P7/8
        wBBpp23b0UZcgHkOAcvqq2BUZdS4oqVwT8pyMWigvAfQXlcI60YR/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T17:24:46Z"
  mac: ENC[AES256_GCM,data:SWYnYoNrjn6VD47y53mIVEOWH56XRnL/gTHIKJ7x0iG4roBQbNvmoKX87aXu9NrunguFA4KtpPd7MpPAVO9gnKkLRpJSXF8qZQJRsUfjCZvRpSoDdEC9x4UHjwOrA6WKWv3xNfL1gMc4yCYkAcroGU/O1p+HWoW+ReyJ2qEABm8=,iv:fgy/K8lNiSWcpn9+8EQGPq7ZycFlCc0MhoAEiWXJKHo=,tag:ClJQDqBPJA7nMU5wJ02rBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
