apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:+/9e2qoVlggO9ivwbNj1ECy4nR04NvR3u7i19/Zr1k7pnqxDv0BoIw==,iv:pQVV73KWJ8nrDw5SZSviDukt9Qa53QzQANBtT03TAhU=,tag:/Rg3IuzDDake7i2Q5xVJ/Q==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SFVJdk9YTHBJaW4rbitp
        TG1jOGZjTXl1MjI3MzNOT2hQbDNSbXJmcENZClo0eTRsaXZzeGJsdkRUejVIMG9V
        WC9hU29aSGZPK0c0WEE3Mlc5ZVR5NlUKLS0tIDBzMElkU1VkQTNvS0ZXYStDYkEy
        aVQ2YjhlRDFuWW9jeGw1dzNPcW5PemcKedVg6KTOE7zT+kCHpMxMllqhLrK2iqeM
        8qSv1e5boiGbulOaJ2u5j0LVG3Sjzkq7EYMzP8AviHpHDrDmn4WzaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T11:20:04Z"
  mac: ENC[AES256_GCM,data:6CFxxbJmRapRcBo0LvH8MtCJcOnPrN9m7STy1+aKLCPC0IgZ8omyVjbTZ3CAbhMVkSRM+3mc048GxVf8r1j67jjbrXyLNbcSoDpWyPFZbUEZ2MwmJOaJrP3BJe90yKQPUGjF7ShZh/ZPuz+700CdsleVbtD7zY0y7Ct1qjoRCa4=,iv:CdmyrWLtjOpRFy7esCC/pksoQwaE+JdOsq3EDBrQPrs=,tag:Ya0wPD8sX9W3vEf85j5Vtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
