apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:BRLu1TbaWoDUW0Tpb3ui7eO3JPytD9qu2G09FLYJWBDj+hNrr/kDmA==,iv:Do6hgjWXGzDjHYq/FmzV2T9QrqzWvj6HsFzdB1urJjs=,tag:DUSr0Gnj2au2MvA0URX8/Q==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV1FKUjU0cjR4L2twdGpo
        VUtoa2dyUVFEa214NWtVUU9SengwN2VYa0RBCk9xdUlaUE9nN0RkbjB1WXcwaGtu
        THlLRThFd2U3SkovL0tER1BtcElldncKLS0tIFhsS0VHMHRDeWttSDEwZ3NvTSsz
        c3BQZjBlcGN0N0tFMVJmbXdzNXlmT3MKrwbLPn8/NChkH76jHKi6UohCRvDHmos3
        k77Yq60BjmIK0xcgwyRf2Ecbttohgsc6NkT4DU03bDa77AFliq9YkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T17:04:02Z"
  mac: ENC[AES256_GCM,data:wSX3NyY2XCSeJtZtuzHCkTxu6usTkKhcjN0xa4wWWO+0F2Pe9oMzuBenIMXZ/EH3FKw1yhajUYTaoRGE6B4cT7kj3b70uN4EQxmDgrpYEGt/T/4IfYW0ZS1/GFp5hCmjjQbI1f2uCtwWegXwvomXFtVfFNva552ZJEb3D3ByADc=,iv:oEmAcDm1NjLkRGb6aZmjH2CDuNTYKomAZZyzKsvwTUg=,tag:PbFAZNKFKkO3dZhQpl8LRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
