apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:VRdzf2BaOKIHTby7O3U/PErFWRG9t7yNJW/yzV+l5q1uzypilSTmyg==,iv:LyOi+RfaSE+55grHq9lDZsYvW8WWFPy5grNVtNE3Qp8=,tag:bITH3bYsUcJ+9s0eUjGi8w==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cElSNGtaL2htUkNiSXFw
        K3N1L1cyTW9Xc3d2NWgvVlo4ek5ydk10YlFvCmF1dW1ncWJweHdrbXVvcUpNb2F2
        L3RSR0RIcWgrWE1HakZwcnRpRmRBMGcKLS0tIFBqak9qRnQ1V2dxajRSaEk4TGRo
        L1o1UnpmbmpBU01yUVE0OGIybVllVncKyD2hJzTb32s3mvm2bsS9Ebc0A+9gATeR
        Ym1KJr00stEqsDa4X3OeqOfDhN2x4CMnEDWHjsKhOu0GHujHo9T5Bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T17:06:54Z"
  mac: ENC[AES256_GCM,data:1pGsFOMxOpXp9N1Fv1kOH/OeC65RXXoeTGNMrKC9uULK0nEN6CwWZhegYJIZMoOCu+CgvrBX/doDv/eNPMG99rAAus7J5bjB5ufOLznxHC465GKGoYKzweHkWQtNUp3pITazat98sPxarurom8BlbXVXc+SJNlU/oMxvrZ1S/Aw=,iv:RE2eXUcAtvNJxXe9Bo2dnSkGk7RfD3GZt8YlRBcFkJc=,tag:VYF4gPIkrfbj1psK/MTmYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
