# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-r2
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:IfU64LOXBBhfknue8BBi4WI23SeHJ7IVPi9PDOE5xevyd/bv7IZ9qLhv/LUwwEOe2JjHIDbERiwZumryxtGrPoGH,iv:xxFirBrhV3N6QHW//qqhSOzujgaEF5n+ttgOstR8jKY=,tag:iE0YeoJiloXRJR3lAVgXHQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:RKvebvPa2qS6XbCGzM8/DzWcWXtGBNYicqpdfke3Zbr93V6PAQ7PVQ==,iv:/tASuyC3xr56aIxry02No7Aa0IxbXtB01CjhzjiYeoE=,tag:dVSWfgZOFL0MIHadTkRbiQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2STWAkFSr2+Sk3wssWjCgqBqTkA=,iv:HqjQFD5pOKVfXiEDc/w4jfLQOt04v6/PYLiR4xy04kA=,tag:QiU5D12M0sDruBdKPlrbQA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Q0jBR/MJONTB4Qk8yVYFDZgwnkk5NvjmLnplmXWgDfPOmWrLcudFvg==,iv:fjZXWGrs+pFv67TzzNmh/fiibMHnDtN+VJmw8j2m6ig=,tag:ckaIHEWNGw2lpeJmeYSCCg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SkFLeEJjbFdib205WnFi
        eWFGWTVJQVZWM0FlWHUyOTJWRFFQcHVZelVVCkFOM0k3Q3kyMGlWM3EwakR6cmZw
        L3VoSFFHTVR5V1VvUkFHdm9haEFFNWsKLS0tIG5velBBS1JqQS84TitSNnkyV05Z
        YWM4RHdDa0oxRkYvQU0vUHhVNmUvYVEKdeXlSFN7nwGOy/U5PUJDIoYfAtrAzP8C
        VGZw9Ad00IVGHj9nuoTBDzCgJKdxRcxcjfslYe2BNdFm+5HUonucFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T03:04:13Z"
  mac: ENC[AES256_GCM,data:JSsKkA8V4Q8BKSMDPDgL11pTiicbdGR4EvaTOIcfe5HSy9gXsCZnuNQeqbgj8mV3A4AnMWl3wTaAroJ12nhXwDRyJlHh1PcXsoIBgIQEvtg0P2CiGAP3/Mf4g/Q7Km4l0t4nyBLavhfoXGsD8KOZIiHsYBQ847lfAkoP3cNmSb0=,iv:ZjFQ4Esmys/J0CaVGKrdeAuX8xzbkJMQVEK3YZDI/Kw=,tag:LzSsJ/gFf4ql/oNlWbrRrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
