# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-r2
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:wP6eHY0BhkAPfhfEqTMPLHG9VavZQjudELxLmxzgYgL1sxLGfkQeF6a0TWIHMGv+O2SVM86nWMWK7DmWBRCFGZZY,iv:Jtdt1icWlYV4Xhq5TW1NX8qXRdOh67ubDSNzGE1vOR8=,tag:obnjIdNoZXsWQg0ddrFh0A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:AeUM6l2yPFKHnZaL9iFQCvnrDge9Ej2+KLcYA/MpPpshTTcmcwPmZQ==,iv:8Wxwc8ZLM3tLEThWz8/J0K9tuWjeQXxigOzRlBcEkqY=,tag:TVyHRRzI+ZV03jvzqlDcEA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hlOAP4gO1aViA49j+dQfIRe4NbA=,iv:aRcfLo73nIbvbSCHOmX8uAm8l6uqQJKeLIW/eKb4CSU=,tag:+YMSaUPw0s9psjS9M+Jddw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yteZSW3Psf7VEA0sfBkpjgM3tWeKPVt2sgLQj2ti7h0kn+J5qaXoKQ==,iv:4yymLAMJ4x9pYcJZpsdwOypeXniXox16LSPMTwhoGq4=,tag:mtYx2idRNBIe9Gw3zrkbUg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOEdCeVZKaWdXOTY1VGhu
        Q2FOUkNSaTFXN05IY2pmR3lYS0UzaU1YTVhFCnppWGNvLzNCYkRYLzlCTlBzaWhS
        Zldya2pBb1BiRXR1RW84Vnl3Z0JoencKLS0tIFNJSlg3RjdFb2pzTDRIM3NudW1O
        NEUrNFVTblFiNU9zdE42OEJCSXhJeFkK6TL4FmJZo4wH6IkjmzpDLwVchf/dG5Eo
        tA5+YCXwJcd0jqp5+gVRJX99vXYd1tT7hbiv0N8Gmj0so0+v5EDoNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T14:47:08Z"
  mac: ENC[AES256_GCM,data:LzsIjfuyt+HU7BQn8BFwwug3pHcpIM/VjNdqusSkaWBCihx/wYHEI+YFft+uRYP3fU2GrqYa/Wl3SLzvgmkbQ8a0oU1Y2llTCg6X5z3hCErLDW0n1UA5vknmN+UuDpysDFyx3BUS9pD1O0ta+EutEaaP9N71tfJ2247nwRyrrpI=,iv:k5FNzIxkE71gvD18OQRpxD5sYI763rQIBsWnlQ9Q9CY=,tag:rZTAPpPLCYSG19XJDYi1Zg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
