# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-r2
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:r6j0pUGS1Qa36sIJuf3H6qENb+gtbKYyzow7Efuuikj4vjFolrH58XGlegoiijG2QP6jfomHzL7aJ1l9t8JjCFJi,iv:zjHXVh3JWJ2Co+3WfYIm0cc7eC7ezHto9+PMvUSdvog=,tag:MPKbdvH7E6ptdv4op4XHbg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:ummcgakR+V0X9KSS6I1o4Cmy/5jHiI6EiWcoTSZbXBoDnhyKnoy0cw==,iv:baIsjtVLPbsjbMq/cwjgyyYt+6eBrjMHDrW4oKO/fCg=,tag:EWgDh5zxEYNXinSWahInkg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:eT+45ZsHetxkhPacHOMguetGyWk=,iv:Fw/0gJWCwsNZ/9EGhZndCXi/q/HmwHPofz0PgKmKj1s=,tag:FDHYEq+Ptjv6Dqvr3nkDLw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:K2fZ/DbOYREJSzPbFeZW3tSryUrQqPlvLXw94gYDFCzci9TNzqlQBg==,iv:fYr/T/2p1+/t82uhwGK6daJ55FRkz7SV+/yZTou+YhA=,tag:Doehrwj0R01FwsmMU2FYHA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITm4rWnFvMEFZNzZBanND
        c2RiaVRvWGsxVEg2NzB4cmlXaE5KaWRGL2trCnE3bGtTUnYrZjZqVWtpR0VNVWhR
        akhlSHlHV2dRenRRa2s3UitVZExsYkEKLS0tIGFPa2ZnNnYwbWdydHZtb21LdkJ5
        YjhvdkgwN0lWWGFlQ2R5SzhCc2dVd3cK5piVEKCx+dSQXtTqxRFzTrpiCjUUHo1D
        SvXx05NibauBD6ll9eqD72WRvc3s49EZJWYfBF4Kwc3JGc52jRJgHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T14:25:28Z"
  mac: ENC[AES256_GCM,data:9eaA/Ew6/almHUHr68nL4yDGubQr8jMMepxeZdlP4MdfdbyD4DCAg5mJBagyjS7L6EiP0/MDXo2ZuYJzr+23Ad7+rYS+hPkHoyTfFsehty7S1oPaI/ixYgn8iUlogc62glSdIcBU4z17V5FXHCqAQZ+KBhd1zWUj0U8n65IVFMQ=,iv:Q3cAcnOSI8cxAC/vPqe1W5G3Yj+pwpHL3k3O56jilU0=,tag:9B5Ew/7vI2KTa53nlWQWKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
