# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-r2-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Css3EQfNYu6jpzWUyOR0hj4JC0LtA+02CT9X9T4ZVtpdpHq5GDcRfrg3HX2BwiCMQHhJPwM5x+bw0jTahHzWmOFH,iv:gxTTnG+/VARCzsUmwGjTYQq+D4lA7oOPN7JPA7wXSlI=,tag:4AROFeng17Lhy0QRR1SOHA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:s2u3lnY8stHPCzO8ZYck2qZnMhQwZC8MEbUvOVjtyPNWM/P5PKRggg==,iv:map4N4/imt7+oB1MHEgbH+GiS1azBJVbp/KdxJ5C0QA=,tag:/CE1diHBCNncJnTDr1wvPA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wwj258PHJRJZcsjez3CHBFaRwqE=,iv:PjPz4zAdEilFOK8VW5eA2BE9gxHT3lYdrybh4Qex5lE=,tag:x30k9GgsqSV9ElJuRJzTmQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PHuVDfRvcTwxA2+gfvu/XKIyjjrGEbgzru4y/SjZsaApmlWeGbWnGw==,iv:xkhduq65u+f+rsZvSKUI4N9p8l4XpBZRfDsOVQ7rExs=,tag:5GDv2sn1MPyL7uQn0Anvww==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYWsxVWNNOUhDRTBySVBC
        TU1ocXhtZnhnL1doai9LcFNkWGw0RUp1VlVVCkUzZXJJTnIrd0prVEdEMFo1ZFhL
        S0RFOXJWcjFRbGIvcjRYblN4eTFURkkKLS0tIDRTcFc0aWNmWjc0WFdBOXpyWk10
        K3lGTnBIcWpOWHZ2eEpKc0pjQWhQN2MKPEDYjfmEaKeNdwv8PwZRgNk9jIs1DwVF
        TsAseAqSH3rgIZyNU8hRkMrrIdJLk7yXNP1lANw3qJmBlCniIfy8+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:09:31Z"
  mac: ENC[AES256_GCM,data:PsTotueyYeuN6W9RTLjSQAPvoUxsE7bY+8Z0bpGotRzP6pl1aQZ5Da20tHSys4cKXmyv9abGCjwrxIaTHrDzC8rndFI5BT6VpPDVVZ5Av7w04AmJDaNxD4ooYmCAu6chujcnOB9dfgNEATLV/Vgy1mqORuNiZ6m8J/ReUtszpJA=,iv:btnjkGU/Aic+dJ7D3/kvygDUfljCSGuEkAkALfX1Abo=,tag:qEehQWi8spVPndLhLbC8Ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
