# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-r2-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:0sdxEtY6gEGGFJHa3f7YRK33Uwsoevh573zpmePUtgS+z5kXsA7kIE10pwnwCqHMKd5EosVYhVCvD2xmg4cVX4R3,iv:+zbICs2j2btn6KF0l5hBjv8kpbdwgqeqhKpKQCXxhy8=,tag:l2lg/fHvM4I/vB7c3vS8yA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:zQ5aUoWazaoU2PDVYJ5oQy3SypmTRRgC+1jPIdp1zcR4xZZBDMLu4w==,iv:rzbzoYuDkK1DbbJ15U1S83dqK9yAxEqEYRChojOYoxo=,tag:STurGskvCHq5ZArodvds5Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EwfVZCjjZKlOJ5Jf0aZIs7v6KG4=,iv:fOS7C7EHhBzSonZqqubpvUScRzkiU8BhjyXU/3NjiGg=,tag:nOnGBIca/GrW+LeeyTj5sA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Xgptr5cGTyzq9KKyEGzU+41PyKYIyIAkPuH1M3o+Ixots7o8/ACw1w==,iv:9ZNmYsGZLn0uvmOJnpsoNxRZQgbsKhlhZC7Tcg79/+8=,tag:zC0NrL16l/LJL0tdF7MChA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwektsR3dQOWdSdkdEQXdF
        TUlwV2RzM0dIQ2RWaFJYSTFvdWtocGtwMHc4CkwvUjhRV2QvbGgwODM1VThjKzJW
        UkgrREhPQjZacWx1TUpJV2pydFU2ekEKLS0tIGVmYjFWQnJSM2pNSmJTbzNlMmJV
        cjBPVFgzbU03a05rM2pScjM1U2pvN0kKvzh6fmFAfc/V1PXKkvSlTjbgJIlmdX/O
        gEburHyZE1UXutomqLnxBhblCapet0K20Or/3YzHNbAbMxxIpkSyGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:27:48Z"
  mac: ENC[AES256_GCM,data:A8Y8TLvUAJEKGMSgsuxsG2Zgfl02Sl70KpMy8WFY/xUuDW7z0zT8750ul46iAYbUhBne9J5q2mIPEmHZ3MNrqR+qiYaTya63P0WITSPEuqf+XoU8Ik+Z0ZKOKRnINRHrGPmIanKM8izF57pA7Hjip4jSXfnIHwMtmV+tA7Pmviw=,iv:JqRA9vvyP9mSqS9DlHPIc10LNRhwuaiTswaWI3S4t+U=,tag:XhYB6HqMRO8jx3NW7AtZ1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
