# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-r2-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:vD73aKBQqSyvtXV94b3TlBfgqPVGmhPauEkVvnPlaQyWTEF0D73qt9C379olBNYoef3AMuqc3qxH9DjCE3FZZn1t,iv:BTcSUMUINdoPUZwatHOhdOUyxQcAUJLvvVXqIp6hvyM=,tag:FwvYlRDdM0nxSbH3/qF7+A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:f9GCip4medwoE83n5QCiFp6jt1LK2tEfGwAQ8KOSexnZcpvjBCerHQ==,iv:1R46EicpYc0p+CtSx5FP4cNq920qlOQZqgHO44xm0AI=,tag:WFYbi2qcItwlm+Bf4JjnIA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:u6YkyOq14BVFKzhCM7KaY32SjBc=,iv:sDpLvvsXwgUuZeloE8cV7DmE1G6LlBcS1uCPwNg1XZM=,tag:b6U3XY4aMLuaBJedJyoh5w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NPDku0bnjdIwXXxGFqOfULssFyFulNiQpUXIJGNzxH9E04fjVZDDOA==,iv:hOL+XzKKr8VlQOwQSdjbE+QDw6cTl7VL/2Sv1w+pDIs=,tag:as9QsEwjLkvF6/BlqoM7qw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN2hFSFNNdEpQMjVobXM1
        ZTBiUEEwVk5vUlRoTFJRYXlkdHJTZ2xmL1ZnCnNXeE9ZV0ZwangxNnF3MTZtTTVJ
        blZvS08yUHNYY1hNSHpvdjhNWHl1WEUKLS0tIGpXV1NWbkVNZ25Cd2N0K1Z6aTM5
        ODJWQnppY0p6V0tmQ3lsWmxWWXZMVFkK8EpwwmOX1E4hEmNgaDG2Z4j8gLGZF+eB
        mKk/8knIVdJj42EUg2uly3CdKmZsxHmeyPES78kkNteM7DhNMfrCgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:28:04Z"
  mac: ENC[AES256_GCM,data:3tW0FyDoYNyKa00nZ3lWwfmzlZLVc3mF1jV0Yq4q9p9s6ycsFZzRPhKIfHOj90wfw9Ie0dS4neBaCC5YdsDYSj/8jbwe2ptlq3db9ovGLw1PzghUSoLhGyoKsgLnuZTRVX1wh0s6G6pzizNhakwRBWwWyRbUlinJBIbAsf52xeM=,iv:CqXzGozqIVFkYoDi8Z+p45JwXYTQ/IHWlzQfzwQh/3c=,tag:b5Xywvqr3MEULj6YsIHmxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
