apiVersion: v1
kind: Secret
metadata:
  name: paperless-ai
stringData:
  PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:loEFD98/8sP3nAOieJCZ58rSOJTSS7wzN2enjE7ari3EfAtik2OGiA==,iv:SkFlPQtYcu5PyHau9XYWdPhr8tQ0ZBY++021pWyeoDI=,tag:rUcRG0oP++/GRYHVHLFvyQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV0VGejFLNmoydHFIM3Vp
        M2EzSU9oTnBUYTE0NzhjNG9XRUhTQlpvWGtrClB5c1RrejYyYjRWRTBwUHRZRW03
        R2JVZnpRMWYxWk5RTGdKTWlMZ0QxR0UKLS0tIEY5RG1EeXZCTThqbmhDaStoc0hI
        N1JMRm55N0lVVVZtaENrYVU1d25XUDgKsb/Jo2Qm5Q9jfmGQKyyUQaBWePxWsvh6
        dh37lEqw4PHLft7/UblBRpwyEvjfDdJ/cOtE71zUeB99yRjW64EI1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T12:36:01Z"
  mac: ENC[AES256_GCM,data:xM/gBvmVLKqnpxF4hSq+JwgfNGsglDjtQzsmSY4fJ2dBjqsNo15Ck/Hav313veRCLar4EtmiT0+GG46ZswXT80FmZh+ro/VG1aJS5DomVb2vyb26jtLXJ/xaoK/1bjhjbv4GU8avJsqYWt0m3wcq6Rzhpv9MO39B/m3kFPOsJ9Q=,iv:e2AUNN7ZHxakgbQjqe72pvF/hdQoLoLP1NsGN4vQsas=,tag:lLsta1XnX2a7aIw0GprX2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
