apiVersion: v1
kind: Secret
metadata:
  name: paperless-ai
stringData:
  PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:Kcj5l28zu/qq+g0GQKyHzke5x84Nlw40FYyybsddVjrhnZTyRu0nPA==,iv:FzI6b48KuDBAHSpLXAxq5GU0+Rg8D3A2EfsuK6dr/pQ=,tag:4RVGT6WJySag7O8E8uCNZQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeWJzYStCT1pWVHV0UjEw
        ZmJLZnh5eGVpNGl6V01HNURVeDIzRFlTZEFFCllwVGZqYlU0WDV6NnduaVdTK0Jn
        Y3lyOW52ZkcvWitZVVlUQTU4ZGswSGcKLS0tIDNBSXlXWitDMXBjZnpHYWFCY1JP
        emI4WTFIZlprUjl0L1VISUpyLzdTczAK1Hcas5EA8d4p9WcrJ28kf0kmYqIrNQRa
        v88hSDR+gRRE9106xpiTT9V9c/jkCL0g8v+fHVv2liPCxzTnEVQJXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T05:51:42Z"
  mac: ENC[AES256_GCM,data:pl0FJuD/Fsj1ASj/0lwHpeyUr439aPtj9w0waXnl8BI9llLdk+7L+Tbk65uREu9rAfZm5HgpYBUONIkeVleW66NBEFwOnxK7icZoaRYEmx7CsSPF2EdUTxyyjz8n4LDXslORpkWwYT0qO1ksaQBd5BvfToZRzrvQcjc7u7kxDdA=,iv:CDE0XuQBspCpBQmeCvJFDBoIF/alpasal2fcGfBGwhA=,tag:ilfzmawu++u2nTM8xqALCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
