apiVersion: v1
kind: Secret
metadata:
  name: paperless-ai
stringData:
  PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:dG/LGh0qQ/Cg2sny3XZJ6VCfbRicmVw74X/0n1/PZosCcPN4bMEKdQ==,iv:ROPMrvuH6zYU88ltB+u3GTqtjyMz3tRwHvbGtDXBI3Q=,tag:DDuuX4RQvegmfrK/Xv3iiA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtejNRQmlPSGc0a0g0NTRk
        MVZRTlc3VGZWNk85UTBtV2ZVSXZVc1h2L1FBCkVjWkZ0OHNDQnF6TEpBbG5OcXNI
        TllGc3Y0WElpN3hnYWQyMU84QUVnaGsKLS0tIGM3VTJJa3ZsWlF5UXhGaUdTSERt
        WTB0STRXM2wva0xpb3ZWc0FNVDVaNUUKrIsagPQY+XR7fI4hu8CtbC8KmFk8VKaU
        GRcQM1DSyyB4Xd7zRjPSJfhFYqmR7lZ7BrJsOxMH/WR9QTQL7BWSQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T17:55:32Z"
  mac: ENC[AES256_GCM,data:99ru7gCq5arMkewP5MHUlRySRI7A8CNe63bAOutngSIN3bwBePZm/HejgpOnjL6h09xBseTfUGuafUnC6WPkFTka+AATTLKltCxFowb2ZjH4P0JgENue5RMBR3p7DGxpR8EEOLd3CeBmP3/H5fLqQr4pSmh5Hw0ubdlnWvLco38=,iv:78L7Vxr7o0IWKUeIC+3ucXe91kOS7InPgwi6ixdJqKY=,tag:+0sr2T8AgwH7RKzwT1oNmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
