apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:qRVmta1iEZwIGjAFxwp5njHu2n6lEFJoZkdC0ws/k1k=,iv:5YfqBRRz9lU4Zf8LHIOynTX8KiBnikB9fxePyZzK/zI=,tag:JpKq4NHilxjj048x20Nemg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcDE4ZGFoQkdybTA0M0JF
        S3lWY0l4YTd0d3ZaZFQ3NGtjbTNHbXBOV3pRCnVkOS9sQ1dwWTkzN0w2RnNBeEVy
        KzlWRkY1SElYM282Ym5qeVZOUkYvTXcKLS0tIHp4eVNWZFVjWE1yMUFUblZzR0d2
        MStJanc1WG95cWZlSWNDTmU1a1VudXcKVEGV8qN9t/1jbsvZkqaSV1t9DiF8+rWR
        vEAZ2Dul1G7qUw4sXpaJc/Mx+GQOdKsMwmVguWVr+yYd133C8AqMTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T11:41:36Z"
  mac: ENC[AES256_GCM,data:gqP5vv1C4VHyGsd67wEIw4Cnq9AEKEw2CqoG41B0C/tz7qm98dLW78NFUV9mN/Xm/a+bDQCHD0kg0xfB/iEzL4ADwLNSQ2SCuonf6jd2J7jj+7l8Di/D9YlrRoXKXGD7AxF8/uE8IdjsZASeOkxKJsVo1W6r+1UFhYl8McbYgMw=,iv:MWofw8FF9SiTchREuXJV1I4qU//S+WoMAtn6+R+Kcfo=,tag:XRsbThfP13AUwWFyr78tAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
