apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:YBhPyoEh5KC93vpUZ4Q/pbQFNq0OPNpoTpq4VZSZh+w=,iv:4T2fpZrgdkNLhzqG9XeCYZrkpDVqqTGKYch34oRSIwM=,tag:JMmT5VfbkGtRajfbRBjS/w==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNWVBRFJuQ0x4a1A3ZG1v
        SXN4dTR0b0I3MUY0UlNhQ0MyeXNZMmVaR3pFCkhLL2JmMWNZSnlhWEczZEwyU3Zp
        b0NqTVhpNUpFNmltRnhaZlRXTmFPeEEKLS0tICtDTGhSck1ORk56eXJRSEtnN0Vv
        T0Z5Ukpwd2RaSmFHb3lESnUxR3FLSkkKweT+4T6+4sDQOJ//60b5XqKCaw5DQZbS
        ZtMIKJuCcMbwEDqWI0JPeAVsDEa9Tfs1n2p6hEuP9O+8Lt3xp9LWQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T18:36:05Z"
  mac: ENC[AES256_GCM,data:+l0blcFA7cc7QRzK8NIl3tFzX0zsCaoNWJ5yhlUWy0Beonh6ihUxIWUIK8wz2D7qKKFi+S+BfKg93Xu1jROq4bgN9OeLf/UZ8EjikYH1FyXdOP0XMLT5AGEInGj5K+A8okLBa4iggOaJ8PCfZBA17IIbtQWv+BCRH7LWtWGvGoE=,iv:errDiFbod+jaWl7Ds9XzIlXun6mSCwDkCSiythN+aIw=,tag:w8NzTZx6xHbv/Gx/oLugqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
