apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:D5qgLSRJALrx2WOcUFyYNQkVsPG9j+dHiAoCya/AmwY=,iv:oMgglm6C6emoUeZllHm0+lXGfVh1uXL8uFB9SbB+aeQ=,tag:y4q0bqfZueixS+SK17bb/g==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYTFTazZiV0htYWtpbFJj
        dk1qc0hlVGFXNTV1QUgzTm9QMEh4RlpBckU0CnZUUS9BcG1zSDUrWUgxaDF5SzZI
        em13eDcrdk11Umd4VDR5YVhrcC81SXMKLS0tIEd0Tmc3WjFlbU5xTHFZaHhSbFQ4
        b0h3UHVZd0JJY0VqZ216eVZEVDljSnMK/6aZJAprIaTX45xPHlhjl22zzijG3FaB
        KsK/VV94eb/HDX+wplXKMz87zn7HRhbEwYOPpp8ZbcZlUi9Q+MFN3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T13:31:34Z"
  mac: ENC[AES256_GCM,data:s7mvrUHI5w+QKiEMTXcnGGJhq5Q2/UpOmByPgUcOSX0vsHdxwJc9/1tNVx6y5G6DicrLKBoL7P7z4dqvLOPwZKLymHV50XGqlcFMmX0zAUuyU1+tKyCGVxe8DRVi691Dka3MwikvhUzRvqpuRCbTn93584wJtlkDJOXdZgusBLE=,iv:FEie44c1HkYz8fTziFOXPUdUGU2D0JOMrGMZfbw/dio=,tag:7tHt8pvRw2TjGTz9N3aORg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
