apiVersion: v1
kind: Secret
metadata:
  name: bytestash
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:X/Inh9IbxCaSrQdwhfr7q3B3v3YA0qr2ft4DzzG1DEs=,iv:gQ7uRjRXfo4edL8W1Q6WItyjisVAhUSDZdLynppY8W4=,tag:C3DF3CSJxjYFw0wjJ+FIlw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZjhPc2JkdjM4d01NbVZi
        RkpNZERSQkM2dW0xRGFOSEFwQmt4akw5TlJrCi9EdnQ2TnhKU2lTL1VVZEtGZ0hv
        Z1gwV3VDSUgrdzFpYk0zOW9QQ01CTm8KLS0tIFRqSkovSUQxLzZFLzlmSzdNTmt2
        K2lwYUt2T0NXSmJmdXZna0szWHJiS0kK4vADpPmc9/05FStNrP34nrVONF/z4JbX
        LlV1cBiwwTBo4iz9s3BPnzOHAyb9tVDW4vt7vHb9blTsNFPQLXbr2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T14:05:37Z"
  mac: ENC[AES256_GCM,data:mhRtKYi72bDM/a9QqZOqoFG3TREiJ44iEQracUPRKtZdSZrhZE9lXwhvD+tAaMBKMkc2H2k+PelyWWpoJicvyhD7jMiKHXQgCHT30yJNdZUkoszDc6x6jL/MgiNWF5t+grlbGnGe3Mh1ofoEWdci/ijMPuxZf1TfZ0d2xr6Qi54=,iv:dmz3Nw2kSVI0pQc/qmM1vEsVF+5QkiNp8pmteuIA74I=,tag:Mg/88mMrwswNAuWmyrD1IQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
