apiVersion: v1
kind: Secret
metadata:
  name: bytestash
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:v/QPZYm386yj78cfC3cQkistjZw+Q6IbG6A9jL0KLz4=,iv:a3/vbaz9bpLEJTLkN3f6jSy1K3CABHxlckcLaqsRm2c=,tag:Yt7mppQjvGxQCvAs6fXsng==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeHFSaTBsTWZQTndOQzFl
        MVpWeXp5b01MTUJuNmp5bjFLWVpYWmVzSEdNClpCS2NCY3VvbUpiaU9nWWt1Uy9i
        REhIdnM3SVZ5NURRUzB0c2kxUlY1dTQKLS0tIDBjNFE4d1BUNHdYTTcxaDl4cFlk
        UWE3bnAvc2I3T0hJM2Y3T2ZjME5tT1EKunnk3HWPhmiyGpL8YaWV9AG8ok1y35oy
        8PVYYaPXoGcIlI45MiP65Fk6Co70MUSnYKtfrC4OPGt0ZqDKqFJXTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T15:35:35Z"
  mac: ENC[AES256_GCM,data:jUaDaZzdAV1qwRKS2KIl7pLqoNfdRqSWkl8eEXOgq5nIKnCqMT7Wevz641dcYwgfqhONu57w4I7uMu21GZCGhSDAf5fgrdAdBkkWxq2eHYj4gZUrmxfSvvvC//NoS1CDZ+Hxbti2NdpBDv7PjoSZ48Tqy99oowCzIOice1sRaf8=,iv:+4YX4Im8uH1yp73yCBe1cAtAGj79mATagUd08wjLdBw=,tag:AIFd/5m8fXJ8vLcsnQustg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
