apiVersion: v1
kind: Secret
metadata:
  name: bytestash
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:hocwISMG/nfjqLnfAhywZbagkiC7y6gEHiUEF93Pn4I=,iv:4sCpThqgXFVIGW1goj/r3FtyNA2khXDSivtSKg10WRU=,tag:llQpFaGDTz0nBCkgJOJE4w==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbDNQVzJuTjJnL0hBV20x
        QjNEL0ZGVWZLOEJzYXNPbk4xOWZOaVZaNkZBClhFdkt2aWM5MUNVd05RaHdUaDhE
        Ty8wU3kzaWtYWGt6VjJCblZMaW8zdWsKLS0tIFpKZWNEV25UY29BVG92YURKZmxr
        N0oxSXhzRVo3bkkzQkYzZkFPRlVvSlkK1pIJEmenNfuyLX42vt6ujPszM2DrI6ij
        GOnbSMTfUY4fCjACjD6tU6pgK2KgxiRDnHa4MMLA/wLhBc8AtzPpYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T04:30:19Z"
  mac: ENC[AES256_GCM,data:q5cTBG4PqRyYSpVOedcjRNDmSAy6R9Sz6f+xytAEIZzsjzmhCzIhuIVFM+aQdp5hXjQ7sSUt4Vki4Mh18pYojCz2sZHdwUj2p+QRM37fMNsuiPqkPVH4suQWebVVOPrdfjmvk6cmrrUNMo/H/WpbjkskBh/kgnDzhRnfkE2Wx2U=,iv:6z9AYzM3NqngqaFjBt+KEEkgxgXVkYkoUzrlN5emhbk=,tag:e1ird6fAs85KxZ3i/c/Uvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
