---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
spec:
  interval: 1h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 5m
  install:
    timeout: 25m
    remediation:
      retries: 5
  upgrade:
    timeout: 25m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2025.12.3
      sourceRef:
        kind: HelmRepository
        name: authentik
  values:
    kubernetesIntegration: true
    server:
      route:
        main:
          enabled: true
          hostnames:
            - auth.${SECRET_DOMAIN}
          # annotations:
          # external-dns.alpha.kubernetes.io/target: sso.${SECRET_DOMAIN}
          parentRefs:
            - name: envoy-external
              namespace: network
              sectionName: https
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/name: Authentik
          gethomepage.dev/icon: sh-authentik
          gethomepage.dev/description: "SSO Admin"
          gethomepage.dev/widget.url: "http://authentik-server.security.svc.cluster.local:80"
          gethomepage.dev/widget.type: authentik
          gethomepage.dev/pod-selector: app.kubernetes.io/name=authentik
          # gethomepage.dev/widget.key: "${AUTHENTIK_API}"
          gethomepage.dev/widget.version: "2"
    postgresql:
      enabled: true
      primary:
        persistence:
          existingClaim: authentik-db
      auth:
        password: ${SECRET_AUTHENTIK_DB_PASSWORD}
    redis:
      enabled: false
    #   architecture: standalone
    # global:
    #   storageClass: longhorn-strict-local-no-replication
    authentik:
      #secret_key: #in cret
      #log_level: debug
      email:
        host: "smtp-relay.network.svc.cluster.local"
        port: 25
        use_ssl: false
        from: "Authentik <auth@${SECRET_DOMAIN}>"
      secret_key: ${SECRET_AUTHENTIK_SECRET_KEY}
      postgresql:
        name: authentik
        user: authentik
        password: ${SECRET_AUTHENTIK_DB_PASSWORD}
      redis:
        host: dragonfly.database.svc.cluster.local
        db: 1
        port: 6379
    global:
      addPrometheusAnnotations: true
    # Enable Database Backups to S3
    backup:
      accessKey:
        name: cloudnative-pg
        key: aws-access-key-id
      secretKey:
        name: cloudnative-pg
        key: aws-secret-access-key
      bucket: authentik-db
      # region: eu-central-1
      host: http://minio.storage.svc.cluster.local:9000
