apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  #ENC[AES256_GCM,data:sA2tNg==,iv:AzwHmdcMWw6V/GaVJ4sgP3UY64PkeZ3kbqT1QJMdWOM=,tag:0gL92dV18a/vZvkhoXLpFw==,type:comment]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:bisb/YmK,iv:U96lrM2CmJgWYpKdH7t7oyxw1hoQVBXRARBrFpYLXWo=,tag:/JEXDlH/XFRaz//d76rH1Q==,type:str]
  DB_HOSTNAME: ENC[AES256_GCM,data:iyVx+KPugNCtTT5sjc4sCis0OvOtv7zfRN1O4FB9bE1sYmRP5WU=,iv:4BzBHff8Pcg7Aas0opieB0a6mje2GlTmRqxs5oX6CBM=,tag:8AsjkWbCnXKXaFnzEYTdew==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:kgo4F2Q3hes=,iv:sg+qCTg9JgNU/7UZWwqGUycQHU3ZXGv8BIuOFvKOUoI=,tag:phzmqW48VQxBxoNd1q9Idw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:1CMJsQxsYthDOOM=,iv:3DdSMYXLEXVSZ99P+SSjck5csm4NO12bLUlWx3SI8qc=,tag:2BSsTFERqUbf+IUNL6+2uA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:7XpvFRgR8qxCM4e5TGVGBOzvez5u/qWdE3BaHL+C/aI=,iv:WtSu9wdpcJC8msGWrWF4tlz21qnOn8DVwZtnBfE6XXE=,tag:lm6EkgAv7Ym8NIvNgI2rUQ==,type:str]
  #ENC[AES256_GCM,data:nFksgAbBQny9djIKdLK/c4l0MC6Q0zNhzgpie0IVwp3F10hCiDiftjmk,iv:AY2lB7wGEEBoAOrrhmDYD+Gs82+1DO4G+ZT0lLrG+eU=,tag:9oOwvmuyzXN5Fl9W9WZHxw==,type:comment]
  #ENC[AES256_GCM,data:MKfkexMQxSGqmu0u4h4=,iv:ookE+1BkwIFpj1saONPR002vSSp02cTF4hYnQXwAFfE=,tag:5yJ/k99WPr/ZqFCVz6E0yQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:SXAzaFht,iv:0pAKulTjXGDZgUb5cajgbD1oYOu1QCR7RPqwxxywoPI=,tag:C2aQavS3qoMOugxsTkavMA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:iB53syQ0Bq3ogO7grb4prZ08JZxSbV/AG7Kv4EXtsnApN3htx0w=,iv:C8zOvbKoOWGY6H4bFQlzJPLpxVLDNq6xwwVfVChva1k=,tag:7KntzfSEWajmhuYFl5AzxQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:2KYHU8slBV8=,iv:fuaX67gr/Wq87WUMzNtWjI9838eGQuiWC9DzZsvG9Dw=,tag:sRSjqtsSxBd6vM5mNmstqw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:IRmDrAOup+hSj3s=,iv:57udBvjWUxzVCiq/odlhoCVbFi29U1qI6dX5c87Kb+Y=,tag:xpZqKAxkunNlua0z0LEv3A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:T8BWV2IQH7qppJk=,iv:s1p6/yRqWMmPpTrA++q/BRLEYQTrDHwkpGFA6WZEWqA=,tag:K2CfEi1VMPPdm+r+ZAbUsw==,type:str]

  DB_DATABASE_NAME: immich
  DB_HOSTNAME: postgres-rw.database.svc.cluster.local
  DB_USERNAME: "#{ cloudnative_user }#"
  DB_PASSWORD:  "#{ cloudnative_password }#"
  JWT_SECRET: "#{ immich_jwt_secret }#"
  # TYPESENSE_API_KEY: "${TYPESENSE_API_KEY}"
  # Postgres Init
  INIT_POSTGRES_DBNAME: immich
  INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
  INIT_POSTGRES_USER: "#{ cloudnative_user }#"
  INIT_POSTGRES_PASS: "#{ cloudnative_password }#"
  INIT_POSTGRES_SUPER_PASS: "#{ cloudnative_password }#"

        DATABASE_URL: postgresql://{{ .AUTHENTIK_POSTGRES_USER }}:{{ .AUTHENTIK_POSTGRES_PASS }}@{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local/authentik

        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbName authentik
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        INIT_POSTGRES_USER: &dbUser "{{ .AUTHENTIK_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .AUTHENTIK_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"

        AUTHENTIK_POSTGRESQL__NAME: *dbName
        AUTHENTIK_POSTGRESQL__HOST: *dbHost
        AUTHENTIK_POSTGRESQL__USER: *dbUser
        AUTHENTIK_POSTGRESQL__PASSWORD: *dbPass

