apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  #ENC[AES256_GCM,data:f8jhrA==,iv:QBc/cJaSnqpzeubyU8xm5bahFBy4N3fKxBsNDg85+Hc=,tag:Mm7dSOQ1WqZvKBQZM1tNVg==,type:comment]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:I31eGnah,iv:a7GtorpaBebK4q3QGstfLn9L4vySO+fxnUedguUuu1g=,tag:ucMKldUVtZAiKvNsJA6+8A==,type:str]
  DB_HOSTNAME: ENC[AES256_GCM,data:qwil+NoQ86OY3lKlr+wQ5zw1TSxmvvonaFxgabmK/rA2p2BGXyM=,iv:okc+QD5oM3V58ZyC2Udh3Qhl1L48CDA6zfrGuFruFHA=,tag:eZQwfxhieC+aWTY/ObciiA==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:9YQzhj8zqY0=,iv:X2AZE4b4zEOyRHnInZyyR3okR/4F7Mibv8AjH/X+r54=,tag:v8rpyfWbjDkL9tDTjrQSqA==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:hR/kcBwSts1xKKU=,iv:ZlspefGAezmuTJnOflcK2K2wM8LJ7PEasdRPMXRRlmY=,tag:bSXSBJMyHwLzGnigZMLZaQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:0Xr2oBZau0vNXP/KA+RRV572uJhhwQyofggU0hX9cz4=,iv:7LA7EYik5B1nzR5tbdZemFumV4+Qd97WSOzBAx6bANc=,tag:uaX9G0H7r2FPTRsefr9qAw==,type:str]
  #ENC[AES256_GCM,data:fU0U1RMLVCxzU4N0x9z2Qar+xyZesMx48xY7hY5LB3hILUbi1slihG7y,iv:P7OZeofvZtP8VkubEUD/OXYw703u17UG9HcAxLJlGzE=,tag:nojfe++nPgGBe18weQXxDQ==,type:comment]
  #ENC[AES256_GCM,data:nj3V0FUIgm6YxHT/IvI=,iv:gF95NC0AiDfw4OLuP2RX1eNK5rYUGkqxPV/vugJJ7Yk=,tag:ra7T9EI72OjNvhTmUmYuVA==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:iR3FdTJF,iv:4U/vXyuPvI+idSP2qmOOTbfejpgWa1BGM7CmicS5GlU=,tag:bTww1zElNc/w4EbEnp8yug==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:FlZh/W9owjruScfWBmsd1jBOFnA5JD6qLcYw8202QoamhAT80PQ=,iv:Wmg2JlYv3WogoHBD1fpe1/ZZ9ws9nSeTF1snPk5YpJw=,tag:FniXlU9fKmcn6j4YexURHQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:fc6A6STquuQ=,iv:Wz6zGfE6ot6p3+N4PnPMulf2gU0A3L45nzL6b9lc3us=,tag:8uHC0R1vNIdOE8hxLb01BA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ZgOGfemhvt3cfYM=,iv:/5tCOF6z8VrnijTr8iQuMD90wi/Ld0utsfvaslFckMc=,tag:lUQXkIcFgEgrG9qSVsnOgw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:OF6RX0QJab4Pcnk=,iv:dWez26rMoC5BA54G/Dm/k9MgoGEMfVAJ4w6NfylwsT4=,tag:MhZoDYLp+O1fAYhF6TDCnQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcTdKRzdERXByeWNQMDR6
        a0o5QzQybnI0MVVqdnBjdWMvN0RqSy80bjBNCnlEWWxTcERCRU1NRHVIcVdxaG9P
        dDZac3ZYN2hxZm9QekRGRDFJdXdKb00KLS0tIFlXd1pDeDFIOHpjMHVtZ0M2YVFq
        Rk0vYjI5Z0FIQytqdzM3NjBndkNlK1kKs1QuoRAUgFBmhhjIqkVSodM27Ik5IPQk
        RsrsHiFZ3ao3vfTsnE5TKLXCwwfqoAVVw8azigIJmGEYWhLG1A/n9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T21:50:34Z"
  mac: ENC[AES256_GCM,data:35a57buyN442SEw6aQqDso8NHyyzXLDwQsUXT1EnI6Oh4PPrfXQ/GUlZIo0UzMW+FXvzRDud2u31OTy/OMCJtip7jXfKPVxqhBiSZsztQsvXDnZLjbZGRrKZJc59bTdEP/VZMbwRN6ppEeJiWg6ijFFlqB6/uSt3BcjV8GA6wBY=,iv:fXqRept2l9NxM7zLMRJGAgy9yikTSZqy9gCRtJog9jg=,tag:HYRyTxe2D8kchMI8Yc//mg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
