apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  #ENC[AES256_GCM,data:4pKN2A==,iv:Pf4ZME8VyM2fRAm15Oy6XLU3KfD11nebPXvVfcTrr5Q=,tag:Cn8eanOKsvMfkhDSwhafBw==,type:comment]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:a40OzU/g,iv:dilPnb6MVKt2ZhCYWJ9/vY5lh7m37JEk24kz6+0yAWU=,tag:/Qpw9/HKioVqSKVABfjoDw==,type:str]
  DB_HOSTNAME: ENC[AES256_GCM,data:5pbLj9rp8yurXIbB4QgKvlviIc3geQPnLospN6Kxz2k8CJwLXIk=,iv:zLHt3OPmCAB9obKy9KIic2xTPGKJWuCFBe9DHwf0t0s=,tag:XsErjaiSQN8hAg6gAqWudQ==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:cm2QGymgMrk=,iv:DdSwL/PpIItpFGxyGYwEAWp2T64yAr2aqAuWp1ALXxs=,tag:afGK/EQDD78nnw48wf9p6g==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:N+65M9lJjU2Xbyc=,iv:ix56dvv2r77xD1zx9iY16uNPReuVKlwZ9ZisQ5v1faw=,tag:uXuHjWBEF/SO1QcGxuiGeQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:92v0mVtLv07SPJ9ZJjjDazpQ6FE4sQsPv57XQwA+Uyk=,iv:uP8ylwo6tGef+Ouqkb1O65HBijAKdyQ7F79duFIdeTA=,tag:yq+CUtmU8wq+ArORfYAf5Q==,type:str]
  #ENC[AES256_GCM,data:TUzTkumek6LGCR3JfzyZoeavX1Ahthd+MTT5b38Y5u6T5FdqjSYz5T4Y,iv:oDp/SL2+Rd+iKrY9iM8/Rmzg86h/xnC0qVZhGx/SApY=,tag:3JXwTP8JGoZsbMdZvBgBvg==,type:comment]
  #ENC[AES256_GCM,data:NvntzbC+/YddlFmYQrM=,iv:wlnOD6AxULjidLCTngf0MM9NHuLdv74bGnfG+ImWcJY=,tag:4/rH3+UtIV4vLqtrQT/D6Q==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:eEovM9hp,iv:7ZNzPCS2Qcfjm18C8kmzNdPiTc8KByLJE2JUFsubDTE=,tag:3l9Jyw+3NQ1Tg4oyh9Pbog==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4wkpvbpgmV9UA1WyC6FJ8aPpapqgNDgGcfueDMr9CdMzAQ7xwP8=,iv:pBdU47yU2Yx/741FvRTCLgpih01J/AvoprvX/Qzh1V4=,tag:a5Med2Xd7OrWqvjtNpXpdw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:GHnCFPNGEJw=,iv:ABdAD/yWfPf+37Bl80CZsOssgji+HDfxdSqswbcSc/k=,tag:jOapg5d5XC4t2GRXoVHUeg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:KBXZ+DpL13IsO94=,iv:jDsAsVcgGV/UqjR8C8OwiMMge1zz4vvUA6P+CmAHT1Q=,tag:HUkpEunPn8s9Y7uOonKiNw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:oj3JwZKnVNo6TcE=,iv:mESs+RSVyMnVJ/Niwuo+Q/RmFVza+xUuvNiu+9K2EJc=,tag:Y2pc5HMgNwlDkpeJLG45oA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYTZqamVQZnY1Vm1mZThy
        R3NJT2JsYnZnWDNZd3IrSWJTdzYrTEkvTmdNClRyMTUwYm1aYk0valNRK1I5VDJt
        OXpzNUk1aFpXeDFsZDVBeXNNSEFINkkKLS0tIDFQSXVHYWRxWXhRdEg2aGFXRTZR
        T2JDa0tRK2NPQS9IalpxNkVyYXI2aFkKoC6qbL1jXXqEeePFvW2UZ80SoXPKHxT0
        qEEkoJGidANwpdVT/U0luH33IqAk4R2O70IF2DL7wFPrqMoGaThrCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T17:00:45Z"
  mac: ENC[AES256_GCM,data:U75PNJZU2SzwZPFBpHjxDuR22yd8oYuvRJU9N1LIRbrKyBnBOGQ9q0zuUIAGAHPSHTfFidALmvkWyBcg63vxSkLUVnrgvqXC3Kl8Nd1ky0qRvcZGdA7VhuEEGOtm/O1xIu51j3TFC4vT+iNIdangjiXk5ZE5zj0eoo8cNC7KA/M=,iv:KH5BBNXqxfEbc3yQZkKKIm3aP4sXtGnOGfrjYzPUICc=,tag:HwTT38Fs/v4oXV3h2nhTMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
