apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  #ENC[AES256_GCM,data:FEpYAQ==,iv:5l8z6kWQxcyOIIuGlLqKUC8sJg0eKFOzNZVO3WVZtGo=,tag:80ggkBp5x9yaaAcvAb5VBA==,type:comment]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:9UqewbkW,iv:z/jWJIIwCDgtxiW75emrJH7Afth5qmUd/dz09PkawNU=,tag:alJcN/Hx9FsqEWQB/WxCkQ==,type:str]
  DB_HOSTNAME: ENC[AES256_GCM,data:PctLWR7WrOJYiEovaI1l9BQ48iv2lzuiksMDiG9vK0GgUqNU0Mc=,iv:+U4pKDtx1kmnbK1nwqedIn68xg7lFe1A0Gt3k3TjCzU=,tag:WXZiHR8HhAAp3wsJndTIHw==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:TW0ahmiemMM=,iv:+27Ih8kud0aR7Jc/ZQ76jXh5cpjbAcJri0ciGph27vQ=,tag:F9dLzzFZOhKUiZLfddunLw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:d7i/eTZR/f/jB1A=,iv:vCJWa7pHe7p7cRHXB089JI8pd2auSlkwHvUD6h0dzZ8=,tag:OLkuTms9//NCaPV5yrZ7LA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:vBNCo2bn9IknbQf3HZ2pAbx/iOQA/vla/xY54GCX1Vk=,iv:5euTLE2ra1TsxuBI4Kj5pCUcq8/Im3WQwIXHSClw1mU=,tag:BHeoA4Z5o1zcytHPD9dFMg==,type:str]
  #ENC[AES256_GCM,data:oq/Hp6kxr6LxrKx3xikEfxztmCYPdGEDUK89DS8pkQBPtm7aJhLPR4Qk,iv:Tsit/ZV+OaWiY36587vDkUz3sooohnjapXsCpBObn4M=,tag:hzHiCI74p3woCx74n+WRUg==,type:comment]
  #ENC[AES256_GCM,data:Qo26glg4a0KikTHXoHs=,iv:Y0nw6p8eGccsnNa+1qkajQYe1E2IrdL3Zw6Lf+wTl7E=,tag:BupfK8Mk1CqTskfCOPnFFQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:hPuWanFc,iv:nzBDUZKU5yNGGFLFp8YnS/3aTzR3VSXsb46ZHnO5qRM=,tag:V6ve79WSQsFE3rLEPnF8cA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:WFNMmHZgzCmSHp0wVGNbX4eD+ue/hL3uLtwWnKqmL+SYrj/ngR4=,iv:ckZJ32DFG8otluzxvcwYfsK8tFZNFctvKPj3o82WiO4=,tag:uQ6OIjRQYvfADLayVP4E/A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Bo/tU8GXsDE=,iv:LZEcyrpUXUEsSVDA7C08JnZqIpsHL4nbS0ZZ+ZqEWUQ=,tag:eKPNZwqig5aDkwW9Eb0YSA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:UR2vNQHaSC/lr3I=,iv:3ATJDEdnjuMLIf4C+VF0hSYDGgn7tfIZJ/WAaslIdJc=,tag:cOiMkYZlLTsIdNrlLw/xJQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:oDKf4XqyUpKYCoY=,iv:peWnjn8FMXyCQkhTuEzFE5O4yX9FvSbNQQ5F76BpGcg=,tag:0yEzv6R3bdr1gFxdJ4/cow==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUW5CZTY1QU15V1Uxbkdq
        djh0TzRzbENRY1BFU3Mvc21Jd1JETC9sazBVCm5UWkR6UkhaWWZ2TjRJNE9heHh4
        Ym5jMHV4dXVtTHNwYm42ZGJnKyszV1EKLS0tIEdtL2RRS0UyaU1LcnhQL0dJT3Jn
        N29FU0JoQ0JaRjNiUDFrOWphTGhiWVUK5J0Id4j1w38KW5dz6FWM//MfSE5cXzPS
        V983bKZjWuZuFeLMgfCwdBSpM/x2U5aCwuh/yEJTBrGBStcCjHfRuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T12:28:25Z"
  mac: ENC[AES256_GCM,data:ZwSYoHbHbii411vzv4ZVSYbhgA1fmt5rKvEw+g9eFBDPJqtx6DILNdwI7gRT5RGHTulDDKz4ipSqFpyGjxTZUtkXO3c/kbIH7GYlsyMOn9SUrFLGx2i/igeD5UpL69ixDJOql6Dc1B6mxfp7moae82N1I2S+YVnLUnOVlUVkhz4=,iv:IE+OekM0kDluuDZsQRXrXEKtZ4s/aCz20WjP3avGB7Y=,tag:oLexzEGWz8Pow2mKwgUqmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
