apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ZPxtjqEk1tOBxg5xh5lTRYSTYJgMK0Vz5q4UtGHtJkIWHpQFQX0qNz6OKsGW1/A9EY0mlQY+rAsmw+MHnV3njoKVoayp7pCI3nPkfltrU+mK3mvgVdPUAGLvTq7d/kanjGxwTN1tiHUZRiME0FOeUtPd/ZiSm5MzhEdFWj+10gEpYF8wc1TrBGqn+UQf9yX6/RfE/pFh1B4kJ49rWhdBBnE54PvcVwKdX2/Hk2B0GtE8zbO1,iv:AvemjvVKGcTT2XNXIa8zwSluwK+BvbkX3yIt+YQB/uY=,tag:/h0vhwzppjNxZhvk2XFXgA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSGt6c1FYZ2RiRElMOTVj
        U0tQdGU1bXYweUluZ0trTTlYVUUxaSt1dkdNCis3eFh0S3M5RTdnaGY3TnVweHpE
        WFJ4Mkp0Qi90eXNTbFB6V0YzalAwSlkKLS0tIGF6ZmNSK0VyaWx4WVNGd0J0RHh3
        WWxYcmhJWXl0eHRic2lBRmZtR084T1kKQ0+s4cRe1COhBU/w4lOy2TD6fZziJi7K
        epAZNFeMkNCkPegD0LYuCuJQXUrzi7/IRIEWJ6GKd7Se1vXGX5U2xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T18:22:39Z"
  mac: ENC[AES256_GCM,data:lKeY7mKHqKDEMVkYGy+LJPWWw6ifYVx1kWV7fTKNYhReBU4EE7evbdxs2C8NnMf/GiBa0t5F+O27O5SOeDrI0hQ4+xewSgfqxzI5yzR8GLhmWjqpgRpwrtafSvj/Bhrlw6vq7qf1Ih98BvvjFARZE+rzqziiRlDyi6YqKf9QGLg=,iv:J/1xC8sgXbNZZZQU8XtBfGzJKjO0XrGI4AX9Gb/ySeo=,tag:DZalWCQM3+7DWo/h9+TrRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
