apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:wGrrJDQ9nOPnmeGqptJDDJfUSoAIYykJrC/sXQ4oJ2jnTCHr/8pRBr7uajkVOKM4K+ZCbQ9Y/6W8+f0hntVNX1DgVNd3vQckQyUkvCQmPHnnTwWF1wrcTgVXQGVga5g7jjvZ6jL/iKM0ft6X8jKduLvg3uEybqqeYHO1S0Ywq3kKmYHtpVlBa3ZS3zMjcoUtGNe9xOCjFbL8IMMPyBpNaTj1cBR0Yotw3C9zCOrxMRf7oqjo,iv:wYLnvV/ZqbLQ4Q5xJuH317KijExFG3Vd7JaF7GqEslE=,tag:f3BKg+aMojMxttYxuX0IGA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTGpnVU9EOC9mdjhxeFls
        MnRpM2pEVlcwdEZYOWhFLzFXT3lpZ3JwK25rCktCdlU0cDFLRFlZaGh0cUxSbU05
        eG1TSFljM1VoTElaU2dkNUwwWGVNaU0KLS0tIFlZS2pMZTRXcUNpMXVqbG1BVFFz
        dUJYUGg4SnRHOFpkS2tCOVpYRm1QVjAKkSqZg7wN7qH2zDnTkvCpBlfaMv+TREIx
        L1jW4px96Hu3WWa6KTfvOpYDqxW/9uMpFQOFfxO+XsOypUz1HTC4YQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T14:45:40Z"
  mac: ENC[AES256_GCM,data:OawDxLHYxE5ZkWScOoaVM4iKGjt958ASpzKPfT90VKJV2xdKzipbUwUKO61go7mfHjbsR/gQtImbxV0bBu37aPjkj8WCMOt55T4s7rpkm4TcK1abVt/JSfUozKhah1ImoPkoiwsKJiDDGKWwDIhybNzPwErezNXvg54mQaNyjGM=,iv:ovzBwX9qsQsK0/dmhMyMn/WaCxmQZZ/1hNeYbNjDXQU=,tag:XYXKuaV08VVr7HMJ2hvJPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
