apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:edLcO59Iy+gbiA0kiQQWkEiHbvVJvyUtDxBU6khvIntvNSVIQ2Bj+QIrCYMXP787hhS/qBGgZHCdPp3nA1Y/p1nKMghF57MJlolgYUXluC0zOvYFoXKxBs//wz0uatp2E6dEoRz8A9+xTFDIGKXdvhLrTs6bmng/YMq0ymP6I1m5OOHD7k/qEkx4kGQ3gp0jKK/85tvmFFIsH9x9Mp2w2oHmeFfuRXi7tmpksh0zWVoCHHEf,iv:ZPrPEWDaS1P8/M8azetkYGC+Gkr2FB3h4qxk3dDzHHw=,tag:WmjwCn8+l6p7WyQV7HqqMA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ0E5M0FnSG5Cd1hkMHdn
        d2lHeGJmbmgwdEsvV2xDTnVUSlhsZ3YydUcwCkk3QnB4dXZFeCttSXcwQmo1cW93
        Tm8zZGdlNmhJVkRveWlPZ0huTTZoejgKLS0tIFdBMGZUMitWdDgzY2NrTEhGdjlD
        RWV1bHN3RFpSMkhlV1dvemhpK2NUVDQKfq1ZF/eMU+78IBO7XEc388qyr3xf5ioh
        QImrwLw41ZmV9wvkIbLzHLQuYKNPySU58AP11wxtO76UE5PJl2QoNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T14:57:13Z"
  mac: ENC[AES256_GCM,data:GcVITalssn7Y3Ck0EOYLJxlloWj301Xtr0sGToR9EXt/CRHzEEZF1TZ5RezfHW4plZAMAtDI34Qq83aYrsUQwjzgHxbfY6uybLWbs0kjH3UJNDHjG03psppJcB9RDWAIQqD4xqbjxowfhbq5UQlIX4gNSVZC7npLXYbJ7Y2DcOQ=,iv:BUQjB2dEooI+7diJuihZ0/uOuVovfwKgvwSX1my6Nic=,tag:6qh53zY2Gnb/W/jRkp74dA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
