apiVersion: v1
kind: Secret
metadata:
  name: loki
stringData:
  BUCKET_NAME: ENC[AES256_GCM,data:0fy5fg==,iv:BRbC24Gw2mjvyJlYm9jkKhfy5VKqwszfCZvhNM7k+a4=,tag:ru+AGnYIAs1GHLouE+Jvyw==,type:str]
  BUCKET_HOST: ENC[AES256_GCM,data:dynw8dIceDLkxD90S1h0QwWKd1pK3j1PXt2zlGJuGyVuoraiXclPVDRT1A==,iv:vct1f3UIz+Te9y5b1+B/QnjHor2hDbQarTz1LeTeZEo=,tag:9cvz0q2SKEbsffC7QPlrbg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LlBV6T/YwU65foAVVQ854slXs6Q=,iv:Oe/fJ8vizXJ+O6LWghbxS+R0jdq9eUHAgwOnTCysNf4=,tag:T/zI3uzzSk8e3AEif53BzA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Qsw0pkqS9oaQXX4L7GFpgd1zWr4mcggwMtxoIxs4XuMBtT6yd8OsOg==,iv:JRAVOlhUdgoOZn2ZYtPI1y3FRyruXHGGh+tpUMgRpIs=,tag:jbELqxdFVrX4aiLppVDyQQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlak9DbXFWRVhPNGJRc2Jp
        MFE0YUZKTEpEZVpOSmZJc1JQMGtESFh6aUZBCi9DYjJVRlF3VEx5RUM2S2w0MGVK
        VlFCK1dQUmJRcVI4Z2Q0WUFzNjdXS2MKLS0tIDdNQ1ZqdER6TzQyM2REZnBwZTFD
        dHZzeUxpYjdrdzJ6ZnNGR0FzN3MwOWMKc1dJDZrvQsDl0xQbrIJdCawBy0OOd+Yk
        rHMunsDxFW8q5um3fwC5GPMHHGLINbBNJyXxNQg9yNs/gf1eEeZKeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T16:30:42Z"
  mac: ENC[AES256_GCM,data:Df1zGulkTs7YIdAdawVBv5q3Gv8jDYpZ3lMnXHBO9CHyITu3anl8yGKXrBol1hHDvjiuVfufbdL7Xz1PDt/88d/Pay862TS0nGs05Yo8huHBALwoE4cQCCSaKhCHQz+o0rYrdY9yrMGVUaPph+FhawjpJ139qc3Sab2LN+5NhRY=,iv:hH56W3nWmqGbn5vI8j30H/Z/fOIm2ZjU91UPmS3n/hk=,tag:idPBUsjfW8LmkgtYlcx+Eg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
