apiVersion: v1
kind: Secret
metadata:
  name: loki
stringData:
  BUCKET_NAME: ENC[AES256_GCM,data:nl085A==,iv:oJfwObwUZX6NtQ0GcFCPI8BlRnv8ck1t3qrpCWP99sg=,tag:xh9PkWOr1BEQRrdnbx6w2Q==,type:str]
  BUCKET_HOST: ENC[AES256_GCM,data:/kGut++LTFbYg8UPViPyd3zQ1gHMIFn4GM7CyFr/nVRt94TfbwMf8FSUSg==,iv:yAx50S9GUEBYUjUBtiPCBhAcSMbZBfE0nfNGqKKoJUI=,tag:QirWrPOCIbc6CyZ62uO3Ow==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CVtlSjHPngHa6UtTlFyCEWEiYqE=,iv:vACP/L4B3uRxpMjisRz8+vJqAVuoTVYcp4kGX7ZCQBE=,tag:Lm8TUXtuzqnxjC/TFrW0pw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pbVsp/S86htwGWrxFzpDRv9m2SSSgcos+MPfmEpZ7PDdxm9r81ig4w==,iv:bzHXNzEWtRC+uIzwAo8Ique0NJrRYnYEARGJY8EyZig=,tag:7KlSHydpoABY3Kv8efWqGw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcWpBOGZqSVVRUmg0Yno4
        RXd2dExlc09TYlNjVXlFM1JjOS9GcVhaMnpFCnhnRUxGVUJmU1Y0OWozZVdlRDRm
        Qk5Ua1ZpVk8rVUR5aUtBaXNxZDNGRWsKLS0tIG9mNVlZM0hBSHpuWWJadXhlczgv
        SHNxVDlxcTQrdTg5eVkveVY5RlVxQlkKM02mw3rLXdLYAFljhEKSHBwIt1t4XwOr
        AZ1bZd0SMLM4RSobwB1s4ynd6oMCdVdoTKTUgpuSJYrPl3ZWOxyqFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T16:10:36Z"
  mac: ENC[AES256_GCM,data:lPl3Eu7rHrFOgy/MdnOgLQYxXsQ3mLuDykoZSjWvTo1iQS6wmWWYWyBgM+/LbDa353fo44ubl1W+FBZ/kpBZR97bnCDWj9Qr7HLGfi+jALpD1Ja0Gh+kT7NiBoO58mujzltZDL0y9IEaBkNQ2tj1waDSwUkF6iuKGFiYlCVnE1w=,iv:l1NYBdDBm87JmpzJFIWg7kJzaCixyXbQTiaU8/VTNwQ=,tag:/OTqJW/ReKPyoGLcPxwyYw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
