apiVersion: v1
kind: Secret
metadata:
  name: loki
stringData:
  BUCKET_NAME: ENC[AES256_GCM,data:Dwjskw==,iv:E2oV6b5GFCtqNz+oNqsN2Ev6kffJYPX1KwFaIrYrtVE=,tag:Rnc6g1Djpa+4yxlrO92koA==,type:str]
  BUCKET_HOST: ENC[AES256_GCM,data:zUrakeU3caIbax6dnsCnvwHo4ni8AEhubpOx4CwpWaLBjt8s3rPsyN0VgA==,iv:hv8gtFKR26qpqUY7c2ChsVV+6HaOeJFB2FiwzJvJSus=,tag:n2ETShBH9rcy/6Ywen/8FA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FARWyA9Dv0lNe3GejfIN+5MO7qk=,iv:Y3h6oXTz4nVA+Gg4WTkM+wlXzmK4R1LiZFp/dI+U65s=,tag:jrnS2CrLQUBZVL6F/bvu0Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xX2HzDofge0MZy2/JPUjPEroySpY/M6RpHLeuDehUyXdzYAsx1PYyQ==,iv:fgyuItrCtvS/4U0/wrmRXZ/I/XeT/TCrfu9hqnVVXuA=,tag:bhW1XaD6fKe06u+ZxUxFtg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwM3ZNZHArTTNNMitEaGdl
        L3JrRW92aDUyc3M2SmdMNkFuUmR2c0hNL2dvCkNjb1ZOV3NhSk96bmJFM3UxSjhK
        ZG9LT09kcmNHRTdlL3NiWXVHWmVzRXMKLS0tIFRQOVVMdHhFRzNsSXRJQ2l2ejJP
        bHlKZkV6cjBiUERsR2dMd2FsZE4yUEUKh6vfdheoD7bi8jcFwcGddRaYwkA+31ci
        hML+zLG8R8C78Cc9g5lXRfIc682mlI2L2rpJR1e92pdah3qW0SudSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T11:08:38Z"
  mac: ENC[AES256_GCM,data:qIjS0sWn4O8KTNTnquMhfQlTklViFnDjLa/XlC/z1KV/u+JuRZmbcGB9Nxs4Ggc/u6cr5/oCrkzMVM7CKl55c/+mzrAJ81dt8KadI9TGqvk/GJKB/IxYv2GC1Eadowh0igrNqfUvht4w9NWyxKnoQhR4mJqAB4Mi9UnOuYGw/8o=,iv:MX4VYgowSjASq1cbwskewDXvbAnUo2Fg6y7en5ZuMGQ=,tag:jAwWAeFyCnQx/hirqbvBNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
