apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:h3m4CntgcrGLyfE0afMNveysCbxiOTfaW8TH71zTtc7aY3sMecpc4g==,iv:h/LNu44DzWDIq3C5GnZp3QZT4kojVp/AYnTiw48mA0g=,tag:muulj2AFOCuutUVaeFv0jw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdFIvWnhENUdqRG13U21X
        RkxJc0owajVKMi9sYlVNWlF4a085S1BMWVc4Cm9UWjdsT2loNitCWE9DalhCR2py
        czlJSjhST3FHejU1YWpzeXd6aDFsOVUKLS0tIHRRSDlxbWZZWDNaMU5DcUVycFRv
        K1JMYmUzWGg1M3R1eUY4MkpGNERJWVEKviAtgylHQvSO2P8qyrGrJjY+ECflNmZN
        ySmyydiOp29gCoRp3oDbkoj9CWMcrkBKvLfPLDs0KMwH8hihzqsWFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T16:41:06Z"
  mac: ENC[AES256_GCM,data:RoN8X4sYO0PanGtSY+0d0+xwrqivuJSY3KxlwCss6x2XPHHrFo5GFax7xdqCdIc50cE8PcLTIErkLV153OeBN2jEDMDxnWU+M8KZYQ3CoHq/HIPDZ9/YJdr+gI4EDfKvPYWtRFl+GgKbHCoJvgD8lWygpmNJlJHYSxeyZNgvqLE=,iv:1cq4EPIOyH/vs9wKA9/f/cL5WHiFZQZ04k3n3QXdGR4=,tag:mM/jqRnywTK1L9NL+BYnPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
