apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Tsdsd4mEmnHjM9weGEnd0pOIIHgKYO83HQyv6Wg+hvqlnfASL8hH2A==,iv:ekXams33U5qoWSYNlYKMoDgseceEZ0s3TMTKb8D4w/0=,tag:dskr3IHyyRrhclkKwiRMYQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bzlweEJhbkZUU2RvZDJw
        T0FkZk9xMUp3TDFqbjlWb1lKZWxNb1ZCbVZnClBKaXA5OGQ5SlU1RzQ1WHRlRmRu
        NU1TTFk4d0NSWWgyYXZtdkFlanB5Q00KLS0tIDFUL3dpenlYNzRoV1llSzV3cFhI
        cXdianozWGU3aXc1N2hSVDhLaEc4MmcKaXH73vFxu3WzMHBks8MTNA11gtob3JSv
        nyMq38p9pM/KcpAO71iE81jfTgIhfaes3ricNn3p/nGgVZZNc4Cx7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T12:12:24Z"
  mac: ENC[AES256_GCM,data:G0Dknpz86T2w+XiM+sIHH1XdBF/AEfEGBtx0A7OrOT5jRCR7xIWrKubyQDDpQyQ/KErHmyFalrP6B667xzx7VkWr9S6EBPF3PxJMau4Z631n2eu/vzqfL5sfxHwNG9EmBAAlqni9JNa0WCmFGVck8NhM5N4ltxJAZzRKYlvZxrw=,iv:o9bM/U0RlNSgZVVm5sQI413lzhVD8iJjuKESqrFVC4c=,tag:j2Pd/13CRJ58kVL3DnFWrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
