apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:kPR/SEeiQMduKpto8ZJ6GVJ1h1BSL+hAE+A6n+U5Q606DXbvDLPrUg==,iv:Hv2092hXbhPME7xdMyaInx8LO31NiNJcOTVXwZud134=,tag:WxWuWmZfmuZ4rPTGh1j61A==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRjBydG85Z0drRVJWd2pY
        ek1tQjZhWVd0NUlxWkxDUzBnbzVCQlowSlI4ClZUVHR5MXlZN2w4MGxzSUJUUlVh
        VWdSbHpTSHJ2OWlORklUNmZMR3V1TUEKLS0tIG5FbjBPWE9pOUVJOXFGaEdDL3dP
        UTd4WDRoWjk5TTV3YlZrRlFXbzlLUmsK48VmIo8xkW88ItkFE27hzsShlJ+nazBK
        ObmO6Vps3Hc7cDVyaZ+7o1xM02NE/OQeqZFkJ9Lf4btHdYm9OXAzXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T15:14:10Z"
  mac: ENC[AES256_GCM,data:QEIfg/iaj6OzDoUjcJFkK/TtnGMK3wU3tTEW/hv1ubKM7hCnXInKNyxORLylw6Vd9Ql5PzyRsmV8DMhBZtZqIoYotbJPJo4IUKpAqr3IxhmnbYD3M93CJ12qSY2SYU/6bxAsazCPC8wF2OQvzcq+X3QWUd5YzIXUb7QopndMEYI=,iv:EzS/vplzRJ9rn3pf1yyLUuXgzEFFrTBbGGr1790bAn0=,tag:7gaMJkw3Hr1PtrPXceWBxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
