apiVersion: v1
kind: Secret
metadata:
  name: obsidian-couchdb-secret
type: Opaque
stringData:
  couchdb-user: ENC[AES256_GCM,data:qq9On9iF,iv:VAstERQ8fVJ5twggJmw0K9W9i3i33u6MOKqBospX4C0=,tag:91TyCV3ASTkploEev0SD2g==,type:str]
  couchdb-password: ENC[AES256_GCM,data:HJ/S/woNdmsA1BZDgMCpfboSR3k=,iv:hwVKJHAD+8AGk3HiX4eCE//RZEQBImMPlx+E1FfEvrw=,tag:BuLGx3a6aD+W0wzKyJmnvA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBra1p4ZytpM2EyTWxienVM
        TUZhdmJBVnR6WDdST0dBdUdqd3N5dXJnazJBCm05dlNYVGdHQkRBMUdRRFBnRUtZ
        bjdMbmk4RHY4aG5PaW5RWE53TTZyaEEKLS0tIGZNVXIrdXpueWdJVVJ2eVJrRWtJ
        UzdSQ2srcGgvME1PaEs0K2c2ODAwRDgKFJmQrsPSJalbTYyIuucr1bIGUNUc6LoY
        6rqrxNZtgSbN/IgRbh2NLEdEZwJIr2qRQtnIM5kW4Ze15CqMRNqBDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T16:31:04Z"
  mac: ENC[AES256_GCM,data:ZXnE6M/Ug5AMn/wUHxShN/KDt1kjycPeYwP4ah4i5lZF6StRSGtNc1qhVcVjk8B0vAusFrqXRQvhSJDJCEQBWG5Z4Y788fCa94RN2etW8kHWoFPhyjCQUNVHkNAfmoLN+5ctXK+T8bu0Zh7N4FpiWBvjTIiF1G/ey7GiUUMVr+8=,iv:IDr/Asauip4fk89137ebcg9GydyVIGebhi4BCKyQ0ZY=,tag:tTGm9/XyAjZt7y/SLCIx2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
