apiVersion: v1
kind: Secret
metadata:
  name: obsidian-couchdb-secret
type: Opaque
stringData:
  couchdb-user: ENC[AES256_GCM,data:ZfcR/TID,iv:hzy4OoKcl9y82ANv6dzOC88PqW4ppZF1c8OK6cObGhU=,tag:v10nRYpCAK9MRznZri8dvw==,type:str]
  couchdb-password: ENC[AES256_GCM,data:PZc/4zFCAiK6IqRuF48zpCDvhmw=,iv:t62vVCjRrOzTej6NZSuL3SppnE4eYs9BrCnWufqgWXw=,tag:Lmq39+iZB4kSmTzEUNmLqw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBenZrT0ZOemxCUmNjblVO
        V1kzSm41Mm4rVlNQZkI0bWZTOWY5UGhDTUhNCmgyWWRtRnFDWHpjSks0NVFkYnV0
        Z2ovTzRFRTI4aEJ5dmlpd1IxV3c5WlUKLS0tIFVTTC9kMTRDU0NhVUJqeTdtNHRs
        ZHhPNkt4ODFVR2F1MG5IZTZDZGQvTzQK/VsqFkgu2Eq2+hC792sLmr4E9gGmnlvu
        tIMWwS9TauR7U0/rOylkprDQFhaawf4adrrRYNfC9fS5UH6vnBq/Tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T04:31:44Z"
  mac: ENC[AES256_GCM,data:jfizF4vO65v+DvYY3guaNlkTjI1YMo8ZMn5OZCe0TM4U1f+XCKYmbNlN2ZJrO4VnPe6aS1lp1k2NH2envoTgHkXXxlPY9LVRtNjimFIq5zei+231qn5xEkv0hzJvh9YNlJd2vJCqFIebqMu66W8hOU3wjtE8hvZVioWhJCqcoU0=,iv:DTyI9GYjgEUHMt+w9bLCiozm8JPBKdOejPmvmSn7cRo=,tag:/dcO8dA9fjUnCB6X8fJKqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
