apiVersion: v1
kind: Secret
metadata:
  name: obsidian-couchdb-secret
type: Opaque
stringData:
  couchdb-user: ENC[AES256_GCM,data:NauezV3D,iv:pU2GETaSlLgpN2aA3F9B1HwzsXj4R0RPzMb3NxLkVlw=,tag:BjN3dZdG+Uqe0efJ2sOslA==,type:str]
  couchdb-password: ENC[AES256_GCM,data:ocImcP7DiHz6P6VytHYXQ5uajoo=,iv:rbV5HynInt+FCvblFVIufoaK3WWzxKOx3etm5pvOEpg=,tag:EyNEaNgJ1IVmm+wYOc5wEQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z1JlcXpIMkV1TDdhVXF1
        MnlPTFFMdm1INnIrcXI0RmlrNzJNK1g5VHhRCk0xL2YzNjdWcjZCYnFQVWF6SUhI
        ZnIvT1VKSVZaN3ZLZTZ0dG0xQWNsTEUKLS0tIENBajhvNDhUeHEybWJQZU5hWDJi
        R0JvanNXU2lOV1gzcUpqQ2pUTFpqS1EKFtMNwyJ4Hp5C6Mh5z3T78IJcjR923I6I
        P7cXusojNFhbeyIVquyTkF+7Pi7yi/lJfy0E4tLS5XoMTVz1W24/pg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T13:38:06Z"
  mac: ENC[AES256_GCM,data:oD54FgGUIeQMK3Xnzon+ACwXtYwhAKoKrlmwW4U/jdSgWYUxsI29Cbzgrds8bjhXvAMsK2wNcH8rIGPsa+RmUXKXbiANAJh/y3JwKLpTzjWlw39vZI9K8wdcb6OqojiPginN8tYzLHoiZFLoXZraDD/pfwLlwGAYO4Jg3psDnuc=,iv:uvRr0dmdg8Sulz8MLDoMUcrLOJQrUTSUn3dCVPLjQp4=,tag:xVWji9GggvnlyUDw5jtEXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
