---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.32.1.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.32.1.10"
  - "k8s.fiqriha.kim"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-0"
    ipAddress: "10.32.1.51"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/e5c9417d53d41b92c56a1489be3541419036a80eb452d18e9794793a0da87ef9
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b4:2e:99:42:5b:e3"
        dhcp: false
        addresses:
          - "10.32.1.51/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.32.1.1"
        mtu: 1500
        vip:
          ip: "10.32.1.10"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

