---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "4398046511104"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: minio
    namespace: storage
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: k8s-0-library
    volumeHandle: backups
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zfs-k8s-0-library
  volumeMode: Filesystem
