apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:7aL3KMSkJV4teU24cPk8hJp5,iv:/2G0u1eGsXmvGbDrbMi0aujIFsx5wFgJhgviEMX2ovg=,tag:6mM9iMJOD6qOAFtWxlmdyQ==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:4gMOeCODPqbfX0M=,iv:i9RSiElbKFUDtdGP60eSPSv4GLsEu7xinI45Nci9d10=,tag:+G4iM8zpvuAsWhj74Q/e8g==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bHVwekczanYzRXAxRlhj
        M2ROczNVVm1kdzkrNCswbHF5dnBnWUZ0ajFRCjFraXhiQ28zMkREU1lGK2JlaFhi
        ZDVLS21wVlc2bUw5WVBUam5YOEhzMVkKLS0tIHZ1QUFGN3dySUVpQWRzUmJ1eWM2
        MzBLcE5FTDJldTdTZWZpVS93S2QydTQKTRFZ85szkMchjtnYd3cjpUTOB6ZR1m62
        fFMKCcbdaqYfavxAGTSsXgQ0Wukka+00hqTj+dbeuvywSPTjwYYxOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T16:53:21Z"
  mac: ENC[AES256_GCM,data:IpSCjeLm3o5uM5epze0Ajny2zilRx26p6aqYDt4xeQoeeACnrdUtVQccCWnZdRFr0z9q6TQ6VvkEk4yy0YVGCrgSSkcqRBZFdQjU/xl/3Bz1RvPMO+HA2sJisoUAsNOLxqeBvSz8IfOPHLWRZnAtCnYFaQabeDKrse4mE02KYqo=,iv:L9o07d/xvaexE6e5LAuMS3jqXc69pcw3elTGLzC04QA=,tag:BeH4wR+214EXk1cE1Eh2wA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
