apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:i3zhstV8as7C8oxjSogVKYp/,iv:iGgtd1iDWqpLPSUMc9Dw7Pua1t9MPUrhUYuyw78J2cU=,tag:5S3r8l6IwwykEunTGivrjA==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:kWtLCC9DGt80TDk=,iv:P8g/bxkfY6BsS6dgh1IUpsIMrWXMadW6Iy0qNQWWII4=,tag:s4b4GEucqCaDk7HgKW9IVw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOGFDSW5zRG1EMmhxeGg1
        MWRNT2JRK3pzTitlUWc0eGJuMVBLU0lVU1IwClhKblJFd29uTnphNDZ6cXN0LzhK
        SnVyMktEazdxcWdiUmtXUnZDVTdiSzgKLS0tIG9nOHZVU3FnclB2b2V3UDRWMWk1
        dUwwZ25CTUEyMXlqSmJVZndlZzl4ZXMKxRCHmow6m8t9iYPUYzKV7HliJcI2P+LF
        iHKV0w9yIGXOo4cbH5VHCje2RChKzcobtJnV32LKmAaDuHvmSzqkrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T15:09:52Z"
  mac: ENC[AES256_GCM,data:Mgm5jj9kK9ZsQeQ1fOEFMLImhaAICmuWgQyxssKpmarRjwfGjL7gv5uZphYoKZSHKtxi02l0fuAJlFCzKaaFYbLn64qxm4lDyzjKeWcMmrvYJLC0KWHsNRra22VP+v/mhJTRNFxVwHMfvv6sEqtIo22DcwBUdMJ531eWe3nVdWo=,iv:vhxMpCMM0FvC9yCJOciwZTQtzpFPA8Y+RaxGP6k3D7I=,tag:1w/KNtvasTxJxHPpOibaTQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
