apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:hHzeLbjAhQCdiQHnnY5B3BAC,iv:Mm1NL0sMPkedzL/z8HNqT3oWwoF5jVQ0ff9StKh5vjw=,tag:fVBApTR/E8HhA2/+SBkrXw==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:7SzyffR+4EroC78=,iv:rF4XXrEUspp4iEBi1HCxycSTVgMzSzorUAOfMDqnQfw=,tag:1dMxmy3XUbCiMWtDomoj9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTFRDU0lkbjJMd25mQkEy
        OHE1STF2aCtmL2hMdkNicVFpY0F6V2x5NVVZCkFRWldNcld5Q3gvdGFnaVByUGFi
        UEsxRzBCNHZDOGsrWDhZWDlVMWJuck0KLS0tIHV3N1NmWXZPVFBuUDVuRTZtOU4y
        WkRQNkhuVUM2cjh3WWVDZXVIWGc4UUEK32WGLGHlj4lo77OrM0zp7S5T1sfK38dl
        Zn1cPNsDo61nWLp/s73sl6kWbYweBE8Z2jPKIs6t4yTPOgNoK5l+wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T14:36:51Z"
  mac: ENC[AES256_GCM,data:6KIMPY9sqmNWU6cPhe3DPrlA2IXxEawMyb3wImUBEXPTR3ILAgtOLWEY9GZ6B0xvAMgbexcU5K6WdDtfRe/K9GKAUI6DY9k9batNw+OcqpUg30LR/Xy0Hyy/WU2a0kmJ/GGWpjNTxvXBxxjb4osCBug1Mn0z/uc6EMAqPRrscFE=,iv:CznElrGVzUdIYnoZi3tGycnQsgG4oGlPVDFQI8mS7J0=,tag:S3cDesBYnuicoyDkg3NxBw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
