apiVersion: v1
kind: Secret
metadata:
  name: hermes-secret
type: Opaque
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:/kjs4tp/t/WiN+WMaiHcy6gjJOBoP6Fl58Mhld08asy6jhZ0DElsM/5D06sjzE+sYoaydvBMbFPIWbe610kU5A==,iv:kZu6fXKN0rAXnZtSjyqKa7lvvrdoZVhe8yefgD/nDaw=,tag:obYHVuATRtPqRanOKm648g==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:b0Z+Nb7j,iv:wgm8UlvmyzzQ8UQTrjLNdd3YjmTqoVSMiaEOSm8Qy1w=,tag:PA+k6s4/ovX0DzrWAVc+DQ==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:piixGUawKW2MnAPn1vcdC5yosVRSbNt3OyhhdkHlD2UUCaRVTEfLQrs=,iv:15LcFDkmJZWLugxvXajVijVrismVmq9e8sqGk1meUO4=,tag:1WDtUUjM2/Vrc62CHaQ8nA==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_SECRET: ""
  #ENC[AES256_GCM,data:Ui2ZXwAgr5D3YUK40g==,iv:3wEDkqlElVL8KiRUC5r8+X4xfVmE3qSe3eq7fj+rueE=,tag:2IiKyD8EDY3eCDEld+RsWA==,type:comment]
  HASS_TOKEN: ENC[AES256_GCM,data:+nMo7d7lIx7DAnED9bkmUX8tmfXxMendlXf6PxMFwgt6t30GyR/ZDQKzf15tyl0v1/SKO66jxfZX8ubRrsd7i/csaOhyGEY/4PdHAF8Oq8eYzWpoqPSBQLa8KSCVs1br5eIoRY8DB0oyQO3A8M6/RTd1hDJPub5vK/ATQr5BzuMl0R+b1dE6Pg+853Nd2+9MS3lpCSpHUCV8e6PFMADp6Khgm+R6fhrrn7qAOCFfmj3/ikGJY1sU,iv:+rjJBSCiRd7GM0JK4fzquFfnp69fLDNJEC5H5q4S0sw=,tag:eKvQEgB1CKBoRuuDbOst3Q==,type:str]
  HASS_URL: ENC[AES256_GCM,data:VIiyqmi406VsPlNlUFWyA3S46pkxTA9Y+wOxjxLhKMeWAnNuIJ9ARO4QkMCViC23Ybf5DQ==,iv:U0/2F+FovcSfxCyzYpTz34iAxgXZ/11CCf7QdjiyFpU=,tag:VSldM4BrTgz2qakcDNZPvA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TVFnSmVPTlBybldYbGxJ
        ZVlQdTlsRnRTSEdHdU9aWjhzaWZ6UkNJQ1F3CjRTdFdVMTNLclNabHFBYS9VUGlH
        VDE2NEZoeTBuNm5JMFNTdDVQbWhRU1kKLS0tIHE5ZGhtUG40ZGFPMkhHeHNhUUhp
        TkxUejNTSTNPSFhFMFFYWkxJS1J2VncKQZYitV9jbVhX2HCawM1tZCN3ZBqTgp/3
        x1ayZ3gAjkauTkU36Kf7LeElBdc1n3gOUtEZoEd5hFfY8ixZdi4T0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T15:47:37Z"
  mac: ENC[AES256_GCM,data:3coZRQgQj/glDqgb/MptdfDohYlspWRpOmUoR08jAJDWNkT+IbP/MLH24YrgODUm0S1hTwWDGPuyFjWB6mdNGUTbV0VQhe80QAjRDpCovCBJLaviZMjn90XTlVzDPNbq4cWSTo9aOe5btq8+TFSh0cfVlWEicIAR7+myGAwX6I4=,iv:/GDH52NLqCAANA0TiLO3B/PjOmLYNqgjPti7n15312o=,tag:KlSdXGN77GWYC/QLiAYZ2g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
