apiVersion: v1
kind: Secret
metadata:
  name: hermes-secret
type: Opaque
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:/HUSQAwgwOyskiANw+U+QyARnxRnvMQiLlWaz9e4RDjfy5oPRrv3sFnAyB/Xlz7OwrDTkjZOj1ezgyBMW2l62w==,iv:v/06RzLpR+bVcDFFPrW1jSxt9PKO0Kn/gy08v23yb5s=,tag:YbLifDH/dBABrsMV2Eng1A==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:WFb+rz6+,iv:jMcrjyRs3qSgzl1CCZ1/Afb8ze9qN/rO0haeSbTsGnM=,tag:W+4Z8ku7SCrh9dmuDqlB1Q==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:EndIOWyFeMuV68UC/ALKQ59YfLkVn3FE52ikP249zpP3pZFHoCPdI+0=,iv:IRIQcE0nRPLXY/OWXisTz8FcvNYwnaU4LayGQPxJ/Nk=,tag:MTqhskv6NDekxb/IOccSCg==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_SECRET: ""
  #ENC[AES256_GCM,data:jPiekSOeuomopNeL7Q==,iv:43EFeiKhKHi8w1jIvjCfDbFGrgy1T6ySV1iCm8H56pg=,tag:kwj1vXwBjI+z7Pnlf53f+g==,type:comment]
  HASS_TOKEN: ENC[AES256_GCM,data:DRR3CLNo1kKpAVu+7+2JwZehVdPhUt4I2Z2KKbOZhq/3cenywyb8vuzUMXGLbyiRNnOjDiMczhkp1i9FGbVQpjaHJafvgqFrOAjwR1zCGCmXL0I1ttOX2cykcOEfE9+1hyED5R82zBSIVLOEId6GzPtwy3QHnzoREREZcclJo4+norNDmOuhKIks/elfH1NsR2qasUc/aNulyf1MiV/GifSwnBGSbdqcQ4Rk2Nq1WOx6qE3DePpS,iv:kaZiHpx3Q/JZ5iwkQqlv4TJqKI9pNL6GcXZvvF2+lsY=,tag:ZxgtGXGO7WlTGVg5PXIxDQ==,type:str]
  HASS_URL: ENC[AES256_GCM,data:FyRvZBLZSTNx3dTaht+o0Mo4h0Sn1NS5XlyBVnpbmpMzMK+UMyge4IKTNFT6x6vQ3JAU7g==,iv:0Qb+Sf27zJz3VV405HQkL0J5bdXWBoGKIM9N/64rZ4g=,tag:ZwRpMJyv0C04+yQf1rgmYw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeldzZnU4ZmIzczlyaTVn
        MFBWV2pYaEFjL1Y2cEkrQnE5ZnY4SzR6b0FNCkU3cXhUUXhTOWpnWHUweG1JU1Jk
        ck9iZmdHK25sTFdGWTJzK1ZYMFdBTDAKLS0tIG13OGlRWmxYRDNpYW4wMjlkcUta
        YkhiYi9RNWVLNnJ6TG9uWnR0M0o0ZjQKnZIIIx+SFEdMamMzx/bfbofpV4GUt5VN
        LdX3qmgsN3MEP23Q3/jHUPdp/XaxRhVajjHpblry03U5PxZ4L1B6xA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T12:34:00Z"
  mac: ENC[AES256_GCM,data:MYcZODV0mkM5eZE3HupfbJoD+vZ/krJnCpiYEz6t+E63+ZER0N47Xwut8W2I7IAsVHCcTf70RjcGATB1n0vvVRs3oCx0GoFRi8DzFq3y9Var95TYnNl+z5xRZwgGTBVDvfv+/aXREag+lAPEyx/zx8hucxYoZLH3ZwKwYGN7gyU=,iv:TTdEyx8EuGK6rkSIJW3D5ec3kJ++JcnC9MhK2LMio8k=,tag:mpWkI+mgcbFBXF/jKLT8Ew==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
