apiVersion: v1
kind: Secret
metadata:
  name: hermes-secret
  namespace: devops
type: Opaque
stringData:
  API_SERVER_KEY: ""
  HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:9Qmt2Pwl,iv:gfbbbfFyvo+N/AgFqpbOVMH87+P3bDcaeepJsb8/tsQ=,tag:HTsZeJwAkp4J5YgkmYTLkQ==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:PpGpQMT010N4zrtx3Fm5cGsrjqe04CLmPyXuegp4QjkzTmTZ3lT1rkg=,iv:ml+SyaKwAWNDAx3+smkpFVIlZzZuwy5caZVROXsZv+E=,tag:qWUcCbyNoBGqyFoKwQWQog==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_SECRET: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OGpuc3ZjRGtYbHBocmJD
        QUlIY2FJcUkzQTRueTFLZm9wZUpDR2R4QWc4CkkzbnZDOElESlcvQk5pZ1VVemhP
        RUFoL3pHbm9FNGRTemFEMVpkeW91MncKLS0tIDhHWjdGUFVYN2ZPbzlDZGhsVktK
        dmRST1dlYWVGQjErTGRCdzE0OEg0aVUK2q0kirLL0fBhjUslPlSFAEByxOE2Hw4J
        sXlTaoIACARV0vyy4L30TlBcfn+VHp29J/RyY1XR/ce0YOH+WivReg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T15:07:56Z"
  mac: ENC[AES256_GCM,data:9W0FTeMH264121VIBdImC2s3Q3qujcSF8KeBO86qqLx9VUjTcYT/aTE9B2zELKVujcfFz3gKTsJxSnUjEwJNsstpofqw2uvCOMlsr3fIni38t+GiPAzg1jfvFPm9qwnPByjlN/M9o/NbXdrFeofPshEvaCj2N7S7Tbv9jSXCChM=,iv:ZSBiQF6IFZPuoy773R2MFvNVTuM5gMCXt1vNJN7bnmI=,tag:IErP5LIaRkiW/TLCQOPEgQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
