apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  labels:
    cnpg.io/reload: "true"
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:Dv7loLUaTyt2544CKJt78KGNhAY=,iv:il4XIegAnr4xyOnWVBxgg8PEGru8WuVuGUTRQVSNXfk=,tag:OkeHJp2RTAR+ssf1U0PfhQ==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:IzuXaoxiTUb1gEXPWDP/cBVPSGwx02S/g6KvxGP/1+MHA7FHzQ45lw==,iv:P61OXha9gtalxvVnPRyKCzPSzNW6i+hc4FYRuGI5084=,tag:iVKX3hz31J3EN/a29++yhQ==,type:str]
  username: ENC[AES256_GCM,data:LF3YXMLRA5Q=,iv:/3ytocUAvEatS+GySPjAtxsac72o6yiq8wT27W2EcZQ=,tag:LPl+SOF7s1yvl2cXkSmblw==,type:str]
  password: ENC[AES256_GCM,data:JUb3Tr8fbEKez8k=,iv:EAOfKa/MvzI09Uc60aVaJt1Z71cGjDXq0+eZ8tlYymg=,tag:35GOhJfd1nWnkQCIzAuyuw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadFI4dktYalBCNjFMcGEy
        RnpSSGZVSjV4ajkwTDh3TnZ6ejFJWXJrM2tBCkxNMHY5Y2hXOU05M0U0K2hqRDB1
        ckNGVXBuM0ZNTENabXdXR0tXbjlsb2MKLS0tIGZqKy9uUUtuVGlTWFNpVWNHV1kx
        aEo1KzJZN3JpeENrRlJRSXhOcVMva2sK75hViL0R8ZzKNJXCeMNzJxszxa1ZW8C7
        AgPJYJMWgWHf4mgSNByJHoURtC+3JcinP6kO1+Kc0OjS2SCZYiWcGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T16:39:36Z"
  mac: ENC[AES256_GCM,data:SRcKB5PoD9D/ffRzAMTUhVzFKWp8AyE5QKvA8/DJDqo4M4IN6oC32QIBAekWQoPouSxdQ9BwtM6SGnQMV+0H/23kdjWAp5ORUDQVr3TVUOXn4IzimFbcehjVm8IVonb358ITg38jxPhcve4Gx2y4e5b7wnCr9VcPh5kKxjz+VhE=,iv:PlSeVi8CYhRzNpUkRNtSHvLayfAwIru/FlXADkp6hA8=,tag:SM4lD/7Tyqi/vCeKahNj8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
