apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  labels:
    cnpg.io/reload: "true"
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:fe9Ce6SDtj2OTD4fkN+YwZG66m8=,iv:4M+o6kgq9rHUjUUJONlKNsk5xpBrbefhrB4YQdDn6gI=,tag:z4PPseEL/oLV0a/W3AL32Q==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:TnDET6q5/cpIS6+U+ow0gK83srvUZFzhn6Xy0DRhlamrqOIFxQMdFg==,iv:JEK9lpLXRcUQpmrGF24xZWMdxGIkPobjt6Bb2SFnSD0=,tag:F3uDzb6T8OWLWLOd5x/EmQ==,type:str]
  username: ENC[AES256_GCM,data:dpTfehN+qn8=,iv:t7kjJ9lKe7JBh2z5VLlEff95hNF4zDRnn4cIaEnLW1s=,tag:Ymgpg0JoD8Pk/K3oLANDQA==,type:str]
  password: ENC[AES256_GCM,data:CuGCYeFRTaq/g7c=,iv:PORwboBSZ6yZmwNBJwxrwehDhW5qbrMyavyRwOguC7U=,tag:7Vs83HmY8ok7+d826H+3iA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K0tEY283YWF2SFAwSUlI
        SGZWNVVwcmsxdkNWdjVFYTlKZVUvQlY3YjNZCnl0RUR5Rkg2TEhQdno2VUdZaCtl
        ZWdtYU1qUjVZaXY2WU1tSHZ2S2QraFUKLS0tIHZ5SEI0MDBjS3NXMVhCcDIwUXdR
        WGkrbzR5RitiZjdtdWxpVEtzQmZEVG8Ke2E/UaMWJxpTY1eZhFR+4VPVWhqXCEgK
        gz0ajf8CXqkR7r8g31FJVPf3Wc3cT7kIe0WR0d9yX17NrzpzztRDQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T12:37:29Z"
  mac: ENC[AES256_GCM,data:LYxonMXOvb0h+p+SXTmk4FqwbEjtQSR2VRbYksZkmYcDGP9gAkhEuUDmWQQ9t4qVnwrCLHnbze4N+A31woRFVsTQ0qRKRp52xPn//4+HlkUzDCo+rTG39GXM6jEdV5469cqDSClVmdJYOANQxGchce8Pw3ISm6+WjGH6k6XHTrU=,iv:L602dCgze3EGcsKJvDqYEN2aRtC1WgajzuIqNjDwxqs=,tag:WDaneco+n3ITbJMQ3RLHDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
