apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  labels:
    cnpg.io/reload: "true"
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:XoRmox7NvoinaEqbGfWRTUU5py4=,iv:OHWJAL63c3El9GNzcR+CdBqSppTYJd+kU7OdO2FpTbs=,tag:Ckt1mspYuuJVDvlNeaCN6g==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:vFF5Ib9GkqOHviinK2DGW0Gbi2YCj66pOHxwTBbQ3t+YvnLeIrKmpg==,iv:8AFUm5LXERKBwQW2VZn/FGexsfzd5C2Q07MEOmjZs9s=,tag:TahX+DqyRsMT6sEUSDZvaQ==,type:str]
  username: ENC[AES256_GCM,data:q8KMQjiIuSk=,iv:boXgSisYJQ3np84VqO60I3cbc3qDz841hB3a4zNq6FA=,tag:CExEgDxSAe7khQfTcxqgSA==,type:str]
  password: ENC[AES256_GCM,data:KM9nveNn5hOLx1g=,iv:N6zd74cZVfLQSX/8fameLFCNpVkIBYVb7A7eXjG7Ugk=,tag:Gops8jOamwJP8lff7QBGMw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aiszcUJGY0Q2ZW5zZkl0
        allLN1A4RkRsYmZjbDh4YzRxTWN3VlpCL0c4CjYyOStma3R0dEd0S21ua2w2Wmcz
        Z1ZlWTlnU1hoZlVJYkE3VzR4L0F0em8KLS0tIFdrUENiVTBFOWltQTZSaXFZSFNm
        SVpZN1V0QUZVSmYyVGpTbS91UEcwRDAKmigrnmjyoOL+Bd0ZJBBao2lxm0GXSoaK
        lkvZAjpMh80dvj1jWx83Qa7Z3MjmUxMuG2t3GU8deFs1ghH2uFzoMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T15:43:54Z"
  mac: ENC[AES256_GCM,data:ppZiMx2F3gHgxYuSB8/BcJxmoOnDsNEjPtLk+M/tH6459ADlZFruOp6ocqFNm58R43IyDGhOMgxoLbEcg1V4XgHqZ8BpNgOBMUtblvh6SAEu9vTJkgo4uo/pB0rgdX9XXRfiopgYfqqQSPKyGpnbhpVGLIf3rn+F4tIyD0Y9T+A=,iv:ucQPTw3015eeojDQlEkIR6jlX4iuvTdCIXo/VSulLds=,tag:u3yeejkda4YVxYw8VSdJYw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
