apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:x9DmisD9,iv:oN0ZzEJ75B3zIX28PmCfgesFcPPGb5dnhZq07nRlccU=,tag:elruv9lViFUX41wlCw7S9Q==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:6bHsHpGmJzljXCRn77MDk6f6de4RTuhvvWVakmmsurA=,iv:F5vudNhuVw7oXj8wg1pFWuHjyTkBm309nrb9dwTzuqM=,tag:V0fehr4UpMDRD4x4v2+2Lg==,type:str]
  #ENC[AES256_GCM,data:cjq9JKO7t+TNCDMllhi5DuWW09PcdA==,iv:Ac5i6sf1oetnaPaxSRRPo+U209xQwAsjXuvcP4HWt18=,tag:D4eZJ/y0k+ufFSZ7ZYdoKQ==,type:comment]
  #ENC[AES256_GCM,data:Mewa0fSsGTpJ32yqUVzIyNMPSGdrnaEFwnvWCA==,iv:p/5DoPI3XeXI41Po0Ki2nee+STD6I4WfEqXP7X/zTDU=,tag:XENudmmfrptSvINL1OS5Rw==,type:comment]
  #ENC[AES256_GCM,data:UtWr5g8FsveGghWnd2qCueNy8T32LMDgL9/9W/uwibY=,iv:ccPEducJdAu7QupeqR7RlNnyt6uXSmBJtiBDXT0VrcA=,tag:jB00ZcKVOfD9txiv45o9Og==,type:comment]
  #ENC[AES256_GCM,data:Hwz/8cq0hca/5fypE4mC9sopEB8c5K7CNpwJRRJFnIathHDT+0MIspdnGwtLRdC44RVk,iv:jlyKK83muSK9qweTMANir/NcroRF9F6qvA57L3qNyQM=,tag:FS0aHKR0kuh0XuiP9tnqLQ==,type:comment]
  #ENC[AES256_GCM,data:CGexXNCWupVV1Oa8HE5UPCWe36kWGiaOvqSu1fh/3g==,iv:TUn7kCHTcGYSURx0gmByxdL/jUAgb1UBvzGYR8WJH+U=,tag:9IHlylp2ncr/coF4EP5WEA==,type:comment]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N1MweWRXNVZXTVpqVnFG
        Qlo3WHpCTTU2SXFBV1JpYlZPVEJpSGxCUEJzCjM2aXJJM1IzK1JpNWY5bDNKd0lW
        Q2M1dHovK0J2Z2cwbGprRjUxT2luT2cKLS0tIGlQNEFXUnI1RndoM28valFGbmYv
        bnUvZWlFMGpRV3M1MWtDOVpYbzNaRlEKEhkQLoOtJMIgIDdOhu1WXy4uW1ERvtqQ
        gL5EEHXC+zX+Ltc8Hl/XDj6XANN4ectU27sCyGia+QtdySHTgjvvFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:59:36Z"
  mac: ENC[AES256_GCM,data:xgafcqQxY5PlagGs1VUk+PM6KYDTvdVhhD1H+q53cbKJqd90OtFHXZI8Q1az+PKW12sf1jxI/ougLXe2CyE3Re5FLz8Md23h3WslSYXzc30cOYIWEFnq02apsenBBJZ4aGsEhuT4YGdaMpzQNEPZPByvAaNH1rbnSvkGVUr/Opo=,iv:8Hf6wdioZHL9DhiJOWcXTxayg7weUw6vHGeYs+s9lv4=,tag:TusZeHHchg14XWYyROCNdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
