apiVersion: v1
kind: Secret
metadata:
  name: paperless
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:TfadP5FN8JOJ,iv:SQzTiRIizEEcXloVJLfKDpoNlyWpv47w0L+xak9Ri2k=,tag:A3zkHC69MfIxgoS2Eyscmg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:USVixhdXspl8mIZgfg8JppA6i/VD91UyIhPdiNHZnUk0lU1zR1Q=,iv:ITE5DWdWO2d7WoKUcsOlBCRr3B3tJ9drkCEJgCK1h58=,tag:nSV2O/O5IIUd+wl4KtDqTA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:TpzZYiPPbrE=,iv:OjwV3ooAt4dzkA4dFmAOgFQV+Nht/7m8jDnFhFFZRMY=,tag:vRDbpg05I6SUSJVYUyMUMw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:cV2oa0gUFCt3n+8=,iv:ou8rcD99+qE+DiePRzxDk/b2W8AK9J3QwDHU8tBl1Do=,tag:S5oHzW1IpTSIdId3lShNGA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0UcL+Td0rZxjXZc=,iv:UOvu/WOyrYfrVYmqqG9Y8JcILzL1NRI8oHZyCmh8OVQ=,tag:icZ6xPH95IBjicvu+Hk9Rg==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:ZQ5tIrUxrauspXI=,iv:AcGzThMOHBM9KL6UBDb0iY3Khe+AkgdT669mPQ6dmpU=,tag:osO7kOHnNxWkzeZxnRbnFg==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:bkOwAHJ0lD4=,iv:173jWMolpzYgU/wcquXeBYgTog7OBCtL99Y8sX8oPXg=,tag:3klV2H2zm0BjNKzHKVfRXA==,type:str]
  PAPERLESS_DBNAME: ENC[AES256_GCM,data:yUdrnX8/CM7x,iv:Bx/OIQiTzIHF3jzOKXGteRJU1T0gWk/hgcGcBlvT9GU=,tag:5v+PvfzdwIlnVU75hGlghg==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:Q4Wq20r3,iv:fBOo04N9iwWIgAlB1u8cLUF1go1g/hlz29yZym+78ao=,tag:sDK/WN7bIjfFBCtrCAIP6g==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:uuM44Q==,iv:uKCg5urwgUPb/u6uFmCATrR1InR2UDphSlmRo6dHAHw=,tag:Gx5NcxCoA0GcsfJkU5j5Cw==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:WRrpI1kRGvCrghpGUCfAnBLU7nmXOL9V4iHAxkIdpqs=,iv:k1XNsDqaqSC7le2UWFv4p7d2JDmf8Ygr4JLvXzV4TRY=,tag:8SsnVllyjqUbarQMmfhqzQ==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:CdjkbiGH0qI+cSNB4oofgDNx7Wk8SLSTIXr8mJiHdZoVO/7b2OmmTiKkI/AyiUcOry2aj1zD30c9LJDi3/6O45AZo1wOUXln5dzr3sVkRNppyntuvJXlrsTV4FfgMg2Y/SQulAiABQKUzGMnOtNNVUWrWc84DfJ+7pBBZYb2SyUar2b1KLEQMKlK3jxKn+iIjNolcY7eRYoOeID5CshMy2h6nesmaRw9r3jEgJzWEiq0fryhL+585IIVJXuMHZL/yCPpf2q/ngz99YU0LHmzpNCyZj0euCheaYSJTJjPJcwnGOjDRjKbZLit2f0EO2zsGOY8quZgKKWwTHbr5e224Qhdft+7V0KNXEsheJxO/R1mmTbFU1LQtU4tIyh03KelesGcdCfXMp/Tr2izG8pLU5AHymqpZOE0AZHStDySqJOMYbHuSVb8UN/k8N6uzrDAGm0uM6qlqycbG4p/7mIPunVVHZSBpFcD8/l94bw/SxV9A6B6uXifrSyIuE5ZM0PX0m4WZ2dJg6sM6wiG5sirNCFtcUldoDSPQ6u81ZzzV3H+hE0io9mytnx/xqks7ekizojWvtl/oohWo7V+/4F8yXS31ksmail2nAQxFT6920e5Exepk3A6ya2Ycj4y2amgDTiXfcZ5,iv:0H0NfaD0+CzgAxHkq5IdAJmK0+suapjmaJA6hVI9shw=,tag:vUd7DgndbMY4lDnMU/w0Vg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUUU2cG5UZU5wM21qWHNx
        elkwNVdTNi9YbHlNUFBCaXkzMTNrZTRnZ0RnCjUzdUNFNkltR083SUd6bjJMNmls
        YzQ5dEwyNFY5NjNkKzg3NEwrRXBpbzgKLS0tIDBSRzl6dThWNXlzNGhwU0IxZlJB
        Vlh4d01RWnNaL3dkRVBLVFRiNUZETVEKhqUVArxW4JxpmhhDauVs5ryWPdhMrFgY
        Uw5TbnhL/34mFp9WxOH9DMDbw6WDRE8ukYnZaXrwyYsGMU/kEPzKjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T14:45:41Z"
  mac: ENC[AES256_GCM,data:Sv6Ya5Hgj7g/khL0JQMer0N7z93I/EZjNIM2cayhjJrhCcbkPS1TekUgTgQlSqjhq5aevtFz9E51agroMxLyawb/Bhq52is4QyxU/9JCoPhTyRPPyojZKnAhOA/x5DH/4q9YYTvugvGZKpqvsG6g80bNOxDsteFR7bnqKcNMVgk=,iv:mIIb1VBDsIjCOdma1A4wrIeMWG7nnIAmbi0fFZKeJgA=,tag:W1OlyIakW9xikCc0WVFNrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
