apiVersion: v1
kind: Secret
metadata:
  name: paperless
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:fmOBG3/3KxTb,iv:CtpFJY7XEdDqOGtnRkePZxZ1ChEYw3bHljaw1rG6w0k=,tag:LCW27JCQ/PkwBGem3HWz9A==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:rXHi2dwUUk9T2/Okw/Wviy+QbHfe9oTd+Bn2H+fZ53FcE73MDGc=,iv:ObaLjsbt+TtmJAB72+0cPfNHYvD1tyCOce7b0jvlQVc=,tag:0evy5y+Z+Wh2Hb5IN1Hxzw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:VcgrDhhWGsE=,iv:TLqRZ6AXDISXBoAAbMh7UxmP9rsQ/r3rutZVmV5brAc=,tag:3JJfH/dnLgBHoav/8DOH9w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjDzSANKGqteTVU=,iv:tauwNDwvJV1SBEozL3atPruBoXeEiXk7k3M7uLRbxnA=,tag:R55DPxd4kJdP++dCUmyqPg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:C+Ac5YLWaitlk5A=,iv:oKgilGMdQpzfAkiELh9FFzDG8WQK6Wsa6OFx89qeu8Y=,tag:EvQiBPFtAm2RZXQsGl567A==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:WfE67SJVp3d4fWs=,iv:MWZo+x3YyxCdyTPSqg75DJA5rPpNBxYM9Uooe+iJ8+M=,tag:VTFqh5grySV2wse3/eHEsA==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:iGXebgRDFUw=,iv:oPWwnWmdCKxUir+nUjBNFtXXIyIpHTIo5Rns7EwS0xQ=,tag:QSr0akbhZiM6reTxrHl2xQ==,type:str]
  PAPERLESS_DBNAME: ENC[AES256_GCM,data:g26nKmdTe3vn,iv:IYT4RSeZ8D86e6r66Qfk0l/da0WtsivUpobmtBO6B10=,tag:s3+lZ2YVbHXbGBQ1h0+pqQ==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:m2nhWF34,iv:qzncy/RrYBsLBRBTHUezN7exq9g6x3eMPwH6d9R5mMI=,tag:SmkEGDw3+EzM0tNOF67O3A==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:8qi8kA==,iv:gIe2W9VNVEskkQzXVVfrCah7/5gKEmukzeDK2r40Y2w=,tag:CeiPgEEjnuk08yGyiW28MA==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:g5QsVE8y5wc8OPHbR+i6EpyKdkdq6U7b/IYiER8hSrI=,iv:rjladOlQHhFVT3UEiXtZtAWqZYiXahzn+3sTjrQuePE=,tag:SOoC/squnAxvI4Bo7pOtzA==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:ClnjOMW9zpUZMsGjf0mcyjxsN7zkhGRqsOX8HdSEcPOEUxO3sCMP+eGKDzePRL23snFuiLsjlzFZghBTz/b53kbTN8agLJ39FuKH2oDzWT4SN9DDbTBVIzu0gRUdtDDVvtpDqNwDf7hqDRE2D3L5SEFPvJVI21bcSt8qSnKGVWVPBYCHbQIn1/k9iARLMEUW+ugebDKV32QA1PVi1a37DZAerigpgRXSp804XLf417uoVOF8jG5kbof6d6GS4RkrjxLwt2DmIa8cgzicZ9u693cUE6gtjyhI6c1rOGlfLbgBQoQVfJGDeP/qDWdV/+Gog/ZMuovyEBMQqMFCcC21q4svXes5sxaBJInP8gGT/yEx/sz0zKEO5p0WxS0YyHRcr75Vk4mP5zEgbOMmmJlw3KH4LZR64XKQ1l1AFI7Y2f2aZ8AmhVAiUanKipPjWKM4z6y5qySeHxWsiKAFF1Ff1KWGRUPI4FLM6wm9zfVdUD8tCRDSfn7WNmbt7Qx77HuWtW5xTjMdiYioBasXG4UkCiX02UW4vUiDQu7kp/XcZQ/hIiKUTfRPJfHYugncmIzzspQgC6fba61LbQo9cSHp2CPw+N3Df6CiiT0U5ogr23NWUFHEg07JtnzeN5DpiVFWYvhrSDRm,iv:dGZIT1UkcpZJD1zyftFUD0sake+tEBiuhcQTNpWAWK4=,tag:J5a92iHs+wq8D4o5vaAjlg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbHRDV1dubUlmb2xkT3px
        K1lZY1VsMmJ4Q1hBeVRNTlB4N1dXT3NGTkhJClZmNEdNYjBMSkxmYUQvemJZU0xy
        K3psUFBLQzFBS0g0NE9qT1RteE83UTAKLS0tIFNmVTh4aEZSZ1Z6a2s0NlRnU3o0
        aC9qZGZZT1RPM2NKaFhzNVZoRysxcnMKpUC2bPTqmCfuQVnsNNKa+eNSq+ME4p7i
        76yrKLDO8q7/wWq16gaz6MDHKZHh+vRP19e2Bx5RX/KObKEdPqj5GA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T05:22:03Z"
  mac: ENC[AES256_GCM,data:Li+EWbFkywQhisNm0aulHMRekys5Ozi5wKC+5mdwHmkIKC5I5/wV/68dfyIt8Lurm7F35RSdAnQHHz73jMX3MlfI5NacTwf3YWi+BIpUam2Jbp1bEbElhXLE0fjYQyEZMjj2keKie0M6nlvoVy+DeGTA+Hlnu1lEtqCaDg7QE7Y=,iv:kRz1Fpm7cnNjag+y1Lvd7uRPVbGBQp7d3ZOM/r8EuoU=,tag:Jfl31glRY8w+x/SU6qpwRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
