apiVersion: v1
kind: Secret
metadata:
  name: paperless
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:r1hCm+XhQ4ll,iv:2zjf84o3VTgEwYCIklqJEkv2tepbPaY3Acw2bvRqeOk=,tag:wOeII927+i6LTEilxwZzOw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:M/yylfSvuTe1Ybe2n74IKxdECkhqhbmgIIoDuqT0SGsdwViTaCg=,iv:76v9Gnc+coPzEO6Ohvx4EZ3Jx6+jFY6A6blfUXRXHuE=,tag:ZBGteXhuBgb06mQGum9TCA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:ygu85K4jP7E=,iv:xfy7BkND3dF5wg2iNDgrevRM7F8Q6uEEU0LriYinpSQ=,tag:bT/dT/azdppwBv4WI0G2zQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:/u6k2/UMRdMKqUo=,iv:67clT5fyGJhE6AKVmLdZzNPm8CNLaQPXQY8LgfGgib0=,tag:tpVHqW6h60Xx32n+HRkhvw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:R9pO7qpcaISOg/Y=,iv:U1Ju3uSJQsw1ogIVjZ4G9c1vwBs4PcGmiueb+x4I/ws=,tag:tHUCKUpvkWU+rWZSGGt9lA==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:I6H4vL3qfo8fL+0=,iv:TsGxJkz5cL87N34bQMPV4mFeYQvZsWdWfHXIab1w9RE=,tag:sBQit7GDOTod840um0EyUQ==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:9d7tJloMpoc=,iv:7oOXYCGhk36aYjuYFeYxExNZLZg7oTKCzHGTwc4VKeQ=,tag:5lT6zFLiZ0fwn/PX03+Htw==,type:str]
  PAPERLESS_DBNAME: ENC[AES256_GCM,data:nFLcSuSc4cwX,iv:kFueIkS0Y+AOZkiaw1XQ1TfooJJ/XtNs7qgHMcyO42I=,tag:Muxj6n3vhWC0ada1yvvlGw==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:rKx26+eL,iv:AkV9wXStAYELfaqz8C0zbBva5lDS6qTEJFnQiylu/Zc=,tag:wgI+sKCncYVdsNzWU3nD6A==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:pREFnw==,iv:ZCFj+WGf8AdTGN6I7w4BY3LtW2XY9+8V3XEy2qtPk6s=,tag:GJGh9fjsIN/9RTWV9HjEtw==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:CZj9dbE9Zuzpmae12Ypmb7vELoGdoue7ZQqBv3A7cuo=,iv:nfH2iuW6Vu6/BOMeZNLFs+In5ebqK5sS6MRqIye5srA=,tag:VVHFaWl1NM7w2dYggz3Jng==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:8T2oISwMO7DVp59JDcLcKXgpNx7k4uo6xnMogn+2/qBHE1SGx41NgbsZj2sNBD2PfDa0yYlpbKOx7GQrT4N9uMEqXCu8ZrAK1Ziw0AhvnTeIIygoAWVkDSiJfq7CHTiZxEMcrlnWBZ2GwOF1d+PNMoQrtgLTqTUeU9D0pu3JAM77Jleinw28Akx7u/jUEgPd0D/JHCFG9fMH2Lqz55QrOXy2Ycp8M+9mhKDT9jxSM2sXCW9w9XblLUaB0unNFxxqWwZORFFwI5o4G51LlQ/ZYK0ZriS5Lj9IiPTZT3KPYN1nYL2xDGA695cSz40BIUnq2I0WJ9XS2ycJRr6O9swk7DryMlCTvQKY650Wq4UkicFb8rPArdMZAe5xPUMMILixxy6aCbGqDpANt+q88s1lNi9lcGUT/nNNMt4FJgcss6p1BMUjoJ+hXTi1xishavYx5jvPdv/YWKQFF2+QZigw+qWYub3uHtFD9u82nbDQFu2T6eMFZXghbRduSXmjRiIJgyaSVo03Mr/Ijsw6rmQag/wqoyJvewsrc4kvNQatZbYvKEYTO2DxXtx4L51ZDomE1JN+j1mVRVgBUF0FO+3PKiDfohRjsUv7bahgi680F9+Lt40b6N7CcjtSllwm6i6PKgABPzYx,iv:Y6yixuSw6OfakSUXlkKPgLIsSpxBc+Y63tGNes7buAE=,tag:TVHGp3CvXVTAP00CTSa+1g==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ3RTRFJsZW5JcUI1aFF2
        TTc0c2FQbm9FMUhmOVA5cWdNam52c0dINUhZCnptRFp2ODcyMFpneHkwNWNDU2lM
        NnE5aUk3ODZWS2M1dWxvS0V1NWVjN0kKLS0tIEkvWGJCVENrNXdBT3dxcEh3MURy
        YkwwT0k2aHd2TFNURHFnUTVydTdvN2MKTJZQ/lHn0eRyqGMb4nTaQCjoYnm2ke/0
        Y4ENDRSoxZiy8VemilzDNSZqR1Bli+kkV2PtC4i0Q8XjvWNS3PBl4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T14:15:12Z"
  mac: ENC[AES256_GCM,data:vsUglXOpQo6X+8ZbXHBLXisbAlII0HX22JZRXUJLh45Dd1qvTC+gnytY9VsL6ycvs0T6XYail01hrrutWZeKclkIK6djkIkn9//RbB8bIEnss9UyTQ0063D1zMV4ohxWQyg49FO/YeqYTZ8c+c0+JjnoZxX/1jxet6lJbpocVMQ=,iv:z/klF87O/H1cek+0NauEDZr1Up/lWsBNoD8YwoU5GVQ=,tag:AQsZm2X/YZezCI3cpHhjhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
