# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app tdarr
# spec:
#   targetNamespace: media
#   path: ./kubernetes/apps/media/tdarr/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: true
#   components:
#     - ../../../../components/volsync
#   postBuild:
#     substituteFrom:
#       - name: cluster-secrets
#         kind: Secret
#     substitute:
#       APP: *app
#       APP_UID: "1000"
#       APP_GID: "1000"
#       # VOLSYNC_CAPACITY: 5Gi
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tdarr-node-cpu
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/tdarr/node-cpu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app tdarr-node
# spec:
  # targetNamespace: media
#   path: ./kubernetes/apps/media/tdarr/node
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: true
  # postBuild:
  #   substituteFrom:
  #     - name: cluster-secrets
  #       kind: Secret
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
