apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:jlB8bClt7YCLtkM5WYDY3wc=,iv:1dt5QoazO43QZGccVMSzisvyDPnp3ZvzsFA0lBcxCtY=,tag:6CtYI4GiIdiNaGPq51X0yw==,type:str]
  client_secret: ENC[AES256_GCM,data:YQ97lx/zmajig3OiErO/cCETMChVyWYFvkbWkWhS/d4ankNaloNHZ8TT/wFevhkKrni4kEu1CCD+EIqi+B9zQg==,iv:kJAt80hRqBbWjPUkZFZawVOjs0uS2Eyb+hDe7iwZDCM=,tag:ABV3ORgpkhpWEQ6t73ozmQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcGlEelRVazVuOFlmV0Z2
        dWpERkRQMjFyM1hvVmFwT3djK2J2UENDU0RRCnJhUEZNUHo3dUUxcmMvM0s0aVJ4
        MDF4VkJFUlJtQ0ozdUdtQXJsZ0RnMGMKLS0tIHFRdUFDdllyakJic3NGdVBUTFVk
        YXczSWdwbDhjb3hzWXcrVitOVFJZVlEKxf3sEezgZQqqDhxGoPxnh8tvIMwPFyDd
        ltsBZRgFzuiM1BGZ6zNcI+6mGDMT50gcMFraTgFQyQT+YDweNXLptQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T10:47:18Z"
  mac: ENC[AES256_GCM,data:ca4OJpWyf99e2QPmI6EdBEf7UGQCsy0N46vFt5lVGKziBTOucBJN3gJIa7kf3PPXS2+wK0zWcjx9TTGY28OQYrZYgRIN7Ns61lkMkBDR3ddrwdD6chIrBoaEVz6RbN2drMVXhM3X6OSJQFFOJz0CNZo+NuJFBHEMr2YF/pCWcuI=,iv:lmgOtG5u3tC9S5qMcPQIWs2by2/H/i9bodn2fBcVd4s=,tag:Xm5dEZz2Svn67iSAhD5nYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
