apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:sBzLvlwLRDbIcLwW9uLfu5I=,iv:vpHcW8ZSEx35YvYEcn7Lkfqw2iP5xd4CdFddGFyEYjU=,tag:hiMjnfKQcF1uMf7q188NzA==,type:str]
  client_secret: ENC[AES256_GCM,data:ksEBx6yAD7BR2x0TxRVfvuRtewpR7m4AdrQyIRq7/shYDnOH6eD/s1IGmI1ArnUU7hiExQOMCCVLGXEcZCdLtw==,iv:b7myOCNvtnxA9Gwk/x+hdaQqYipLI/ZjZz8d+mbo2rM=,tag:hF7FviDVSvtojQzDD+tEJw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SzRyYXVIbEFSbDVqUTFp
        cW9GNFUvUDBxUkhDTVpIOHRYaHp0T210ZURFCjZqcnVjbkRUTXRCb1RPa2dYQVAy
        djJXSmp1UDh4dUxLRGZaNHkxTHVqMWcKLS0tIG94dGpuVmVPOVRpdWlTWFZ0Z2xj
        TDUzZzdSc1JSSnhUM1pQOEllNVNRSHMKEg8aPkfv4hIs7F08v05VmmpKWASu+oM2
        rMuUJjqANYLGGMaDMh1HoaDb7ZTO7kzJVMvI1brvJcN4oz6hy8spiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T17:16:26Z"
  mac: ENC[AES256_GCM,data:dvyXYulr3bdDjP+hg7QutnV3FPBGZ0YqitutKfK6U0vZ8oONVctqfX8wP/c/KOKm1qg9OFru0XgxWrMhZ+NOJT1MTpgKke39Aqtyh0VobwAlFU8Fe7lIvHzgT8XED4F43APE+Xf3/b/i071v36Z8bVnKblhUkP9SBXrhb4rUcLg=,iv:w7nheX5oAf2luf/Y8lcK/JtD3YN1FTirH9rhlCTDQ90=,tag:s5x6jTveiMjR1z4ons76WQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
