apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:N1WTUAc0s6n7C/AY67sCOJg=,iv:lYX9VkSGYDvsk71p0JGQDkBDYRL5Hcd5uis6xh/zZRE=,tag:1LMSn7z0Yl4Daj04BSvJpA==,type:str]
  client_secret: ENC[AES256_GCM,data:H22I7CwOOTi9/IUEQE7UrejJMCp8Fd08ngrHPCGHXHTSoIP+bA3JD3ro1fRTZzQUpufCpJZ0I/b9iSQsA9jwZQ==,iv:yj6oIPoBJZII/FiroPTVPn64497TAaXrZ2Q+iu24h/Y=,tag:UIvBq7l5Hh8Lbc9m1E494A==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMUYwOW9EUEU0cHhWL3hw
        SStpOE9JOWFMQ1BnQmZyaXhiZGZZTVIreVV3ClhuVTJUWFBPMEpHNEg0cW5VdUY5
        NExXazAwZzE3S0s1VllCYWsyYVhTS0UKLS0tIDljMW4zRmxQaEVQVDJ4eHBIWlVi
        b0NyL3FZTjRmTTdvaFYvQkFTa2N2eUEKW62YW0jwIzURdfAgl3h3pJHfYsii6Ct2
        fDg5ByMjWjTNkM3tx8ELMGFAGqrrft92EKaYOzwkxwEc5l0aN0ZdTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T18:40:09Z"
  mac: ENC[AES256_GCM,data:yWrLuvl742r6v7jd1rBdVXF++IcCcNrGIglji15BhoU/3BbAj92nWAL/g3RfYuR/z3ACYI6ndBorFeKtvDaJskQkb7fTCtOyL8SI9ML1c1Bxrx1r8oRdM+FpVMiWJJwA4L02m3Sg/cdYIQ04zLK8Of1uyMQjxp112eTfH2K1Ggw=,iv:J+ZJE1eB+Nyeg/QBQtlyC93dUJCrRhKZFAafhcMvXtc=,tag:W4KFSdXljnTe+lgj1gF89g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
