kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mealie
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:I11jWQO9TXY=,iv:V047CZLWdEHajMlMLz/r+JKP6tkVda4TRmPXKHMh9FU=,tag:YFIVuVSgKW6JviRxF6l26w==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:J1TLcYfj18wicyk=,iv:VkjAQxsybp7wzqMFUGnNIHwC7JdoKtM0X6mlECdjhUw=,tag:6dTlqEGNesm//4nld5H5bg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:bNvlrSglWhocv54=,iv:7f2nXMb8Tcwyk1yV1dDXHr12pNjeCr6Ik+ZHYUuLFkA=,tag:fyJAdU1/NsXN5WM5zdgZUw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:m3aSYpoIr4HYgz0P1JMk+f6hX08WWprbzyH9bszu1TKExotd2Ya/X7n66WD5IehDC4tYItk4Wr9rBBDeMAl6v5Q536k7JiiCsT4kWdqM8LCWnwPBag6f5Pf+t7UzmzvNvZxOyGXZ5iYTECi2A9a3W5OefrZ1FxMhHK7dKKNK/vs=,iv:zblnSgeSDk9kDobF2baIMjwzpqVbE7kxL1LJLfznzMM=,tag:X60T7j1S6Z1N0+AKkmSWtQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdXFDby9SOGs0eDhGcjdn
        N204MEMzOUVwNE52Sm9BblV6RW5KSjMvbFRzCnJUdkRnUlZQdThsS0dYYkRSZjlU
        SFhVREc0QnFidGF3OVhmMXRvNE1GWVkKLS0tIEVsQ0ZDUSsvRXEzekxwVFpKcTg4
        Y3A2VThvQ1hnVFdBWk9BMEtWU2l6Z3cKznk/IvsaG8idlt7LEELoS1cRCKTRWgLK
        EM53BfNV9IF9qNTMocAkAfzYpo7Gz3FJ4mLQ89tjqM+WUQpp8jBJLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T16:26:57Z"
  mac: ENC[AES256_GCM,data:k7V3AE//u+Nt4PwBRQRgUPu4/owkQWJK9fOvcB+znRI2PjYaxDs6n+tP46TTCphtmtON1PqHS0hkedD9S2wp7nXJgcNzumLG5lvZOfn/fAvDYizzc6Nvrz1pPuIEfEOKAi7N2bE/ilcxwpPLWzRMi+vu+gTyReoUXL3tof9WHXI=,iv:1zir5SLlNndoVwEqAvvWkyN3x3R7PY4gvz4vmmxxM5I=,tag:Wydvjs906cj8z9tTcLgcpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
