kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mealie
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:AeV02ZFDorA=,iv:BqNTSeHn6/V3jLTh5yT0+gLdGKYSz7v7w6CRXdLAlII=,tag:yc2gpTr43IYiBTD5If8hvg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:uz60qpBGXw27a8w=,iv:9GPktXfiy+xJnnpefYNFDbJfxZ6WTiu2cTBtt3VZV7Y=,tag:93epajcfNk8D2SCFn2Teig==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:F2dCGfX5xLwGlMw=,iv:/DTtGrkFRqjP8yTKlZNHk+CDcZGJJn6h8KnTWWC8uRI=,tag:jQDnzhxm7uqLiW2mzcbWPQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/5aS33hA6U7o/5M+iZrrIHEVoC7wgjR1rAuzFQ1dLSx5F7M6jOoUCBDGsF0uHlqE6KhRz8DpZcERJPhv8Rsci6N9apQJcLOegrl0SvNMEbpk1gjMalKP8/Ff/dx3Usys8WoUzBJ3hpQ5wbPnIdLAdgFwag6NK65ZxmUCNaJpTo4=,iv:HyIFMApk9YGG1+56W0yIBLrFtM8KhjBFJuEI2WmVeH0=,tag:0S09YgRLN1SiWrXatTZO3g==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VHlWaDROQ3cxV3BsRGZt
        TGdLN0Q4SjV4aTJwOXJENno0T3BaK013elM4CmR6WWpaeDZnOG0rd1R1K1V6Y0Nt
        ZTEva0gxaWk2bDhYU2xBSVQzaUxUaVkKLS0tIERndHNoZVFwSmFYY2pKNGxDa2E3
        ZXBiWVZDODhrK2x5a1gvZG5qUjZSQ28KYo44Gvnk+laMPgAHcInFrm3lDigMJ8mm
        iJnQnrfWHmMExehGBJ8UQVlPGJR814iIp8ehRNRfUP+gHQrbafON+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T17:25:30Z"
  mac: ENC[AES256_GCM,data:KI/MEv0zxCuwDJVDM0dnP8wytSX3rJyQwUjeVEZhubclPtMxSxUdAJrTAuRN+fRAIU8JQRiABUYtrlWeMhoBlOF+Bpj4oTYjofNImjHn84+jbW9nhKNN26jY6+7Pnl53ataAoVLtQTJ52lnO78mJrwnyERT9mA7XyFRIkHJ3WCI=,iv:hna0E1hV3Wpqe8IBvugSv0oa33pmYL1sqLO0bY4/LRs=,tag:g2RtKg3B4cgEzHadAjX1sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
