kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mealie
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:O3ZqN+2nBOU=,iv:qQRV4HxMSvEHdClKoAk6ZqaDLNjb7qh6HQQpnfQ9NrA=,tag:fayMOuuDvVHeL1vuGlUTlA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:fcOVlpZaIt/TrGw=,iv:P9rXRYUaczRKjM253OKj4bOh7F9cSX0iX26WQILFz2k=,tag:5vrpCdz9AI7pCg3De1IwFg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:syz7Kn5k65bP64w=,iv:5fl2lyY46PblMqkyhAQm3//YGj1s3i82PWO40tTigN0=,tag:KXouwE1qF7j6aSPdra2uUg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:XYgY1xAaeDCU7NXWrGtrA37J/v5QbqsVdVsXAT7u0SiLo4q0YB+gI8pfsKY09+1XALOI+xGWxs8sCDAV0kK1BzBvxk4/mSAT95xdTph0iVMcb7biBQ39fZGb/vmCzWMFh2IhoxiZLcE4ZzFrVhl1YviSlmGevBj6rdqrPBKJu/U=,iv:DNNeW/wGBHHVj2rOM621zs8GuVjPZZlMfg11h+bjBQ8=,tag:y8/psQ2QpnJHkQLaWUPGPQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaE5sZjJzYWV1b2g0Sjht
        RnFnSG1rVEhqWWtnYXZMOWY3TkZVK0I0b0ZvCmRvd2k2b0czSk4xNTV6VUVkRUti
        MWFYNnA2aFBRamd0MGloR0xIc1pIZ2cKLS0tIHJOemlnUDd6R3ZOMk1kTWxDRHBw
        S3FRckJkaitxVEUxNUV6U05JL2dyWTQKR7H9+2houg1D3oKjN8NqFSGh9CGFAzf9
        Ilbl5Wyiy+8xhdL7sQWSzMoIJFhkPgaNUZ40+zdUKzFnic7v5SQOaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T06:37:17Z"
  mac: ENC[AES256_GCM,data:8zdUdYV+V9o7aCPdF7ss870mPtQk/Zj6LcVvZMr9bZeSMkABZtWPRBPCOq8ce1O9DicIieMwg7NCNvrweGzRnORbe5280cY5crmWXZ/Tm4HDfwAU1Rynru7IMzSObr6Vo4W1HfCKCXGwETEOUWEv8LpCF69GzEpgi0xiH3sf11A=,iv:h/bM+H0MZOQuss0KGxTBUxzw5+u+Moow4Iq+YfWf1Ec=,tag:2yKiMeGwii1YzE0OjvQx8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
