apiVersion: v1
kind: Secret
metadata:
  name: bytestash
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:i2dDWy18wk+HZRoCO0fVaIf5bOr7/gluxkD5oPeRW3s=,iv:1NPpx+FDNtGMvmG7s24y+R+HZOoFLF5/sVfC0YV/nRs=,tag:S0jMa9fXwmDXSj1AsHp47w==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeDcwUmNHTllTSkNoekNG
        Qkp2bGNyS1B2cVpBS1grQ0JUMm41NkhOSTM0CmczbTgxU3hUVjhNSU8vdGVmZjA3
        Zk9jWmo1M1RGTmVsejcyb2tnRzF0OWcKLS0tIElkYWtZKzQ5cFdSZExXTGhDVHZi
        WVZ3TVNvQzBZU2pIRnFxS1g2bTJ2SlUKjblIxSng8/mtwZPb/36qWWoZkg6o2pwN
        q+wX4szwtnAmXiC1217XJmzeQXiL60ghDlxm/WLoSGpVuycGhTL3/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T16:35:25Z"
  mac: ENC[AES256_GCM,data:I++vnlLb4rEFYAeXax/ujUn2DpKzIF86HhKvGZLp3Bsw1caY0SeqXAtNxAeanNun1S5HOfbMThjKMkE+f5/SSmzfNLbYR8VLGJ6kguSqjRt0bV6xEmc++Wec6A3G5UqkI2u+0lD+2U3fPQiAT4v96Y4YGf6pwz8SzciKKvFdZw8=,iv:CDonHFRShQ76SOpZLPOqYFrCqPK+3+CulR3r5yxTvYs=,tag:JYoqQum+FmG3r60+klJHdg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
