apiVersion: v1
kind: Secret
metadata:
  name: bytestash
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:ET74h6qH0J/nxZkm4bwTKXz4rV1+E7luUPZ4Eg/dLT0=,iv:fluL8wpkTtp+7GmXyzHsvtCFZjpPUn7edy133HOFQPY=,tag:PZfHsUFsqihR6FWb0Z7ahA==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVFdLd0g1SThsTHVTeGVK
        WnRaTGlSbW9OOEwzVUx5c2p3Z1hUMER0UHk0CmU5NlBUM1hDZWlQZE5udGtLM0VO
        ZW9WS0p6WXByeCtJcmhoeis5Y3VwcmsKLS0tIEhrME9pNGVwUGk4U1ZUYVhhUEVG
        SmZnajNZZXdHc1NmSlhyM1BJY05oNTgKcVmXIb6M3+sEM/UKeB/5QxALx5IeY1a2
        98TcWFQ99wwlFulcp/1d0HBu7iraw7jxeQLWcgMkCVYrIHjaPTpCIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T17:42:34Z"
  mac: ENC[AES256_GCM,data:1W5pkYMncuTUKRWO8zh1TFdile4FI0YPJLmTaEkc6F2Yn3pvuaboBa19IqXy/kRivcBYy1pwkDokorwYc59svttoCDWDR3Z0nU4BGsXsSRapLrvomq/tc6DFw0Imy58qwooagkDGjmUwVk/lXPj3r2xGM+I+fUOzYqBKk8VXchk=,iv:zOSjDwB2xvg5Rn2bEqNKS25x3+g7L3arQ3QKHLpPgls=,tag:SdfSI2rzmBMPIrlxf0/Kjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
