apiVersion: v1
kind: Secret
metadata:
  name: bytestash
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:0N8ZBdSnRkR5cCGypvwjbqMebbRHC8/n54kpuTpLMFw=,iv:8gTNKlnovuFg+pV3jxWUIiRSUyB1xef9hSknu/dF3ZI=,tag:u0jVVsjB2G54QoVT7qld9w==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYnBLZUU5cnkwMkVxT2tN
        R09VNTVTWnJtSFJvcHNMbmd5RlFwK3VyS1JBCk5hNENuOFNzcVYvQS9qTE5qUi9K
        UW8wSGdOZ2lYZDRHOEpYZ0J1VlFxb0UKLS0tIG1aT01ieTdhOTM1aTVXbjgvWUtr
        N1lvQkVBZkhxZVlwUmVtQWZCNVdiN0EKtXWqjSi8ls+pRtj890Xi4iMIkmlLytau
        M80hKmyz1C5gsnOsHVWMypY4KrTCw0UBw7nnaq0PpR6MSI8Z7FxhHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T17:14:46Z"
  mac: ENC[AES256_GCM,data:001vmunfcNsHq6RbpjTFnVdVfvUq/BsYxmX3LBn8wZSeZNQjewD5FbIcl7xkFQBBkhqSmnP8VgnsZ9Y68bGgm8AmNrwBRuZEDh/YTY+7pbeL2h8h5w/qbid+9xuUVSSEK7/6wip6p2Tlhdre33CZiYE3gzILO96QtMF7k6bm7Cw=,iv:htNK/hl9SOssohprrHH244KXB3dfkBhtjXQNzCOiCVc=,tag:7qc9sjOYBd0yW6fYydGwIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
