apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:r8LzS5fTFTdy0kv9FRM/TsRkTZErAUmKsdk71l9xkx8Du4N07sTlu38fPeGLyH7yIvJC7Nb7h9WHXPEWtr0PQByNUx0xGg2qhn2Wg3bzjRlTs+Nr7rnh6BUdhkTVlyEMWNs6olUWEDn7uAxmVsC0QjNebe9Y/ffQogWsCYMsQ70061qLytUd6puOUXSM4n/xx+a3yb64pgdgavJIoOE3uCpHQ85aavOZZvdxnR2HEsu9j/Z5,iv:HXShtiwmRP9F6xI3JdcTpQLQc9fskEEOKQIC69SKHtE=,tag:330kaMWqRfwOHamAtGtrvw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZENZUUFoUHUzSUo1WWJN
        aU9INmxPRURWSy9DNk11NlMvSDZCTEtqL0RZCnhTbm1vOEFaZTBVd1RUaTNSWS9S
        dDRTa09qMjhQQzZVWVowQ1RVOHppencKLS0tIHpwZWNEZmRJSHdidE5DTXh3T0dJ
        S3RHalM1bWNJU1F0WnhJak9TTWdzeG8Kf3EFSRfJddQlVmxvv/D3bXLiP7KEvo3r
        z06Lh02uVQ00IQI+G4BwiCC2LnotGXQPGCeiFiA/dbiyb5wuQ0JF3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T17:26:38Z"
  mac: ENC[AES256_GCM,data:HRTbs1b/excM+Gg3DY5rCG3BneQOVABVbaLWLGDtHzkmw8jWF1KTMWDBp/faahDv212Sw90xlxgVM3ZFCuWLnc+ySaxguhNZ/piv0HZpe+8sLwVtUpOaSTXHxIzc5j42n58bhGJ3dyLb5AUTANyog9GIbTXa8/LnB/RhG8T4GiU=,iv:dgc4+PMvQOOPIGJYphpItPyaMKhZMSekNZIbkhPW6nc=,tag:04Spus4iI15vBXpHuVSfSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
