apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:8XLRZovh9CL8G4DPmb6S9deTlDGBdnhmrvTdR9g6osywpAXqNSv08zmbeat5o6lmPSaB6YeR/CM+7br+deKjxyy55wWV5AVBQt34gtvwwhBtF7UXGyVz9kojydFfFGZikSX3MsG5vafJkASGyuQ6VwxtT7tETrkjyQ0Wm+5oc4Ge/ut75/kt803pc6HaZ4/8R0BYKkP6oF8x5QvL39DeAlBpJKkmIFyPasECiijBxQHqe3Js,iv:aZOzVVYkIeeuu4beyMwofE/ILl+zJoX7bCWtYfl3d1c=,tag:jxxuipSC0xdbQrcspGgcow==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcWNPL1Yzd1lJZkVSaWp4
        ajk5NTRTSk4yN3MxSDkrY29DZXN0UkhKZHdZCkZERm44K29BR1Vqay95aFozQ2M5
        ZnFOZW4wV2pCRGZvZlBDdGRzTlhqSW8KLS0tIGs3UzlJUUdEenJ3ZTRlL1NzQnpm
        N2toZWUrYm01OVd4cWhEVGxkNnplR1UKfTFAPV+TkL/uaxvd5xdwC3YYTbY8dnIL
        TdYZyIMT4nu+IDWsJCgpy7UMwLXuAsqnrA23FcXMKfNgfehAKE/jYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T17:25:29Z"
  mac: ENC[AES256_GCM,data:ae/f+qmWxy2IkNXsLk0C5s5CpP/Q1HgCR/RuxtHg7pHPvPXC9hqRkFJg5EmATWtu/XM5rWK4qFKOXn83QrcK1jnGpzUqxdsbCzDJNbTVWWPU6t4Q9HLvDsmQTDTEJWF31ertJZASDD/AyD2r0fMyJFuJKWu1o2V6zJ1mNU5CpfA=,iv:crHF3LoVWmQGDar0eW0OMaI4t7Fo4Y1VaPaTSzNZAds=,tag:W4sqOKVdyJ8/uBMplXqPlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
