apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:hR32hNB86M7EwAuAv9DcgvQLfAg29e8FXhJlZ1WsZyup9iacpbS4f3XI9vI29ZxFmu6iR6Bc1CMM5QA3I+CE5oIr0wgHN2B8aYoBujDyYudjKTkJejO2f9ZnJ4GFm196xkTDb7EaPmccq+u1xOLRM2X0NUUErV8honIN8eXud52v9AolYnLGB00PWvX9j9G4/oV3xTlqOO2vYZNtghExak7zPIAXToGEg2mvBkjf+SsGOhx1,iv:cGBKHZEPXL1iEj5DbXm0fDtmMaOYD+tY078hY3eWvUo=,tag:tzM+ZCimtnB1PoyKI+AJnw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbVJROXdncDR3c1pCaEQy
        bGhBK1Z0YytsZE9vLzVSOGJIZVdNU1F6Z2lJCkRiOE04UGZZUXdTV3Y2ZVFTeXRi
        bTgvcHhYWENiLzh1cUpLQlk1SGFjRUUKLS0tIGFxRWlPUzFkUmJlR01MKzdIa0dI
        MTZ0K2xDbCtsajdRWTJ6U1E1Z29DTHMK6xtYzOAxsEjmGUZ3kK0RXHwAGLI7Rv3l
        6KdEVSk7YBFXaWfMHsIhtRRL/XVUKFq20Dx3le0dJk4STMkc4nX1Qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T07:23:59Z"
  mac: ENC[AES256_GCM,data:0pIDjDNmpkDh4hSbYCUsaViq9L+JkmREYwe+CfONIISB8nydjalUoL5w3Df/kYRGAokjoJuWdOg1WodtkLjhT8wTQV26F1kELPjVtfMd+V9YC91Qw5ZGdKItl3z2EKA+k8CH5+1nvVOO2+549PD+55/L2cPQ1orlMaOUQJ72ATc=,iv:Yq4r26LCwt1VBbXi0nMBb9kaxAKgsMoT91n72AOglm0=,tag:GvEctk6cTBihnCBo+o+KsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
