---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-pod-cidrs
spec:
  hostname: ts-pod-cidrs
  proxyClass: tun-access
  exitNode: false
  subnetRouter:
    advertiseRoutes:
      - '10.32.0.0/16'
