---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-nfs-svc
spec:
  hostname: ts-nfs-svc
  exitNode: true
  proxyClass: tun-access
  subnetRouter:
    advertiseRoutes:
      - "${SECRET_NFS_SVC}/32"
