apiVersion: v1
kind: Secret
metadata:
  name: wallabag
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:MgqkOxmiKLw=,iv:CP3lJ2N8p1HR+rkJO3kf7woMtPimbt5PyeoYxEQkjfg=,tag:Qxsxe1bH9T/ELcFZ6iT/Xw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:fddGAE1yB6j68yvqumFM6ma32xljt/nzCMPCu/mD408Au6YT9ow=,iv:ewbVeknN9uCrbTm6NVTsHLk/uCVmQF7MGvXi0i07Klw=,tag:M4YmrXGKoNDHfExTYE6mRw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:LC1gNEHD+y8=,iv:QkVdCvPwhH4/yBQEfGtY1xd/x3iyHJ/o9+zzAtEv0ZA=,tag:ut3LwLXbNX15MbMrBIp9Xg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:DyvaK7eS5+xWoms=,iv:E65f4pAjuI1/5WpzZ7fmgr3Igk9sHIMVGtgTCs5cYE4=,tag:v62ebaXpHCKDJk4TrVDP5w==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3L8sk1/9EZqA+cQ=,iv:txT48uDojUjSFnhveOcxOkS0YWMtStZEqSKXUMO6Uf4=,tag:2K2yfRTCTplERDxs33TyUA==,type:str]
  #ENC[AES256_GCM,data:bln9nQ==,iv:j9eP+wTuJ+F3UZzO++8U1VAzT4c3B7QLfQ8XNSgcNXQ=,tag:A9Wzc0uwO+vvIqHzugbzGA==,type:comment]
  SYMFONY__ENV__DATABASE_DRIVER: ENC[AES256_GCM,data:MtRCNhCKY67Z,iv:pE22BWQ0taZv8J5IX/C6HpNHPj6o+qYZajKTWMTN2G8=,tag:RieeWXKIC6ka1hjO8bAnuw==,type:str]
  SYMFONY__ENV__DATABASE_HOST: ENC[AES256_GCM,data:Wyg44mbKtopbeQgKR0a5kIcXe8qan1lWuAsSN7L10mi6CUlzuHY=,iv:GzJAj6MXguhpM9f+GaPwaqYXgtRxxfxAx6W21Ji2OCk=,tag:Yq9YzlMbmIzGArMnr8Rt0A==,type:str]
  SYMFONY__ENV__DATABASE_PORT: ENC[AES256_GCM,data:vCQUlg==,iv:SPQ73aoyVF5dKvx3wXIW4hslQhen2/DRWYNu86PJQDA=,tag:IbZFt2RK5FxYWS/KYJjeKg==,type:str]
  SYMFONY__ENV__DATABASE_NAME: ENC[AES256_GCM,data:1V0GCBBo8II=,iv:vnphvX9wuJh8MjhISeKRS1zcZjHEezdfL8Dprnnmpfs=,tag:LsOHEB6MPt8HXaHh3b29Jg==,type:str]
  SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:6WD8PEIN/Ts=,iv:82/aYbLVeqcFiWVtWL9SN0xJec3SEGGfK95/e+38n5Q=,tag:PEn7XWtNyE8gJWya56oCHw==,type:str]
  SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:saxphNiwihnDEqw=,iv:5VWcQpzLMgZYSQCbrN+v6Nj5CX7AlHi0WjdugpHCvBQ=,tag:83hqeQdyy/UfRg7mHzj4ew==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTkdPcGt6bGVNTXprRWtQ
        aWNyV2lOc1FSdFBJZENCSHpici9hV09zSURZClFobjR4Z1pCRUthbmRBM0VqdDU2
        Y01ZdGdxUVpUQjNDbkZzbGs5cXgveVkKLS0tIDM0Tkl4dVlXclN2bzluY0tLRjNL
        dUJHNmpudkp5NWtkb2RPbmhENlB5bm8KLQwV/xRVMBjK4DY5iQ9uiCNtc1LpB501
        T3EKOo6CRj5maULjMIjwkVzr+UEm1kUo39/kllCUzbQeN5TXseR8Vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T18:01:46Z"
  mac: ENC[AES256_GCM,data:ifLi54eqK6DOJ0R9QVAPG9AvT/IK+b1mQTkgJCZkx+woNbIc04Px9ImgjrRIx+8+Omj+p/4aNTlhLxJxJj26/FdRnN8WSKuUE2T+RlzaSMptMEvk9Tpq4PkaG1Jr6LRyZigtS+E8ytC+sYIaYliJpA3a3fJ8nrD2E2tVfFqTLss=,iv:hnXrzUxiEFIkw8ZZBwNzlggqHH7dqc94d97WliSd0JA=,tag:vzcUxFNoN+NPLe4wz9OVcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
