apiVersion: v1
kind: Secret
metadata:
  name: wallabag
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:iyvoKbw3XLs=,iv:s2RyyTjylUhrb4QYgY6TW4PARmOzK9QK5Zvi0xJ6IIw=,tag:oonBYtUjJr7JCn4Y7MElCQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:07dX5voI7bYahkUDk3lpr7SeyyOn5rg3zUkVWvYQtFbpsAd12dw=,iv:uwW8xGiUR3JloavTUnh5ZKw4PlGHoykXQq56EBF+3Tk=,tag:3etwr00ss/zD+tFQJTi7hw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:hlp5wFpBRzM=,iv:qisjJ5nRs+FwWHHEmsik6H1FS/m2vJ0tF9E9LJu29LE=,tag:s2oV7QHfURwhDtl8GH6zHw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:mTeR2y6S9EbNOYo=,iv:1u/Sp/fZSy1enE5YVvxfcZEPAI8CIY1RwKD7HwHJBpQ=,tag:QxHlyrXTM3JbcjU1hdrneA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:lsTF4uwG67xgtz0=,iv:EaPgsz3qVtfJLAb3UBO65Hl7Hvaih/GrCp9etRTIpSU=,tag:hRujeJ0VlHnulbwCo6pBMg==,type:str]
  #ENC[AES256_GCM,data:Gli+hw==,iv:bT0OuTVELLT3eEW8ItzFqEaHkbeW/xnmAFmVagLP0pc=,tag:O0ejYaJGD7OBoYvRmYmRgA==,type:comment]
  SYMFONY__ENV__DATABASE_DRIVER: ENC[AES256_GCM,data:qBob0NY7juBV,iv:SR4IPEugul+UOh3vAgFWJTIvAKYm1KZkiSK9blc65uU=,tag:ShffffdvQUHdbCG/6/lzvA==,type:str]
  SYMFONY__ENV__DATABASE_HOST: ENC[AES256_GCM,data:hY1LcSqQWQH6ES760o++gOvjOT+pzZczFITUIILaxbsfzag+M4M=,iv:6cdFg612dSMu9/mP5HFYCJwzFPz4a4491cTJgPFxcyk=,tag:u1EjnYWBStNw+flwatMPdw==,type:str]
  SYMFONY__ENV__DATABASE_PORT: ENC[AES256_GCM,data:EnJHDg==,iv:BV5mKmxC55dtMLi1Xxk36kvYjpFioOqJqk+0isnPAGE=,tag:6Lsngm+CI4pU2uSVHHOgGA==,type:str]
  SYMFONY__ENV__DATABASE_NAME: ENC[AES256_GCM,data:cH+7DalmXEY=,iv:QgKB2hloPYQXT1UWGW3n0OfxoWkBruOAlpeYbo1tJBM=,tag:IkaACVQOfSICVal1RpNNkQ==,type:str]
  SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:7N7W6C7Ll8g=,iv:/B7MIJ34FylwEcjeTp5JNUcajRD4HcnyNGfX6Zcgq7U=,tag:rKvKD+OgAb8n6ZTPl3dsfA==,type:str]
  SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:9rhi494QVeLZOxA=,iv:IrTMY/r7xgxjvqS1GP+gdKADzMi20vrXrLRP7FTiesU=,tag:VCR56JvbxL7Su+DOJEwi1Q==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMnpoT08yMEUrODlRNjVx
        ZU9rc3Z3WHp2ZUJKMFhZV1lLb3VYWm9oM2lZCmQ3c1B0UW9NZWNKZWZFWkZTR25n
        MHg3cWJPSWdQR3NTYWFvRTdzQzd5eVUKLS0tIG5uQ2Nvb21BNGlTOTJzV0d4Q3Zi
        c0syeTNYRnRNbVUzN1JWVXFiTE1WTWcKh9zyUZ8nnI049LU0HgvGfaxMdqWzHKCq
        lx5PuR7H9c7ZgHsy7s17PzzFYVNWpwuct2oeRlwnYcLxrf997gk8Iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T16:36:35Z"
  mac: ENC[AES256_GCM,data:S5c6exmDYZt49Wbig0DM5XvpG4ue7JN458ibYtSdy4KDYVVGzCwnUHtWO5hUHAz3zeM1avI7vmxUJc2s9k3lnmTgypdNd6gps1h5KN31iohwntrScvH5FQbK6rzFtHdysb1z9DNYjfAdr5XUSxCU5zoX0znzRmd9x1dI3G/bscE=,iv:uUCurnd7M/HcojialRxRtUBn21zDiyH2ptNqn1XVR2M=,tag:bm8mSOWv8Z78pyYZRLsp4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
