apiVersion: v1
kind: Secret
metadata:
  name: wallabag
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:/c7u0I5jPPQ=,iv:yBZlUzMKP32KzlOIX6RP4rVwFUvF1oR6zPTYu2TMfVY=,tag:q4xZq0Uaxi4WtBAvp6VcCg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:0BU1yDNQKX1TQq/aAsgPrGFGL+seEjPSOgKQ95dCmIitdsCPA30=,iv:mZNUJnJfojvF+BvQ2c/4JN//CD85XqoI9w1eRYpZZs4=,tag:0VYmk7zblfjTNaygrW+NiA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:x35c/eGMyJc=,iv:NAxU6QKM9slNqFsKnA+ZdnxdxqPK593StEjxkH8kD0c=,tag:5rg6UdK/pJb/w/cDPrWRWQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:N8YBEqor81ew5uo=,iv:KJ43O8+fhE2/NFbRfUN2Wod4l8mWvhuhDZx5Zx5K0YQ=,tag:YjnlLeCjQGKPiJRuPH0Nuw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:8kIZev03vmU+nq0=,iv:rTHp/qdxXemSb14BzMQTldg6mtOjlfiIL6f8ase1wxM=,tag:R2knGGi8T2ldgBi4e5hwHg==,type:str]
  #ENC[AES256_GCM,data:YV7DOw==,iv:qcfAZrwzVihLokL8iWUZRa5+P9lkc4hWezM6q4irj2k=,tag:TdcQsM5flkKz7eRFM+CB6Q==,type:comment]
  SYMFONY__ENV__DATABASE_DRIVER: ENC[AES256_GCM,data:XnahH6m7/tdM,iv:O0/bvsP9sdb2Ic/guIH6j1s0qHcELpqxYAR20P8X4B4=,tag:Bp5R44hijn1kd275hHoEPg==,type:str]
  SYMFONY__ENV__DATABASE_HOST: ENC[AES256_GCM,data:hFo7Lm1EkZrgx16uGH4JDE2h8PbtUi6IoTtRlqQb7Gxm2k8KIpo=,iv:iJYoxgqi8BeGBD1pshx7Z9jhU0hjgzjdvRiVE94r/Xc=,tag:xADn1gyzyczbLfgOvTR4rA==,type:str]
  SYMFONY__ENV__DATABASE_PORT: ENC[AES256_GCM,data:IAZJ3Q==,iv:QGVL7sWlVm8QI0IovxPQsxO9uGbi//9QNMoosNxxl/Q=,tag:/o4IHvhm2Aw28/MZIvE6jg==,type:str]
  SYMFONY__ENV__DATABASE_NAME: ENC[AES256_GCM,data:V8iytZcN4xM=,iv:bg6VfobJD0GwGtwSibB7/BqD9x1G7B94L74NVO1IX7U=,tag:eF7IhVWpXp8tYCtdatG9ig==,type:str]
  SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:WiIbYNWSw5Q=,iv:OJP5ijmtYIfGddOtHzWDH4bzhO0eSr7L9nUAkyTteZc=,tag:ePCji8kYFj8b7mI1WxvpCQ==,type:str]
  SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:yFeBi4tlDqwwjJA=,iv:MxAbDCD2O3gcIoK3Q3l36dDQozdyPv9ytnBz+xRliwA=,tag:H93DiNonY0aOKbBcmYRquQ==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bjBoS2hpb2JRMjJxZmVn
        QU95cE1QWUFxK1dIbGw4bEpVUW1TWHZneHdNCksyUkZpODRPOFNGRXN4Nm1TdFdv
        bEMzOWRWQ0NxMC9IS3AwQ0dXT3RkNWcKLS0tIGd6dWV6UFFMRGxxTHIwWVNQc1My
        Z1NRNzZtNHFRSERVWTdDTjFPaVJmT0UKV2D01Dvhh6uxsQWgk2oDILkiPWAGHi0I
        2llG4bf7BiGzlonSSkf2mOghqG2wSC/tpKyfzKJcu3qVPkK32DFGBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T17:10:58Z"
  mac: ENC[AES256_GCM,data:QfYEQi3Pgvomx3qHeK98MBAV9a7fiTD9DMWor3kX0pWL618UgrQmYpHkO3qeAUREbzShaJRpWw2g28OU3fuQuUV3cKv/MCuo4K9SUF03ZJTrhrwc39BLtKckKfnDRW8xdrZVG3Rbzn6ihxTyWTGoKeus9rzdDk46/iK8n5uCDLM=,iv:CM2/3z3XBiomvu1aKNBrJo7yCSlf4TWagL6yz1UAo50=,tag:x5N+DLJTsRHolvBP/W7S3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
