apiVersion: v1
kind: Secret
metadata:
  name: pihole-dashboard
stringData:
  password: ENC[AES256_GCM,data:D0PWNXDTTBS/M2E0zTwvGw7j8T6tfokoMmH/hArPtxc=,iv:8PgoGhuwOR3A80lekFwMQ0advqeZ3TTmvZc/J/+TdwM=,tag:KAsdGZAN6at4SgwUaKZazg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVW9NUlBpK095NXhubUFZ
        K3pLK21QSkI1VzJaQXlVVVpCK1Y3U1g4ams4CkI5YmFSbnZORGhrZGdpTVhZMGtw
        TFRhZld5Wk1yNVFkZG9KQURwcG5TZ2sKLS0tIHVna0JydTNaZEpLTGVSamNrL3gw
        UUNzYmJrekhFS0lxb2gxV3RUSDdkN2sKSJqEIFMW7fpYoiTj/NCWqDLcMEMd173a
        kfDrGZjj+Qyk/tLofDBJdiUXD4WhJMBnVSCnibz+hEw3jXMG//eJeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T07:32:01Z"
  mac: ENC[AES256_GCM,data:+JgV0+AKprxuAp4yuCo0vqriN18nU+ISJzWRvGptsNh3izOpkQAVEq2UKK9Iw6afKKej6XeKF1dhmDAnIp4LM+jHL0YFcOAp6Dfz5FdMTHlK4jDrk6TPrq1Ne9jK3lezLakzGU9oScb0kspjjgRu6fEQirIF9ke4YffvfjFZtdI=,iv:MQxqlrO2bOvri8zd9fOFlKWwKZUChr2eHbp5GSfe4ZE=,tag:t8UNiwbPeKVuwtYlB2qaWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
