apiVersion: v1
kind: Secret
metadata:
  name: pihole-dashboard
stringData:
  password: ENC[AES256_GCM,data:v0gEI3K/j6GQ/XWA6G/DOQQe5+ZUYxva+oZ2tjvp54U=,iv:P38nT4QYLirAfcmFIkMz8TftG8qLwfVJMzO1NuVzIbE=,tag:09qQI8bmBbONmAVENsgxZw==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQkEzaW43cFA2MGw5Mm43
        RXc0dzduK0ZSMFpVZldOTEpCdU1LdTBBK2cwCndLSVI1b2pjYWtLYVBxWFpCbFNT
        WmUwWW5oOVl4SFZhcWQrRzg0QnVGelkKLS0tIHZjS3FmSEd5TkVSalZaeXowSHlK
        OUJpbW1aLyt4dXhCQ0xaOG5hYmovcDAKV8Lf+kHRu28GXcOzV7IHUMAYVrILwchN
        7FAeJBBIE5bNILSZ7B98Kh+syXcn2RfIZAZVv+5evGblGE7htAN6NA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T02:12:17Z"
  mac: ENC[AES256_GCM,data:9SnyTOrB6YWmTuI3hQjfmzX52ZMzp5ZZmMa7Wte5IftbkkRcQgN4OtbXzMnfk685St//WlOL7ZB5c0/b6lEEoXG6fpF2akW2gG1zShLSKQKFQhCuSgol6GZ99QKnlKDtvJ0YAq5BmcNCytKZs6OIjIO0jY27GudchemjcsSuSRw=,iv:JulWMwcs1iW2+Pu9y0JlZUTOgs+AJBe8zQ6AUcBfhCg=,tag:xHAePnWPtUZuzy0mhJkO5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
