apiVersion: v1
kind: Secret
metadata:
  name: pihole-dashboard
stringData:
  password: ENC[AES256_GCM,data:rdjgMnu4GbYUPqZCneWmzv0ec5jt2W70TqLmOfZpk68=,iv:QwM4tEWCKp4fu0ZafLWX726/9zrMW9Cf3goHUcWsRTo=,tag:Py/ieBR/YD0ohICgq9hfFg==,type:str]
sops:
  age:
    - recipient: age1sumyxgm2je4txw82k838698mmqmf40wsw6j8eu3jhf5v54g4sslqpchxuf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cjVFRHprMmd5aE1HMXU2
        b2dNcTNRSlVEUFUwa1M4YndyaUtyQlZwRmxVCkxDZTNNcXNlTzR0TnZCSTRuQnNR
        ZEQxeXN4U0NJSDM5YzA2UEZnSEoxdzAKLS0tIHZxai9IRS9YNDJCdWdUR0g5Tmo1
        eC9UaHVEeVV3RkxNdHBaTlFoMjNDSlkKbgYg0wKQvSItvolfNrrkP/2/GZhll4q3
        uioJi0CaPM2whZAfMIob5ONuauGTYj9LF/qgopiVzYjNu7nYRK+wgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T03:15:10Z"
  mac: ENC[AES256_GCM,data:qvN+TtxZKdrUmeFeUKeBt5wBLwAs9ytXAnthX06ETTRvcXlE1J5Zth9n0kc7yerzfRbU+YstEwjMcMbZJndJl0LKLBZXVHUyvAeXCYUrwO2mVL5j2MubiBTGxq6U5PCidTs28zkd0IFfmY3wiXNteXjS9IdyeCx/YsF5cP5NY9o=,iv:hN0s2oiTtiD9tQr06+1aCCDzLwZk5ZAc05oKanoP0RE=,tag:TPyuOpNPkw0ocoB8zXLg4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
